In [5]:
import os
import pandas as pd
import numpy as np

In [14]:
# ── Base directories ──────────────────────────────────────────────────────────
BASE_DIR   = '/storage/Arushi/090526_EvoAge/kg_formation/'
PROC_DIR   = BASE_DIR + 'processed_data/'
DB_DIR     = BASE_DIR + 'data_collection/databases_for_mapping/'

# ── Required output schema ────────────────────────────────────────────────────
REQUIRED_COLS = [
    'head', 'relation', 'tail',
    'head_type', 'relation_type', 'tail_type',
    'kg_source',
    'head_id_is', 'tail_id_is',
    'head_detail_name', 'tail_detail_name', 'kg_type', 'species'
]

# POSITIVE ASSOCIATION

In [20]:
# ── Output path ───────────────────────────────────────────────────────────────
OUT_PATH   = BASE_DIR + 'processed_data_relation_wise_merge/generalised/CHEMICAL_POSITIVEASSOC_BIOLOGICALPROCESS/ALL_CHEMICAL_POSITIVEASSOC_BIOLOGICALPROCESS_Human.parquet'

In [24]:
# AgeXtend
AgingAtlas_POSS_ASS = pd.read_csv(PROC_DIR + 'agingatlas/Human/ChemicalEntity_PositivelyAssociatedWithAging_BiologicalProcess_Metabolites.csv')
AgingAtlas_POSS_ASS.columns = AgingAtlas_POSS_ASS.columns.str.lower()
# AgingAtlas_POSS_ASS.rename(columns={'relation_source': 'kg_source'}, inplace=True)
AgingAtlas_POSS_ASS['kg_type'] = 'Aging'
AgingAtlas_POSS_ASS['kg_source'] = 'AgingAtlas'
AgingAtlas_POSS_ASS['relation'] = 'ChemicalEntity_PositivelyAssociatedWithAging_BiologicalProcess'
AgingAtlas_POSS_ASS['head_id_is'] = 'Pubchem'
AgingAtlas_POSS_ASS['tail_id_is'] = 'Quick_GO'
AgingAtlas_POSS_ASS['tail_detail_name'] = 'aging'

AgingAtlas_POSS_ASS['species'] = 'Homo sapiens'

AgingAtlas_POSS_ASS

,head,relation,tail,head_type,tail_type,head_detail_name,head_smile_name,relation_source,species,head_alt_name,cell/tissue,treatment,log2 fc,p,kg_type,kg_source,head_id_is,tail_id_is,tail_detail_name
0,20822574,ChemicalEntity_PositivelyAssociatedWithAging_B...,GO:0007568,ChemicalEntity,BiologicalProcess,(4-ethylphenyl) hydrogen sulfate,CCC1=CC=C(C=C1)OS(=O)(=O)O,Aging_Atlas_Metabolites,Homo sapiens,4-ethylphenyl sulfate,Kidney,Young VS Old,-2.86017,0.049630,Aging,AgingAtlas,Pubchem,Quick_GO,aging
1,10243361,ChemicalEntity_PositivelyAssociatedWithAging_B...,GO:0007568,ChemicalEntity,BiologicalProcess,(2S)-2-(4-aminobutanoylamino)-3-(1H-imidazol-5...,C1=C(NC=N1)C[C@@H](C(=O)O)NC(=O)CCCN,Aging_Atlas_Metabolites,Homo sapiens,homocarnosine,Muscle,Young VS Old,-1.32838,0.047988,Aging,AgingAtlas,Pubchem,Quick_GO,aging
2,5280961,ChemicalEntity_PositivelyAssociatedWithAging_B...,GO:0007568,ChemicalEntity,BiologicalProcess,"5,7-dihydroxy-3-(4-hydroxyphenyl)chromen-4-one",C1=CC(=CC=C1C2=COC3=CC(=CC(=C3C2=O)O)O)O,Aging_Atlas_Metabolites,Homo sapiens,genistein,Kidney,Young VS Old,-3.54275,0.047700,Aging,AgingAtlas,Pubchem,Quick_GO,aging
3,1198,ChemicalEntity_PositivelyAssociatedWithAging_B...,GO:0007568,ChemicalEntity,BiologicalProcess,"1-hydroxypropane-1,2,3-tricarboxylic acid",C(C(C(C(=O)O)O)C(=O)O)C(=O)O,Aging_Atlas_Metabolites,Homo sapiens,isocitrate,Kidney,Young VS Old,-1.65370,0.047401,Aging,AgingAtlas,Pubchem,Quick_GO,aging
4,134731361,ChemicalEntity_PositivelyAssociatedWithAging_B...,GO:0007568,ChemicalEntity,BiologicalProcess,"(2R,3R,4S,5S,6R)-2-[(2S,3R,4S,5S,6S)-4,5-dihyd...",C([C@@H]1[C@H]([C@@H]([C@H]([C@H](O1)O[C@H]2[C...,Aging_Atlas_Metabolites,Homo sapiens,maltotriose,Muscle,Young VS Old,-1.56716,0.041185,Aging,AgingAtlas,Pubchem,Quick_GO,aging
5,3083620,ChemicalEntity_PositivelyAssociatedWithAging_B...,GO:0007568,ChemicalEntity,BiologicalProcess,3-(1H-imidazol-5-yl)-2-(trimethylazaniumyl)pro...,C[N+](C)(C)C(CC1=CN=CN1)C(=O)[O-],Aging_Atlas_Metabolites,Homo sapiens,histidine betaine (hercynine)*,Plasma,Young VS Old,-1.03210,0.038184,Aging,AgingAtlas,Pubchem,Quick_GO,aging
6,22844748,ChemicalEntity_PositivelyAssociatedWithAging_B...,GO:0007568,ChemicalEntity,BiologicalProcess,(2S)-2-amino-5-[[(1S)-1-carboxy-2-hydroxyethyl...,C(CC(=O)N[C@@H](CO)C(=O)O)[C@@H](C(=O)O)N,Aging_Atlas_Metabolites,Homo sapiens,gamma-glutamylserine,Heart,Young VS Old,-1.24592,0.037639,Aging,AgingAtlas,Pubchem,Quick_GO,aging
7,5288409,ChemicalEntity_PositivelyAssociatedWithAging_B...,GO:0007568,ChemicalEntity,BiologicalProcess,"(2R,3R,4S,5S,6R)-2-[(2R,3S,4R,5R,6R)-6-[(2R,3S...",C([C@@H]1[C@H]([C@@H]([C@H]([C@H](O1)O[C@@H]2[...,Aging_Atlas_Metabolites,Homo sapiens,maltohexaose,Muscle,Young VS Old,-1.21506,0.037406,Aging,AgingAtlas,Pubchem,Quick_GO,aging
8,59040790,ChemicalEntity_PositivelyAssociatedWithAging_B...,GO:0007568,ChemicalEntity,BiologicalProcess,trimethyl-[2-[(Z)-octadec-9-enoyl]oxyethyl]aza...,CCCCCCCC/C=C\CCCCCCCC(=O)OCC[N+](C)(C)C,Aging_Atlas_Metabolites,Homo sapiens,oleoylcholine,Plasma,Young VS Old,-1.55837,0.035134,Aging,AgingAtlas,Pubchem,Quick_GO,aging
9,153005,ChemicalEntity_PositivelyAssociatedWithAging_B...,GO:0007568,ChemicalEntity,BiologicalProcess,[4-(2-aminoethyl)phenyl] hydrogen sulfate,C1=CC(=CC=C1CCN)OS(=O)(=O)O,Aging_Atlas_Metabolites,Homo sapiens,tyramine O-sulfate,Kidney,Young VS Old,-1.39017,0.034944,Aging,AgingAtlas,Pubchem,Quick_GO,aging
10,1005,ChemicalEntity_PositivelyAssociatedWithAging_B...,GO:0007568,ChemicalEntity,BiologicalProcess,2-phosphonooxyprop-2-enoic acid,C=C(C(=O)O)OP(=O)(O)O,Aging_Atlas_Metabolites,Homo sapiens,phosphoenolpyruvate (PEP),Heart,Young VS Old,-1.50386,0.033960,Aging,AgingAtlas,Pubchem,Quick_GO,aging
11,45109807,ChemicalEntity_PositivelyAssociatedWithAging_B...,GO:0007568,ChemicalEntity,BiologicalProcess,"(2R,3S,4S,5R)-2-(hydroxymethyl)-6-[(2R,3S,4R,5...",C([C@@H]1[C@H]([C@@H]([C@H](C(O1)O[C@@H]2[C@H]...,Aging_Atlas_Metabolites,Homo sapiens,maltose,Muscle,Young VS Old,-1.26586,0.033833,Aging,AgingAtlas,Pubchem,Quick_GO,aging
12,75810,ChemicalEntity_PositivelyAssociatedWithAging_B...,GO:0007568,ChemicalEntity,BiologicalProcess,2-(1-methylimidazol-4-yl)acetic acid,CN1C=C(N=C1)CC(=O)O,Aging_Atlas_Metabolites,Homo sapiens,1-methyl-4-imidazoleacetate,Kidney,Young VS Old,-1.05887,0.032365,Aging,AgingAtlas,Pubchem,Quick_GO,aging
13,96215,ChemicalEntity_PositivelyAssociatedWithAging_B...,GO:0007568,ChemicalEntity,BiologicalProcess,2-(1H-imidazol-5-yl)acetic acid,C1=C(NC=N1)CC(=O)O,Aging_Atlas_Metabolites,Homo sapiens,4-imidazoleacetate,Kidney,Young VS Old,-1.61231,0.031965,Aging,AgingAtlas,Pubchem,Quick_GO,aging
14,5570,ChemicalEntity_PositivelyAssociatedWithAging_B...,GO:0007568,ChemicalEntity,BiologicalProcess,1-methylpyridin-1-ium-3-carboxylate,C[N+]1=CC=CC(=C1)C(=O)[O-],Aging_Atlas_Metabolites,Homo sapiens,trigonelline (N'-methylnicotinate),Kidney,Young VS Old,-2.17766,0.031259,Aging,AgingAtlas,Pubchem,Quick_GO,aging
15,150914,ChemicalEntity_PositivelyAssociatedWithAging_B...,GO:0007568,ChemicalEntity,BiologicalProcess,(2S)-2-amino-5-[[(1S)-4-amino-1-carboxy-4-oxob...,C(CC(=O)N[C@@H](CCC(=O)N)C(=O)O)[C@@H](C(=O)O)N,Aging_Atlas_Metabolites,Homo sapiens,gamma-glutamylglutamine,Heart,Young VS Old,-1.52637,0.029827,Aging,AgingAtlas,Pubchem,Quick_GO,aging
16,1102,ChemicalEntity_PositivelyAssociatedWithAging_B...,GO:0007568,ChemicalEntity,BiologicalProcess,"N'-(3-aminopropyl)butane-1,4-diamine",C(CCNCCCN)CN,Aging_Atlas_Metabolites,Homo sapiens,spermidine,Heart,Young VS Old,-1.28558,0.028977,Aging,AgingAtlas,Pubchem,Quick_GO,aging
17,5280961,ChemicalEntity_PositivelyAssociatedWithAging_B...,GO:0007568,ChemicalEntity,BiologicalProcess,"5,7-dihydroxy-3-(4-hydroxyphenyl)chromen-4-one",C1=CC(=CC=C1C2=COC3=CC(=CC(=C3C2=O)O)O)O,Aging_Atlas_Metabolites,Homo sapiens,genistein,Liver,Young VS Old,-1.90435,0.028839,Aging,AgingAtlas,Pubchem,Quick_GO,aging
18,5281708,ChemicalEntity_PositivelyAssociatedWithAging_B...,GO:0007568,ChemicalEntity,BiologicalProcess,7-hydroxy-3-(4-hydroxyphenyl)chromen-4-one,C1=CC(=CC=C1C2=COC3=C(C2=O)C=CC(=C3)O)O,Aging_Atlas_Metabolites,Homo sapiens,daidzein,Liver,Young VS Old,-2.05596,0.028244,Aging,AgingAtlas,Pubchem,Quick_GO,aging
19,46891780,ChemicalEntity_PositivelyAssociatedWithAging_B...,GO:0007568,ChemicalEntity,BiologicalProcess,2-azaniumylethyl [(2R)-3-hexadecanoyloxy-2-[(9...,CCCCCCCCCCCCCCCC(=O)OC[C@H](COP(=O)([O-])OCC[N...,Aging_Atlas_Metabolites,Homo sapiens,1-palmitoyl-2-linoleoyl-GPE (16:0/18:2),Plasma,Young VS Old,-1.29907,0.027850,Aging,AgingAtlas,Pubchem,Quick_GO,aging
20,5255,ChemicalEntity_PositivelyAssociatedWithAging_B...,GO:0007568,ChemicalEntity,BiologicalProcess,2-[(2-acetamido-3-carboxypropanoyl)amino]penta...,CC(=O)NC(CC(=O)O)C(=O)NC(CCC(=O)O)C(=O)O,Aging_Atlas_Metabolites,Homo sapiens,N-acetyl-aspartyl-glutamate (NAAG),Kidney,Young VS Old,-1.02694,0.026225,Aging,AgingAtlas,Pubchem,Quick_GO,aging
21,10140,ChemicalEntity_PositivelyAssociatedWithAging_B...,GO:0007568,ChemicalEntity,BiologicalProcess,"2-[[(4R)-4-[(3R,5S,7R,8R,9S,10S,12S,13R,14S,17...",C[C@H](CCC(=O)NCC(=O)O)[C@H]1CC[C@@H]2[C@@]1([...,Aging_Atlas_Metabolites,Homo sapiens,glycocholate,Kidney,Young VS Old,-2.32634,0.024789,Aging,AgingAtlas,Pubchem,Quick_GO,aging
22,9085,ChemicalEntity_PositivelyAssociatedWithAging_B...,GO:0007568,ChemicalEntity,BiologicalProcess,(2S)-2-amino-6-(diaminomethylideneamino)hexano...,C(CCN=C(N)N)C[C@@H](C(=O)O)N,Aging_Atlas_Metabolites,Homo sapiens,homoarginine,Heart,Young VS Old,-1.11270,0.024675,Aging,AgingAtlas,Pubchem,Quick_GO,aging
23,45,ChemicalEntity_PositivelyAssociatedWithAging_B...,GO:0007568,ChemicalEntity,BiologicalProcess,2-hydroxypropanedioic acid,C(C(=O)O)(C(=O)O)O,Aging_Atlas_Metabolites,Homo sapiens,tartronate (hydroxymalonate),Kidney,Young VS Old,-1.28018,0.020746,Aging,AgingAtlas,Pubchem,Quick_GO,aging
24,71920,ChemicalEntity_PositivelyAssociatedWithAging_B...,GO:0007568,ChemicalEntity,BiologicalProcess,"[(2S)-2,3-dihydroxypropyl] 2-(trimethylazanium...",C[N+](C)(C)CCOP(=O)([O-])OC[C@H](CO)O,Aging_Atlas_Metabolites,Homo sapiens,glycerophosphorylcholine (GPC),Muscle,Young VS Old,-1.53859,0.020049,Aging,AgingAtlas,Pubchem,Quick_GO,aging
25,5461127,ChemicalEntity_PositivelyAssociatedWithAging_B...,GO:0007568,ChemicalEntity,BiologicalProcess,"(2R,3S,4S,5R)-2,3,4,5,6-pentahydroxyhexanoate",C([C@H]([C@@H]([C@@H]([C@H](C(=O)[O-])O)O)O)O)O,Aging_Atlas_Metabolites,Homo sapiens,galactonate,Kidney,Young VS Old,-1.34329,0.019272,Aging,AgingAtlas,Pubchem,Quick_GO,aging
26,1175,ChemicalEntity_PositivelyAssociatedWithAging_B...,GO:0007568,ChemicalEntity,BiologicalProcess,"7,9-dihydro-3H-purine-2,6,8-trione",C12=C(NC(=O)N1)NC(=O)NC2=O,Aging_Atlas_Metabolites,Homo sapiens,urate,Heart,Young VS Old,-2.55171,0.018511,Aging,AgingAtlas,Pubchem,Quick_GO,aging
27,3083879,ChemicalEntity_PositivelyAssociatedWithAging_B...,GO:0007568,ChemicalEntity,BiologicalProcess,(2-hydroxyphenyl) hydrogen sulfate,C1=CC=C(C(=C1)O)OS(=O)(=O)O,Aging_Atlas_Metabolites,Homo sapiens,catechol sulfate,Skin,Young VS Old,-2.00367,0.016449,Aging,AgingAtlas,Pubchem,Quick_GO,aging
28,53356659,ChemicalEntity_PositivelyAssociatedWithAging_B...,GO:0007568,ChemicalEntity,BiologicalProcess,"3-[18-(2-carboxyethyl)-8,13-bis(ethenyl)-3,7,1...",CC1=C(C2=CC3=NC(=CC4=C(C(=C([N-]4)C=C5C(=C(C(=...,Aging_Atlas_Metabolites,Homo sapiens,heme,Heart,Young VS Old,-2.12297,0.016119,Aging,AgingAtlas,Pubchem,Quick_GO,aging
29,13489094,ChemicalEntity_PositivelyAssociatedWithAging_B...,GO:0007568,ChemicalEntity,BiologicalProcess,"(2R,3R,4S,5S,6R)-2-[(2R,3S,4R,5R,6R)-6-[(2R,3S...",C([C@@H]1[C@H]([C@@H]([C@H]([C@H](O1)O[C@@H]2[...,Aging_Atlas_Metabolites,Homo sapiens,maltopentaose,Muscle,Young VS Old,-1.98207,0.015958,Aging,AgingAtlas,Pubchem,Quick_GO,aging
30,75124209,ChemicalEntity_PositivelyAssociatedWithAging_B...,GO:0007568,ChemicalEntity,BiologicalProcess,"(2S,3S,4S,5R,6S)-3,4,5-trihydroxy-6-(2-hydroxy...",C1=CC=C(C(=C1)O)O[C@H]2[C@@H]([C@H]([C@@H]([C@...,Aging_Atlas_Metabolites,Homo sapiens,catechol glucuronide,Kidney,Young VS Old,-1.55179,0.015172,Aging,AgingAtlas,Pubchem,Quick_GO,aging
31,165007,ChemicalEntity_PositivelyAssociatedWithAging_B...,GO:0007568,ChemicalEntity,BiologicalProcess,"[(2R,3R,4R,5S)-2,3,4,5,7-pentahydroxy-6-oxohep...",C([C@H]([C@H]([C@H]([C@@H](C(=O)CO)O)O)O)O)OP(...,Aging_Atlas_Metabolites,Homo sapiens,sedoheptulose-7-phosphate,Liver,Young VS Old,-1.43125,0.014757,Aging,AgingAtlas,Pubchem,Quick_GO,aging
32,1052,ChemicalEntity_PositivelyAssociatedWithAging_B...,GO:0007568,ChemicalEntity,BiologicalProcess,4-(aminomethyl)-5-(hydroxymethyl)-2-methylpyri...,CC1=NC=C(C(=C1O)CN)CO,Aging_Atlas_Metabolites,Homo sapiens,pyridoxamine,Heart,Young VS Old,-1.37995,0.013979,Aging,AgingAtlas,Pubchem,Quick_GO,aging
33,9085,ChemicalEntity_PositivelyAssociatedWithAging_B...,GO:0007568,ChemicalEntity,BiologicalProcess,(2S)-2-amino-6-(diaminomethylideneamino)hexano...,C(CCN=C(N)N)C[C@@H](C(=O)O)N,Aging_Atlas_Metabolites,Homo sapiens,homoarginine,Brain,Young VS Old,-1.14339,0.013414,Aging,AgingAtlas,Pubchem,Quick_GO,aging
34,7021854,ChemicalEntity_PositivelyAssociatedWithAging_B...,GO:0007568,ChemicalEntity,BiologicalProcess,2-[[(2S)-2-amino-3-(4-hydroxyphenyl)propanoyl]...,C1=CC(=CC=C1C[C@@H](C(=O)NCC(=O)O)N)O,Aging_Atlas_Metabolites,Homo sapiens,tyrosylglycine,Heart,Young VS Old,-1.20176,0.012522,Aging,AgingAtlas,Pubchem,Quick_GO,aging
35,5283496,ChemicalEntity_PositivelyAssociatedWithAging_B...,GO:0007568,ChemicalEntity,BiologicalProcess,[(2R)-1-[2-aminoethoxy(hydroxy)phosphoryl]oxy-...,CCCCCCCCCCCCCCCC(=O)OC[C@H](COP(=O)(O)OCCN)OC(...,Aging_Atlas_Metabolites,Homo sapiens,1-palmitoyl-2-oleoyl-GPE (16:0/18:1),Plasma,Young VS Old,-1.43867,0.012402,Aging,AgingAtlas,Pubchem,Quick_GO,aging
36,3083879,ChemicalEntity_PositivelyAssociatedWithAging_B...,GO:0007568,ChemicalEntity,BiologicalProcess,(2-hydroxyphenyl) hydrogen sulfate,C1=CC=C(C(=C1)O)OS(=O)(=O)O,Aging_Atlas_Metabolites,Homo sapiens,catechol sulfate,Kidney,Young VS Old,-3.52168,0.010835,Aging,AgingAtlas,Pubchem,Quick_GO,aging
37,9903482,ChemicalEntity_PositivelyAssociatedWithAging_B...,GO:0007568,ChemicalEntity,BiologicalProcess,(2S)-2-(3-acetamidopropanoylamino)-3-(1H-imida...,CC(=O)NCCC(=O)N[C@@H](CC1=CN=CN1)C(=O)O,Aging_Atlas_Metabolites,Homo sapiens,N-acetylcarnosine,Kidney,Young VS Old,-1.14365,0.010454,Aging,AgingAtlas,Pubchem,Quick_GO,aging
38,342532,ChemicalEntity_PositivelyAssociatedWithAging_B...,GO:0007568,ChemicalEntity,BiologicalProcess,2-[(2-amino-3-methylpentanoyl)amino]acetic acid,CCC(C)C(C(=O)NCC(=O)O)N,Aging_Atlas_Metabolites,Homo sapiens,isoleucylglycine,Heart,Young VS Old,-1.30848,0.010153,Aging,AgingAtlas,Pubchem,Quick_GO,aging
39,9903482,ChemicalEntity_PositivelyAssociatedWithAging_B...,GO:0007568,ChemicalEntity,BiologicalProcess,(2S)-2-(3-acetamidopropanoylamino)-3-(1H-imida...,CC(=O)NCCC(=O)N[C@@H](CC1=CN=CN1)C(=O)O,Aging_Atlas_Metabolites,Homo sapiens,N-acetylcarnosine,Plasma,Young VS Old,-1.34863,0.008464,Aging,AgingAtlas,Pubchem,Quick_GO,aging
40,8094,ChemicalEntity_PositivelyAssociatedWithAging_B...,GO:0007568,ChemicalEntity,BiologicalProcess,heptanoic acid,CCCCCCC(=O)O,Aging_Atlas_Metabolites,Homo sapiens,heptanoate (7:0),Skin,Young VS Old,-1.11090,0.006791,Aging,AgingAtlas,Pubchem,Quick_GO,aging
41,22473,ChemicalEntity_PositivelyAssociatedWithAging_B...,GO:0007568,ChemicalEntity,BiologicalProcess,(2-methoxyphenyl) hydrogen sulfate,COC1=CC=CC=C1OS(=O)(=O)O,Aging_Atlas_Metabolites,Homo sapiens,guaiacol sulfate,Kidney,Young VS Old,-1.72303,0.005346,Aging,AgingAtlas,Pubchem,Quick_GO,aging
42,10111,ChemicalEntity_PositivelyAssociatedWithAging_B...,GO:0007568,ChemicalEntity,BiologicalProcess,2-methylguanidine,CN=C(N)N,Aging_Atlas_Metabolites,Homo sapiens,1-methylguanidine,Brain,Young VS Old,-1.06012,0.001161,Aging,AgingAtlas,Pubchem,Quick_GO,aging
43,3614,ChemicalEntity_PositivelyAssociatedWithAging_B...,GO:0007568,ChemicalEntity,BiologicalProcess,2-(1-methylimidazol-4-yl)ethanamine,CN1C=C(N=C1)CCN,Aging_Atlas_Metabolites,Homo sapiens,1-methylhistamine,Brain,Young VS Old,-1.37496,0.000727,Aging,AgingAtlas,Pubchem,Quick_GO,aging
44,5570,ChemicalEntity_PositivelyAssociatedWithAging_B...,GO:0007568,ChemicalEntity,BiologicalProcess,1-methylpyridin-1-ium-3-carboxylate,C[N+]1=CC=CC(=C1)C(=O)[O-],Aging_Atlas_Metabolites,Homo sapiens,trigonelline (N'-methylnicotinate),Muscle,Young VS Old,-1.38880,0.000488,Aging,AgingAtlas,Pubchem,Quick_GO,aging

In [25]:
SOURCE_DFS = [
    ('AgingAtlas_POSS_ASS', AgingAtlas_POSS_ASS),
]

CONCAT_COLS = [
    'head', 'relation', 'tail',
    'head_type', 'relation_type', 'tail_type',
    'kg_source', 'head_id_is', 'tail_id_is',
    'head_detail_name', 'tail_detail_name', 'kg_type', 'species'
]

df_list = []
for name, df in SOURCE_DFS:
    tmp = df.loc[:, ~df.columns.duplicated()].copy()
    for col in CONCAT_COLS:
        if col not in tmp.columns:
            tmp[col] = pd.NA
    df_list.append(tmp[CONCAT_COLS])

final_df = pd.concat(df_list, ignore_index=True)
print(f'Combined: {len(final_df):,} rows')
final_df

def nan_summary(df):
    true_nan   = df.isna().sum()
    string_nan = df.apply(lambda c: c.astype(str).str.upper().eq('NAN').sum())
    return pd.DataFrame({
        'NaN_count':          true_nan,
        "'NAN'_string_count": string_nan,
        'Total_NaN_like':     true_nan + string_nan
    })

nan_summary(final_df)

Combined: 45 rows

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type            45                   0              45
tail_type                 0                   0               0
kg_source                 0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
kg_type                   0                   0               0
species                   0                   0               0

In [26]:
os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
final_df.to_parquet(OUT_PATH, index=False)
print(f'Saved {len(final_df):,} rows → {OUT_PATH}')

Saved 45 rows → /storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/CHEMICAL_NEGATIVEASSOC_BIOLOGICALPROCESS/ALL_CHEMICAL_NEGATIVEASSOC_BIOLOGICALPROCESS_Human.parquet

# NEGTIVE ASSOCIATION

In [27]:
# ── Output path ───────────────────────────────────────────────────────────────
OUT_PATH   = BASE_DIR + 'processed_data_relation_wise_merge/generalised/CHEMICAL_NEGATIVEASSOC_BIOLOGICALPROCESS/ALL_CHEMICAL_NEGATIVEASSOC_BIOLOGICALPROCESS_Human.parquet'

In [30]:
# AgeXtend ALL
AgingAtlas_NEG_ASS = pd.read_csv(PROC_DIR + 'agingatlas/Human/ChemicalEntity_NegativelyAssociatedWithAging_BiologicalProcess_Metabolites.csv')
AgingAtlas_NEG_ASS.columns = AgingAtlas_NEG_ASS.columns.str.lower()
AgingAtlas_NEG_ASS.rename(columns={'relation_source': 'kg_source'}, inplace=True)

AgingAtlas_NEG_ASS['relation'] = 'ChemicalEntity_NegativelyAssociatedWithAging_BiologicalProcess'
AgingAtlas_NEG_ASS['head_id_is'] = 'Pubchem'
AgingAtlas_NEG_ASS['tail_id_is'] = 'Quick_GO'
AgingAtlas_NEG_ASS['tail_detail_name'] = 'aging'
AgingAtlas_NEG_ASS['kg_type'] = 'Aging'
AgingAtlas_NEG_ASS['kg_source'] = 'AgingAtlas'
AgingAtlas_NEG_ASS['species'] = 'Homo sapiens'
AgingAtlas_NEG_ASS

,head,relation,tail,head_type,tail_type,head_detail_name,head_smile_name,kg_source,species,head_alt_name,cell/tissue,treatment,log2 fc,p,head_id_is,tail_id_is,tail_detail_name,kg_type
0,5958,ChemicalEntity_NegativelyAssociatedWithAging_B...,GO:0007568,ChemicalEntity,BiologicalProcess,"[(2R,3S,4S,5R)-3,4,5,6-tetrahydroxyoxan-2-yl]m...",C([C@@H]1[C@H]([C@@H]([C@H](C(O1)O)O)O)O)OP(=O...,AgingAtlas,Homo sapiens,glucose 6-phosphate,White adipose tissue,Young VS Old,2.86050,0.049167,Pubchem,Quick_GO,aging,Aging
1,5460358,ChemicalEntity_NegativelyAssociatedWithAging_B...,GO:0007568,ChemicalEntity,BiologicalProcess,"(2R)-2,3-dihydroxypropanoate",C([C@H](C(=O)[O-])O)O,AgingAtlas,Homo sapiens,glycerate,White adipose tissue,Young VS Old,2.11179,0.048887,Pubchem,Quick_GO,aging,Aging
2,90659885,ChemicalEntity_NegativelyAssociatedWithAging_B...,GO:0007568,ChemicalEntity,BiologicalProcess,(3R)-3-(3-hydroxybutanoyloxy)-4-(trimethylazan...,CC(CC(=O)O[C@H](CC(=O)[O-])C[N+](C)(C)C)O,AgingAtlas,Homo sapiens,(R)-3-hydroxybutyrylcarnitine,Skin,Young VS Old,1.52903,0.048584,Pubchem,Quick_GO,aging,Aging
3,439224,ChemicalEntity_NegativelyAssociatedWithAging_B...,GO:0007568,ChemicalEntity,BiologicalProcess,(2S)-2-(3-aminopropanoylamino)-3-(1H-imidazol-...,C1=C(NC=N1)C[C@@H](C(=O)O)NC(=O)CCN,AgingAtlas,Homo sapiens,carnosine,Liver,Young VS Old,1.08779,0.048096,Pubchem,Quick_GO,aging,Aging
4,5281120,ChemicalEntity_NegativelyAssociatedWithAging_B...,GO:0007568,ChemicalEntity,BiologicalProcess,(Z)-tetracos-15-enoic acid,CCCCCCCC/C=C\CCCCCCCCCCCCCC(=O)O,AgingAtlas,Homo sapiens,nervonate (24:1n9)*,White adipose tissue,Young VS Old,1.16327,0.047929,Pubchem,Quick_GO,aging,Aging
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
223,111,ChemicalEntity_NegativelyAssociatedWithAging_B...,GO:0007568,ChemicalEntity,BiologicalProcess,3-(carbamoylamino)propanoic acid,C(CNC(=O)N)C(=O)O,AgingAtlas,Homo sapiens,3-ureidopropionate,Skin,Young VS Old,1.06582,0.000522,Pubchem,Quick_GO,aging,Aging
224,6613,ChemicalEntity_NegativelyAssociatedWithAging_B...,GO:0007568,ChemicalEntity,BiologicalProcess,"3-[[(2R)-2,4-dihydroxy-3,3-dimethylbutanoyl]am...",CC(C)(CO)[C@H](C(=O)NCCC(=O)O)O,AgingAtlas,Homo sapiens,pantothenate (Vitamin B5),Muscle,Young VS Old,1.14698,0.000383,Pubchem,Quick_GO,aging,Aging
225,193344,ChemicalEntity_NegativelyAssociatedWithAging_B...,GO:0007568,ChemicalEntity,BiologicalProcess,(2S)-2-amino-6-(dimethylamino)hexanoic acid,CN(C)CCCC[C@@H](C(=O)O)N,AgingAtlas,Homo sapiens,"N6,N6-dimethyllysine",Kidney,Young VS Old,1.60634,0.000124,Pubchem,Quick_GO,aging,Aging
226,7021854,ChemicalEntity_NegativelyAssociatedWithAging_B...,GO:0007568,ChemicalEntity,BiologicalProcess,2-[[(2S)-2-amino-3-(4-hydroxyphenyl)propanoyl]...,C1=CC(=CC=C1C[C@@H](C(=O)NCC(=O)O)N)O,AgingAtlas,Homo sapiens,tyrosylglycine,Liver,Young VS Old,1.60410,0.000086,Pubchem,Quick_GO,aging,Aging
227,6932058,ChemicalEntity_NegativelyAssociatedWithAging_B...,GO:0007568,ChemicalEntity,BiologicalProcess,1H-indole-3-carboxylate,C1=CC=C2C(=C1)C(=CN2)C(=O)[O-],AgingAtlas,Homo sapiens,indole-3-carboxylate,Plasma,Young VS Old,1.42430,0.000067,Pubchem,Quick_GO,aging,Aging

In [32]:
SOURCE_DFS = [
    ('AgingAtlas_NEG_ASS', AgingAtlas_NEG_ASS),
]

CONCAT_COLS = [
    'head', 'relation', 'tail',
    'head_type', 'relation_type', 'tail_type',
    'kg_source', 'head_id_is', 'tail_id_is',
    'head_detail_name', 'tail_detail_name', 'kg_type', 'species'
]

df_list = []
for name, df in SOURCE_DFS:
    tmp = df.loc[:, ~df.columns.duplicated()].copy()
    for col in CONCAT_COLS:
        if col not in tmp.columns:
            tmp[col] = pd.NA
    df_list.append(tmp[CONCAT_COLS])

final_df = pd.concat(df_list, ignore_index=True)
print(f'Combined: {len(final_df):,} rows')
final_df

def nan_summary(df):
    true_nan   = df.isna().sum()
    string_nan = df.apply(lambda c: c.astype(str).str.upper().eq('NAN').sum())
    return pd.DataFrame({
        'NaN_count':          true_nan,
        "'NAN'_string_count": string_nan,
        'Total_NaN_like':     true_nan + string_nan
    })

nan_summary(final_df)

Combined: 228 rows

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type           228                   0             228
tail_type                 0                   0               0
kg_source                 0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
kg_type                   0                   0               0
species                   0                   0               0

In [33]:
os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
final_df.to_parquet(OUT_PATH, index=False)
print(f'Saved {len(final_df):,} rows → {OUT_PATH}')

Saved 228 rows → /storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/CHEMICAL_NEGATIVEASSOC_BIOLOGICALPROCESS/ALL_CHEMICAL_NEGATIVEASSOC_BIOLOGICALPROCESS_Human.parquet