In [ ]:
import pandas as pd
import numpy as np
import os

# Mapping Setup

In [2]:
BASE_PATH = "/storage/Arushi/090526_EvoAge/kg_formation/data_collection/"
OUT_PATH = "/storage/Arushi/090526_EvoAge/kg_formation/processed_data/"

## PubChem

In [4]:
import pandas as pd
Pubchem_Syn_fil  =  pd.read_csv(f'{BASE_PATH}databases_for_mapping/pubchem/CID-Synonym-filtered', sep= '\t', header = None)
Pubchem_Syn_fil
Pubchem_Syn_fil_dict = dict(zip(Pubchem_Syn_fil[1],Pubchem_Syn_fil[0]))
# del Pubchem_Syn_fil
Pubchem_Syn_fil_dict

Pubchem_Syn_fil_dict_lower = {str(k).lower(): v for k, v in Pubchem_Syn_fil_dict.items()}

In [5]:
## Pubchem_2_name 

Pubchem =pd.read_pickle(f'{BASE_PATH}databases_for_mapping/pubchem/combined_df.pkl')
Pubchem.head()

Pubchem

Pubchem_CID_Smile_Dict  = dict(zip(Pubchem['PUBCHEM_COMPOUND_CID'], Pubchem['PUBCHEM_SMILES']))
Pubchem_CID_Smile_Dict

Pubchem_IUPAC_CID_Dict  = dict(zip(Pubchem['PUBCHEM_COMPOUND_CID'], Pubchem['PUBCHEM_IUPAC_NAME']))

## MESH

In [6]:
Mesh2DOID = pd.read_csv(f'{BASE_PATH}databases_for_mapping/DO/HumanDiseaseOntology-main/DOreports/MESHinDO.tsv', sep='\t')
Mesh2DOID.rename(columns={"ID": "id", "LABEL": "label"}, inplace=True)
Mesh2DOID
# Explode xrefs column by splitting on ', '
Mesh2DOID['xrefs'] = Mesh2DOID['xrefs'].str.split(', ')
Mesh2DOID = Mesh2DOID.explode('xrefs')
Mesh2DOID["xrefs"] = Mesh2DOID["xrefs"].astype(str).str.replace(r'MESH:', '', regex=True)
Mesh2DOID

Mesh2DOID[Mesh2DOID['xrefs'] == 'C0001418']

Mesh2DOID_dict = dict(zip(Mesh2DOID['xrefs'],Mesh2DOID['id']))
Mesh2DOID_dict

Mesh2DOID_dict.get('C0001418')

Meshname2DOID_dict = dict(zip(Mesh2DOID['label'],Mesh2DOID['xrefs']))
Meshname2DOID_dict

Mesh2DOID
Meshname2DOID_dict = dict(zip(Mesh2DOID['label'],Mesh2DOID['xrefs']))
Meshname2DOID_dict

# Mesh2DOID[Mesh2DOID['label']=='shock']

{'angiosarcoma': 'D006394',
 'disease of metabolism': 'D008659',
 'autoimmune pancreatitis': 'D000081012',
 'Rocky Mountain spotted fever': 'D012373',
 'erysipeloid': 'D004887',
 'adiaspiromycosis': 'C000656784',
 'Keshan disease': 'C536166',
 'tinea barbae': 'C000656825',
 'La Crosse encephalitis': 'D004670',
 'hemophagocytic lymphohistiocytosis': 'D051359',
 'superficial mycosis': 'D010854',
 'podoconiosis': 'D004604',
 'Kartagener syndrome': 'D007619',
 'otomycosis': 'D059249',
 'aspiration pneumonia': 'D011015',
 'idiopathic pulmonary fibrosis': 'D054990',
 'cryptogenic organizing pneumonia': 'D018549',
 'desquamative interstitial pneumonia': 'C562470',
 'lymphoid interstitial pneumonia': 'C562489',
 'inhalation anthrax': 'C571912',
 'tick-borne encephalitis': 'D004675',
 'erythema multiforme': 'D004892',
 'Lambert-Eaton myasthenic syndrome': 'D015624',
 'angiostrongyliasis': 'C536369',
 'tungiasis': 'D058285',
 'Trichomonas vaginalis trichomoniasis': 'D014247',
 'fusariosis': 'D060585',
 'trichosporonosis': 'D060586',
 'aniseikonia': 'D000839',
 'congenital hypothyroidism': 'D003409',
 'bradyopsia': 'C564243',
 'hypophosphatemia': 'D017674',
 'complement factor I deficiency': 'C572568',
 'familial adenomatous polyposis': 'D011125',
 'restless legs syndrome': 'D012148',
 'Stevens-Johnson syndrome': 'D013262',
 'xeroderma pigmentosum': 'D014983',
 'nonepidermolytic palmoplantar keratoderma': 'C563422',
 'Hailey-Hailey disease': 'D016506',
 'multiple endocrine neoplasia type 2A': 'D018813',
 'arrhythmogenic right ventricular cardiomyopathy': 'D019571',
 'Asperger syndrome': 'D020817',
 'fatal familial insomnia': 'D034062',
 'Andersen-Tawil syndrome': 'D050030',
 'mulibrey nanism': 'D050336',
 'Danon disease': 'D052120',
 'Frasier syndrome': 'D052159',
 'Usher syndrome': 'D052245',
 'familial partial lipodystrophy': 'D052496',
 'mucosulfatidosis': 'D052517',
 'infantile Refsum disease': 'D052919',
 'X-linked dominant hypophosphatemic rickets': 'D053098',
 'white sponge nevus': 'D053529',
 'pachyonychia congenita': 'D053549',
 'Gitelman syndrome': 'D053579',
 'Brugada syndrome': 'D053840',
 'mevalonic aciduria': 'D054078',
 'lissencephaly': 'D054082',
 'periventricular nodular heterotopia': 'D054091',
 'Buruli ulcer disease': 'D054312',
 'Sertoli cell-only syndrome': 'D054331',
 'juvenile myelomonocytic leukemia': 'D054429',
 'hyperphosphatemia': 'D054559',
 'Wolf-Hirschhorn syndrome': 'D054877',
 'aspartylglucosaminuria': 'D054880',
 'campomelic dysplasia': 'D055036',
 'Farber lipogranulomatosis': 'D055577',
 'Muir-Torre syndrome': 'D055653',
 'Loeys-Dietz syndrome': 'D055947',
 'erythrokeratodermia variabilis': 'D056266',
 'yellow nail syndrome': 'D056684',
 'Costello syndrome': 'D056685',
 'Donohue syndrome': 'D056731',
 'Carney complex': 'D056733',
 'monilethrix': 'D056734',
 'Alstrom syndrome': 'D056769',
 'Weill-Marchesani syndrome': 'D056846',
 'Barth syndrome': 'D056889',
 'Liddle syndrome': 'D056929',
 'sennetsu fever': 'C537582',
 'exanthem': 'D005076',
 'exanthema subitum': 'D005077',
 'adult T-cell leukemia/lymphoma': 'D015459',
 'adult spinal muscular atrophy': 'C563948',
 'intermediate spinal muscular atrophy': 'D014897',
 'congenital stationary night blindness': 'C537743',
 'hypermethioninemia': 'C564683',
 'familial medullary thyroid carcinoma': 'C536911',
 'hereditary sensory neuropathy': 'D009477',
 'Walker-Warburg syndrome': 'D058494',
 'Lennox-Gastaut syndrome': 'D065768',
 'West syndrome': 'D013036',
 'nonsyndromic deafness': 'C580334',
 'congenital disorder of glycosylation type II': 'C535747',
 '2-hydroxyglutaric aciduria': 'C535306',
 'Senior-Loken syndrome': 'C537580',
 'cranioectodermal dysplasia': 'C562966',
 'brachydactyly': 'D059327',
 'trichotillomania': 'D014256',
 'inflammatory bowel disease': 'D015212',
 'tooth agenesis': 'D000848',
 'intestinal schistosomiasis': 'D012554',
 'ABCD syndrome': 'C535334',
 'acrocapitofemoral dysplasia': 'C564334',
 'acrodermatitis enteropathica': 'C538178',
 'paranasal sinus cancer': 'D010255',
 'Aland Island eye disease': 'C562664',
 'Allan-Herndon-Dudley syndrome': 'C537047',
 'oculocutaneous albinism': 'D016115',
 'ocular albinism 1': 'D016117',
 'alopecia universalis': 'C537055',
 'alternating hemiplegia of childhood': 'C536589',
 'Rh deficiency syndrome': 'C562717',
 'arterial calcification of infancy': 'C537440',
 'arterial tortuosity syndrome': 'C565942',
 'Arts syndrome': 'C535388',
 'atrioventricular septal defect': 'D004694',
 'Baller-Gerold syndrome': 'C536788',
 'Bannayan-Riley-Ruvalcaba syndrome': 'D006223',
 'biotin-responsive basal ganglia disease': 'C537658',
 'vitelliform macular dystrophy': 'D057826',
 'bestrophinopathy': 'C567518',
 'Bethlem myopathy': 'C535436',
 'Birk-Barel syndrome': 'C567357',
 'Birt-Hogg-Dube syndrome': 'D058249',
 'Bjornstad syndrome': 'C537633',
 'Blau syndrome': 'C538157',
 'Boomerang dysplasia': 'C536573',
 'Borjeson-Forssman-Lehmann syndrome': 'C536575',
 'Bothnia retinal dystrophy': 'C564392',
 'Bowen-Conradi syndrome': 'C537081',
 'organ system cancer': 'D009371',
 'brachydactyly-syndactyly syndrome': 'C565193',
 'brachyolmia': 'C537098',
 'Brody myopathy': 'C536607',
 'Brown-Vialetto-Van Laere syndrome': 'C537111',
 'chorioamnionitis': 'D002821',
 'Dent disease': 'D057973',
 'cardiomyopathy': 'D009202',
 'PHGDH deficiency': 'C566618',
 'vitamin B12 deficiency': 'D014806',
 'Qazi Markouizos syndrome': 'C536259',
 'nicotine dependence': 'D014029',
 'diffuse large B-cell lymphoma': 'D016403',
 'mantle cell lymphoma': 'D020522',
 'marginal zone lymphoma': 'D018442',
 'cerebellar ataxia': 'D002524',
 'deafness-dystonia-optic neuronopathy syndrome': 'C535808',
 'myotonic dystrophy type 2': 'D020967',
 'neuroacanthocytosis': 'D054546',
 'choreaacanthocytosis': 'D054546',
 'N syndrome': 'C536108',
 'polycystic liver disease': 'C536330',
 'pheochromocytoma': 'D010673',
 'paraganglioma': 'D010235',
 'rapadilino syndrome': 'C535288',
 'schneckenbecken dysplasia': 'C536637',
 'hydrolethalus syndrome': 'C536079',
 'Zollinger-Ellison syndrome': 'D015043',
 'secondary progressive multiple sclerosis': 'D020528',
 'primary progressive multiple sclerosis': 'D020528',
 'progressive relapsing multiple sclerosis': 'D020528',
 'juvenile polyposis syndrome': 'C537702',
 'fibular hypoplasia and complex brachydactyly': 'C537931',
 'persistent Mullerian duct syndrome': 'C536665',
 'multiple cutaneous and mucosal venous malformations': 'C563977',
 'cone dystrophy': 'D000077765',
 'achalasia microcephaly syndrome': 'C536010',
 'peroxisomal acyl-CoA oxidase deficiency': 'C536662',
 'guanidinoacetate methyltransferase deficiency': 'C537622',
 'Kahrizi syndrome': 'C567196',
 'biotin deficiency': 'C531633',
 'spondyloepimetaphyseal dysplasia, Pakistani type': 'C567551',
 'temtamy preaxial brachydactyly syndrome': 'C536958',
 'urofacial syndrome': 'C536480',
 'Stargardt disease': 'D000080362',
 'atrioventricular block': 'D054537',
 'rheumatic heart disease': 'D012214',
 'peripheral artery disease': 'D058729',
 'familial encephalopathy with neuroserpin inclusion bodies': 'C536841',
 'CHARGE syndrome': 'D058747',
 'generalized dystonia': 'D020821',
 'sleep apnea': 'D012891',
 'obstructive sleep apnea': 'D020181',
 'Muckle-Wells syndrome': 'D056587',
 'Marshall-Smith syndrome': 'C536026',
 'fibroma': 'D005350',
 'follicular lymphoma': 'D008224',
 'Caroli disease': 'D016767',
 'inclusion body myopathy with Paget disease of bone and frontotemporal dementia': 'C563476',
 'triosephosphate isomerase deficiency': 'C566029',
 'Townes-Brocks syndrome': 'C536974',
 'ameloblastoma': 'D000564',
 'medulloblastoma': 'D008527',
 'myelodysplastic syndrome': 'D009190',
 'Charlevoix-Saguenay spastic ataxia': 'C536787',
 'spastic ataxia': 'C564815',
 'spinocerebellar ataxia type 4': 'D020754',
 'spinocerebellar ataxia type 25': 'C537202',
 'spinocerebellar ataxia type 26': 'C537203',
 'episodic ataxia type 2': 'C535506',
 'cerebellar ataxia, impaired intellectual development, and dysequilibrium syndrome': 'C535731',
 'X-linked severe combined immunodeficiency': 'D053632',
 'reticular dysgenesis': 'C538361',
 'immunoglobulin alpha deficiency': 'D017098',
 'autism spectrum disorder': 'D000067877',
 'aphasia': 'D001037',
 'popliteal pterygium syndrome': 'C562509',
 'lymphoma': 'D008223',
 'non-Hodgkin lymphoma': 'D008228',
 'primary cutaneous T-cell non-Hodgkin lymphoma': 'D016410',
 'nonbacterial thrombotic endocarditis': 'D059905',
 'osteoblastoma': 'D018215',
 'pharynx cancer': 'D010610',
 'connective tissue benign neoplasm': 'D012983',
 'heavy chain disease': 'D006362',
 'apraxia': 'D001072',
 'visual agnosia': 'C531604',
 'childhood spinal muscular atrophy': 'D014897',
 "Kennedy's disease": 'D055534',
 'dentatorubral-pallidoluysian atrophy': 'D020191',
 'Kleine-Levin syndrome': 'D017593',
 'seasonal affective disorder': 'D016574',
 'histidinemia': 'C538320',
 'generalized epilepsy with febrile seizures plus': 'C565808',
 'Timothy syndrome': 'C536962',
 'succinic semialdehyde dehydrogenase deficiency': 'C535803',
 'homocarnosinosis': 'C535328',
 'colitis': 'D003092',
 'ischemic colitis': 'D017091',
 'microscopic colitis': 'D046728',
 'collagenous colitis': 'D046729',
 'lymphocytic colitis': 'D046730',
 'Clostridium difficile colitis': 'D004761',
 'ileitis': 'D007079',
 "Crohn's colitis": 'D003424',
 'Balo concentric sclerosis': 'D002549',
 'Cogan syndrome': 'D055952',
 'CREST syndrome': 'D017675',
 'agraphia': 'D000381',
 'atrial fibrillation': 'D001281',
 'acrofrontofacionasal dysostosis': 'C538186',
 'basal ganglia calcification': 'C536275',
 'branchiootic syndrome': 'C537104',
 'cardiofaciocutaneous syndrome': 'C535579',
 'Carpenter syndrome': 'C563187',
 'carnitine palmitoyltransferase II deficiency': 'C535589',
 'Warburg micro syndrome': 'C536681',
 'Van Maldergem syndrome': 'C536530',
 'Van der Woude syndrome': 'C536528',
 'UV-sensitive syndrome': 'C563466',
 '3-M syndrome': 'C535314',
 'synpolydactyly': 'C538153',
 'stuttering': 'D013342',
 'Mast syndrome': 'C565409',
 'MASA syndrome': 'C536029',
 'Smith-McCort dysplasia': 'C564589',
 'Simpson-Golabi-Behmel syndrome type 1': 'C537340',
 'scoliosis': 'D012600',
 'sclerosteosis': 'C537525',
 'sclerocornea': 'C565209',
 'scapuloperoneal myopathy': 'C536624',
 'Robinow syndrome': 'C562492',
 'Dowling-Degos disease': 'C562924',
 'dyschromatosis symmetrica hereditaria': 'C535729',
 'renal-hepatic-pancreatic dysplasia': 'C567142',
 'ptosis': 'D001763',
 'gallbladder disease': 'D005705',
 'porencephaly': 'D065708',
 'pontocerebellar hypoplasia': 'C580383',
 'pontocerebellar hypoplasia type 2A': 'C564738',
 'pontocerebellar hypoplasia type 2B': 'C567325',
 'pontocerebellar hypoplasia type 2C': 'C567324',
 'pontocerebellar hypoplasia type 3': 'C548072',
 'pontocerebellar hypoplasia type 4': 'C536716',
 'pontocerebellar hypoplasia type 5': 'C537745',
 'pontocerebellar hypoplasia type 6': 'C548074',
 'persistent hyperplastic primary vitreous': 'D054514',
 'peeling skin syndrome': 'C564818',
 'paroxysmal nocturnal hemoglobinuria': 'D006457',
 'parietal foramina': 'C566826',
 'Ohdo syndrome': 'C536232',
 'Ohdo syndrome, SBBYS variant': 'C536717',
 'oculodentodigital dysplasia': 'C563160',
 'X-linked chondrodysplasia punctata 1': 'C580533',
 'cold-induced sweating syndrome': 'C536214',
 'congenital secretory chloride diarrhea 1': 'C536210',
 'complement component 4a deficiency': 'C565167',
 'complement component 6 deficiency': 'C567307',
 'complement component 7 deficiency': 'C566443',
 'dyschromatosis universalis hereditaria': 'C535730',
 'Meier-Gorlin syndrome': 'C538012',
 'tracheomalacia': 'C557675',
 'oral hairy leukoplakia': 'D017733',
 'orofaciodigital syndrome I': 'D009958',
 'lung abscess': 'D008169',
 'acute promyelocytic leukemia': 'D015473',
 'cardiac arrest': 'D006323',
 'inguinal hernia': 'D006552',
 'umbilical hernia': 'D006554',
 'mastoiditis': 'D008417',
 'myelomeningocele': 'D008591',
 'omphalocele': 'D006554',
 'anal fistula': 'D012003',
 'ectopic pregnancy': 'D011271',
 'Rapp-Hodgkin syndrome': 'C535289',
 '3-methylglutaconic aciduria': 'C579867',
 'CEDNIK syndrome': 'C537943',
 'agnathia-otocephaly complex': 'C562503',
 'acromelic frontonasal dysostosis': 'C566345',
 'bacillary angiomatosis': 'D016917',
 'Native American myopathy': 'C538343',
 'acrorenal syndrome': 'C563159',
 'hypoparathyroidism-retardation-dysmorphism syndrome': 'C537157',
 'microcephaly with or without chorioretinopathy, lymphedema, or mental retardation': 'C537711',
 'adenine phosphoribosyltransferase deficiency': 'C538228',
 'Kleefstra syndrome 1': 'C563043',
 'Stormorken syndrome': 'C566108',
 'Vici syndrome': 'C535566',
 'chylomicron retention disease': 'C535460',
 'multiple acyl-CoA dehydrogenase deficiency': 'D054069',
 'Sakati-Nyhan syndrome': 'C537227',
 'hereditary papulotranslucent acrokeratoderma': 'C566323',
 'punctate palmoplantar keratoderma type III': 'C535653',
 'Hennekam syndrome': 'C537255',
 'orofaciodigital syndrome III': 'C557817',
 'orofaciodigital syndrome IV': 'C537133',
 'orofaciodigital syndrome V': 'C557819',
 'Joubert syndrome with orofaciodigital defect': 'C536531',
 'orofaciodigital syndrome VII': 'C563104',
 'orofaciodigital syndrome VIII': 'C557820',
 'orofaciodigital syndrome X': 'C563491',
 'orofaciodigital syndrome XI': 'C557821',
 'orofaciodigital syndrome IX': 'C557818',
 'acrofacial dysostosis Rodriguez type': 'C538183',
 'acrofacial dysostosis, Catania type': 'C538182',
 'acrofacial dysostosis, Patagonia type': 'C538185',
 'Chilblain lupus': 'C535924',
 'chondrodysplasia Blomstrand type': 'C537914',
 'chromosome 10q23 deletion syndrome': 'C567385',
 'distal 10q deletion syndrome': 'C567182',
 'chromosome 15q13.3 microdeletion syndrome': 'C567439',
 'chromosome 15q24 deletion syndrome': 'C579849',
 'chromosome 15q26-qter deletion syndrome': 'C567232',
 'chromosome 17p13.1 deletion syndrome': 'D054221',
 'chromosome 17q11.2 deletion syndrome': 'C563524',
 'chromosome 18p deletion syndrome': 'C538309',
 'chromosome 18q deletion syndrome': 'C536580',
 'chromosome 19q13.11 deletion syndrome': 'C567810',
 'NFIA-related disorder': 'C535594',
 'chromosome 1p36 deletion syndrome': 'C535362',
 'chromosome 22q11.2 deletion syndrome, distal': 'C567511',
 'chromosome 2p16.1-p15 deletion syndrome': 'C567289',
 'chromosome 2q31.2 deletion syndrome': 'C567344',
 'chromosome 3q13.31 deletion syndrome': 'C536808',
 'chromosome 3q29 microdeletion syndrome': 'C567184',
 'chromosome 6pter-p24 deletion syndrome': 'C567239',
 'SATB2-associated syndrome': 'C567350',
 'chromosome 17p13.3 duplication syndrome': 'C567705',
 'chromosome 1q21.1 duplication syndrome': 'C567290',
 'chromosome 22q11.2 microduplication syndrome': 'C567224',
 'Cole-Carpenter syndrome': 'C535963',
 'lysinuric protein intolerance': 'C562687',
 'granular corneal dystrophy 2': 'C535474',
 'congenital stromal corneal dystrophy': 'C566452',
 'X-linked endothelial corneal dystrophy': 'C567587',
 'epithelial basement membrane dystrophy': 'C535477',
 'Fleck corneal dystrophy': 'C563256',
 'gelatinous drop-like corneal dystrophy': 'C535480',
 'Lisch epithelial corneal dystrophy': 'C567588',
 'Meesmann corneal dystrophy': 'D053559',
 'posterior amorphous corneal dystrophy': 'C567546',
 'Reis-Bucklers corneal dystrophy': 'C535476',
 'subepithelial mucinous corneal dystrophy': 'C567547',
 'Thiel-Behnke corneal dystrophy': 'C535942',
 'Schnyder corneal dystrophy': 'C535475',
 'posterior polymorphous corneal dystrophy': 'C562745',
 'chromosome 3q29 microduplication syndrome': 'C567626',
 'chromosome 5p13 duplication syndrome': 'C567717',
 'chromosome Xp11.23-p11.22 duplication syndrome': 'C567585',
 'Desbuquois dysplasia': 'C535943',
 'Feingold syndrome': 'C537734',
 'fibrochondrogenesis': 'C562524',
 'gingival fibromatosis': 'C562884',
 'humeroradial synostosis': 'C535284',
 'Holt-Oram syndrome': 'C535326',
 'Miller-Dieker lissencephaly syndrome': 'D054221',
 'fetal valproate syndrome': 'C536525',
 'Kindler syndrome': 'C536321',
 'Kabuki syndrome': 'C537705',
 'Perlman syndrome': 'C536399',
 'Zika fever': 'D000071243',
 'Shwachman-Diamond syndrome': 'D000081003',
 'Goldberg-Shprintzen syndrome': 'C537279',
 'oculoauricular syndrome': 'C567416',
 'EAST syndrome': 'C557674',
 'Mowat-Wilson syndrome': 'C536990',
 'Perry syndrome': 'C566822',
 'Pitt-Hopkins syndrome': 'C537403',
 'Schimke immuno-osseous dysplasia': 'C536629',
 'SPOAN syndrome': 'C563702',
 'mitochondrial complex I deficiency': 'C537475',
 'mitochondrial complex II deficiency': 'C565375',
 'purpura fulminans': 'D055665',
 'Hermansky-Pudlak syndrome 2': 'C537709',
 'Barber-Say syndrome': 'C537908',
 'ablepharon macrostomia syndrome': 'C535557',
 'poikiloderma with neutropenia': 'C565820',
 'Kufor-Rakeb syndrome': 'C537177',
 'lethal congenital contracture syndrome 1': 'C537194',
 'lethal congenital contracture syndrome 2': 'C564369',
 'anomalous left coronary artery from the pulmonary artery': 'D063748',
 'Char syndrome': 'C566815',
 'Ritscher-Schinzel syndrome': 'C535313',
 'Holzgreve-Wagner-Rehder Syndrome': 'C535327',
 'erythema elevatum diutinum': 'C535509',
 'hypertrichotic osteochondrodysplasia Cantu type': 'C535572',
 'cardiac tuberculosis': 'D014381',
 "von Willebrand's disease 1": 'D056725',
 "von Willebrand's disease 2": 'D056728',
 'Noonan syndrome 2': 'C548081',
 'Noonan syndrome 3': 'C537847',
 'Noonan syndrome 4': 'C548082',
 'Noonan syndrome 5': 'C548083',
 'Noonan syndrome 6': 'C548084',
 'Yunis-Varon syndrome': 'C536719',
 'XFE progeroid syndrome': 'C567043',
 'WHIM syndrome 1': 'C536697',
 'atypical chronic myeloid leukemia, BCR-ABL1 negative': 'D054438',
 'Nance-Horan syndrome': 'C538336',
 'alpha-methylacyl-CoA racemase deficiency': 'C565768',
 'ankyloglossia': 'D000072676',
 'microcephalic osteodysplastic primordial dwarfism type I': 'C537577',
 'microcephalic osteodysplastic primordial dwarfism type II': 'C565898',
 'megacystis-microcolon-intestinal hypoperistalsis syndrome': 'C536138',
 'abdominal obesity-metabolic syndrome': 'C535554',
 'ulnar-mammary syndrome': 'C536937',
 'ethylmalonic encephalopathy': 'C535737',
 'primary sclerosing cholangitis': 'D015209',
 'chondrodysplasia-pseudohermaphroditism syndrome': 'C536123',
 'chronic recurrent multifocal osteomyelitis': 'C535456',
 'dicarboxylic aminoaciduria': 'C536171',
 'autosomal recessive congenital ichthyosis': 'D017490',
 'anencephaly': 'D000757',
 'Peters anomaly': 'C537884',
 'pigment dispersion syndrome': 'C563184',
 'autosomal dominant nocturnal frontal lobe epilepsy': 'C579932',
 'arteriovenous malformations of the brain': 'D002538',
 'atrichia with papular lesions': 'C565924',
 'Brunner Syndrome': 'C563156',
 'Cayman type cerebellar ataxia': 'C563363',
 'hyperekplexia': 'D000071017',
 'hyperekplexia 1': 'D000071017',
 'Muenke Syndrome': 'C537369',
 'congenital disorder of deglycosylation 1': 'C000626124',
 'congenital central hypoventilation syndrome': 'C536209',
 'chromosome 9p deletion syndrome': 'C538024',
 'methylmalonic aciduria due to methylmalonyl-CoA mutase deficiency': 'C565390',
 'Pendred Syndrome': 'C536648',
 'Doyne honeycomb retinal dystrophy': 'C535602',
 'basal laminar drusen': 'C563034',
 'immunodeficiency with hyper-IgM type 4': 'C564277',
 'restrictive dermopathy': 'C536920',
 'Smith-Magenis syndrome': 'D058496',
 'T-cell immunodeficiency, congenital alopecia, and nail dystrophy': 'C536781',
 'microvillus inclusion disease': 'C537470',
 'EEC syndrome': 'C536189',
 'ectrodactyly, ectodermal dysplasia, and cleft lip-palate syndrome 3': 'C536189',
 'ectrodactyly, ectodermal dysplasia, and cleft lip-palate syndrome 1': 'C536189',
 'syndromic X-linked intellectual disability Lubs type': 'C537723',
 'syndromic X-linked intellectual disability 5': 'C535773',
 'MEHMO syndrome': 'C537451',
 'syndromic X-linked intellectual disability 7': 'C537449',
 'syndromic X-linked intellectual disability Siderius type': 'C537333',
 'syndromic X-linked intellectual disability Abidi type': 'C535556',

## DOID

In [7]:
DO_All_File = pd.read_csv(f'{BASE_PATH}databases_for_mapping/DO/All_DO_ref_files.csv')
DOID_disname_dict = dict(zip(DO_All_File['id'], DO_All_File['label']))
DOID_disAltID_dict = dict(zip(DO_All_File['id'], DO_All_File['xrefs']))
DOID_disname_DOID_dict = dict(zip(DO_All_File['label'], DO_All_File['id']))
DO_All_File
# DOID_disAltID_dict
DOID_disname_DOID_dict

{'angiosarcoma': 'DOID:0001816',
 'pterygium': 'DOID:0002116',
 'disease of metabolism': 'DOID:0014667',
 'shrimp allergy': 'DOID:0040001',
 'aspirin allergy': 'DOID:0040002',
 'benzylpenicillin allergy': 'DOID:0040003',
 'amoxicillin allergy': 'DOID:0040004',
 'ceftriaxone allergy': 'DOID:0040005',
 'carbamazepine allergy': 'DOID:0040006',
 'abacavir allergy': 'DOID:0040007',
 'isoniazide allergy': 'DOID:0040008',
 'lidocaine allergy': 'DOID:0040009',
 'mepivacaine allergy': 'DOID:0040010',
 'phenobarbital allergy': 'DOID:0040011',
 'phenytoin allergy': 'DOID:0040012',
 'ranitidine allergy': 'DOID:0040013',
 'corticosteroid allergy': 'DOID:0040014',
 'sulfonamide allergy': 'DOID:0040015',
 'sulfamethoxazole allergy': 'DOID:0040016',
 'suprofen allergy': 'DOID:0040017',
 'thiopental allergy': 'DOID:0040018',
 'D-mannitol allergy': 'DOID:0040019',
 'cefotaxime allergy': 'DOID:0040020',
 'cephalosporin allergy': 'DOID:0040021',
 'amodiaquine allergy': 'DOID:0040022',
 'cefaclor allergy': 'DOID:0040023',
 'ceftazidime allergy': 'DOID:0040024',
 'cefuroxime allergy': 'DOID:0040025',
 'chlorhexidine allergy': 'DOID:0040026',
 'cyclophosphamide allergy': 'DOID:0040027',
 'succinylcholine allergy': 'DOID:0040028',
 'trimethoprim allergy': 'DOID:0040029',
 'cefixime allergy': 'DOID:0040030',
 'diclofenac allergy': 'DOID:0040031',
 'carbapenem allergy': 'DOID:0040032',
 'piperacillin allergy': 'DOID:0040033',
 'rocuronium allergy': 'DOID:0040034',
 'sulfasalazine allergy': 'DOID:0040035',
 'tubocurarine allergy': 'DOID:0040036',
 'aztreonam allergy': 'DOID:0040037',
 'meropenem allergy': 'DOID:0040038',
 'hexamethylene diisocyanate allergic asthma': 'DOID:0040040',
 'isocyanates allergic asthma': 'DOID:0040041',
 "diphenylmethane-4,4'-diisocyanate allergic asthma": 'DOID:0040042',
 'toluene meta-diisocyanate allergic asthma': 'DOID:0040043',
 'methyl isocyanate allergic asthma': 'DOID:0040044',
 'nickel allergic asthma': 'DOID:0040045',
 'nickel allergic contact dermatitis': 'DOID:0040046',
 'trimellitic anhydride allergic asthma': 'DOID:0040047',
 'phthalic anhydride allergic asthma': 'DOID:0040048',
 'maleic anhydride allergic asthma': 'DOID:0040049',
 'tetrachlorophthalic anhydride allergic asthma': 'DOID:0040050',
 'hexahydrophthalic anhydride allergic asthma': 'DOID:0040051',
 "diphenylmethane-4,4'-diisocyanate allergic contact dermatitis": 'DOID:0040052',
 'cobalt allergic contact dermatitis': 'DOID:0040053',
 'cobalt allergic asthma': 'DOID:0040054',
 'palladium allergic contact dermatitis': 'DOID:0040055',
 'chromium allergic contact dermatitis': 'DOID:0040056',
 'benzoic acid allergic contact dermatitis': 'DOID:0040057',
 '1,4-phenylenediamine allergic contact dermatitis': 'DOID:0040058',
 'potassium dichromate allergic contact dermatitis': 'DOID:0040059',
 'ketoprofen photoallergic dermatitis': 'DOID:0040060',
 'remazole black respiratory allergy': 'DOID:0040061',
 'chloramine T respiratory allergy': 'DOID:0040062',
 '4-vinylcyclohexene dioxide respiratory allergy': 'DOID:0040063',
 'carvone allergic contact dermatitis': 'DOID:0040064',
 'quinidine allergy': 'DOID:0040065',
 'melphalan allergy': 'DOID:0040066',
 'neomycin sulfate allergic contact dermatitis': 'DOID:0040067',
 '4-tert-butylphenol allergic contact dermatitis': 'DOID:0040068',
 '1-chloro-2,4-dinitrobenzene allergic contact dermatitis': 'DOID:0040069',
 'co-trimoxazole allergy': 'DOID:0040070',
 'sodium aurothiomalate allergy': 'DOID:0040071',
 'parthenolide allergic contact dermatitis': 'DOID:0040072',
 'disodium cromoglycate allergy': 'DOID:0040073',
 'formaldehyde allergic contact dermatitis': 'DOID:0040074',
 'benzo[d]isothiazol-3-one allergic contact dermatitis': 'DOID:0040075',
 'phthalyl group allergy': 'DOID:0040076',
 'alcuronium bromide allergy': 'DOID:0040077',
 'gallamine allergy': 'DOID:0040078',
 '2,4-dinitrophenyl allergic contact dermatitis': 'DOID:0040079',
 'patent blue V allergy': 'DOID:0040080',
 'acid anhydride respiratory allergy': 'DOID:0040081',
 'oxirane allergy': 'DOID:0040082',
 'Chlamydia pneumonia': 'DOID:0040083',
 'Streptococcus pneumonia': 'DOID:0040084',
 'bacterial sepsis': 'DOID:0040085',
 'Polyomavirus-associated nephropathy': 'DOID:0040086',
 'autoimmune peripheral neuropathy': 'DOID:0040087',
 'autoimmune uveitis': 'DOID:0040088',
 'autoimmune optic neuritis': 'DOID:0040089',
 'autoimmune gastritis': 'DOID:0040090',
 'autoimmune pancreatitis': 'DOID:0040091',
 'juvenile ankylosing spondylitis': 'DOID:0040092',
 'drug-induced lupus erythematosus': 'DOID:0040093',
 'autoimmune glomerulonephritis': 'DOID:0040094',
 'autoimmune cardiomyopathy': 'DOID:0040095',
 'autoimmune atherosclerosis': 'DOID:0040096',
 'autoimmune vasculitis': 'DOID:0040097',
 'pemphigus gestationis': 'DOID:0040098',
 'livedoid vasculitis': 'DOID:0040099',
 'Hirata disease': 'DOID:0040100',
 "N,N'-diphenylthiourea allergic contact dermatitis": 'DOID:0040101',
 "N,N'-diethylthiourea allergic contact dermatitis": 'DOID:0040102',
 'cefotiam allergy': 'DOID:0040103',
 'toluene 2,4-diisocyanate allergic asthma': 'DOID:0040104',
 'seminal vesicle acute gonorrhea': 'DOID:0050004',
 'chikungunya': 'DOID:0050012',
 'human granulocytic anaplasmosis': 'DOID:0050025',
 'human monocytic ehrlichiosis': 'DOID:0050026',
 'mineral metabolism disease': 'DOID:0050032',
 'African tick-bite fever': 'DOID:0050035',
 'Astrakhan spotted fever': 'DOID:0050041',
 'Indian tick typhus': 'DOID:0050042',
 'Israeli tick typhus': 'DOID:0050043',
 'Far Eastern spotted fever': 'DOID:0050046',
 'Flinders Island spotted fever': 'DOID:0050047',
 'Japanese spotted fever': 'DOID:0050050',
 'Rickettsia parkeri spotted fever': 'DOID:0050051',
 'Rocky Mountain spotted fever': 'DOID:0050052',
 'oropharyngeal anthrax': 'DOID:0050059',
 'erysipeloid': 'DOID:0050061',
 'adiaspiromycosis': 'DOID:0050072',
 'invasive aspergillosis': 'DOID:0050073',
 'Keshan disease': 'DOID:0050083',
 'tinea barbae': 'DOID:0050096',
 'ectothrix infectious disease': 'DOID:0050097',
 'endothrix infectious disease': 'DOID:0050105',
 'tinea imbricata': 'DOID:0050116',
 'disease by infectious agent': 'DOID:0050117',
 'La Crosse encephalitis': 'DOID:0050118',
 'hemophagocytic lymphohistiocytosis': 'DOID:0050120',
 'dengue shock syndrome': 'DOID:0050125',
 'sinusitis': 'DOID:0050127',
 'secretory diarrhea': 'DOID:0050129',
 'osmotic diarrhea': 'DOID:0050130',
 'motility-related diarrhea': 'DOID:0050131',
 'inflammatory diarrhea': 'DOID:0050132',
 'superficial mycosis': 'DOID:0050133',
 'cutaneous mycosis': 'DOID:0050134',
 'subcutaneous mycosis': 'DOID:0050135',
 'systemic mycosis': 'DOID:0050136',
 'podoconiosis': 'DOID:0050138',
 'acute diarrhea': 'DOID:0050140',
 'intestinal botulism': 'DOID:0050141',
 'asymptomatic dengue': 'DOID:0050143',
 'Kartagener syndrome': 'DOID:0050144',
 'adenoiditis': 'DOID:0050145',
 'otomycosis': 'DOID:0050147',
 'laryngotracheitis': 'DOID:0050148',
 'Pontiac fever': 'DOID:0050150',
 'aspiration pneumonia': 'DOID:0050152',
 'pulmonary aspergilloma': 'DOID:0050153',
 'sensory system disease': 'DOID:0050155',
 'idiopathic pulmonary fibrosis': 'DOID:0050156',
 'cryptogenic organizing pneumonia': 'DOID:0050157',
 'desquamative interstitial pneumonia': 'DOID:0050158',
 'lymphoid interstitial pneumonia': 'DOID:0050159',
 'inhalation anthrax': 'DOID:0050160',
 'lower respiratory tract disease': 'DOID:0050161',
 'tuberculous salpingitis': 'DOID:0050166',
 'autoimmune polyendocrine syndrome type 1': 'DOID:0050167',
 'autoimmune polyendocrine syndrome type 2': 'DOID:0050168',
 'cutaneous lupus erythematosus': 'DOID:0050169',
 'Kunjin encephalitis': 'DOID:0050174',
 'tick-borne encephalitis': 'DOID:0050175',
 'monogenic disease': 'DOID:0050177',
 'Powassan encephalitis': 'DOID:0050179',
 'erythema multiforme': 'DOID:0050185',
 'Nipah virus encephalitis': 'DOID:0050192',
 'Argentine hemorrhagic fever': 'DOID:0050194',
 'Bolivian hemorrhagic fever': 'DOID:0050195',
 'Venezuelan hemorrhagic fever': 'DOID:0050196',
 'Brazilian hemorrhagic fever': 'DOID:0050197',
 'Chapare hemorrhagic fever': 'DOID:0050198',
 'Whitewater Arroyo hemorrhagic fever': 'DOID:0050199',
 'Korean hemorrhagic fever': 'DOID:0050200',
 'nephropathia epidemica': 'DOID:0050201',
 'lujo hemorrhagic fever': 'DOID:0050202',
 'Epstein-Barr virus hepatitis': 'DOID:0050204',
 'swine influenza': 'DOID:0050211',
 'Lambert-Eaton myasthenic syndrome': 'DOID:0050214',
 'polycystic echinococcosis': 'DOID:0050218',
 'selective IgM deficiency disease': 'DOID:0050222',
 'primary amebic meningoencephalitis': 'DOID:0050242',
 'granulomatous amebic encephalitis': 'DOID:0050246',
 'philophthalmiasis': 'DOID:0050250',
 'coenurosis': 'DOID:0050251',
 'mesocestoidiasis': 'DOID:0050253',
 'acanthocephaliasis': 'DOID:0050254',
 'angiostrongyliasis': 'DOID:0050256',
 'baylisascariasis': 'DOID:0050259',
 'dioctophymiasis': 'DOID:0050260',
 'thelaziasis': 'DOID:0050261',
 'tungiasis': 'DOID:0050266',
 'ophthalmomyiasis': 'DOID:0050268',
 'Trichomonas vaginalis trichomoniasis': 'DOID:0050269',
 'Trichomonas tenax trichomoniasis': 'DOID:0050270',
 'basidiobolomycosis': 'DOID:0050278',
 'conidiobolomycosis': 'DOID:0050279',
 'penicilliosis': 'DOID:0050288',
 'fusariosis': 'DOID:0050289',
 'trichosporonosis': 'DOID:0050290',
 'parasitic Ichthyosporea infectious disease': 'DOID:0050291',
 'primary systemic mycosis': 'DOID:0050292',
 'aniseikonia': 'DOID:0050304',
 'Alkhurma hemorrhagic fever': 'DOID:0050308',
 'congenital hypothyroidism': 'DOID:0050328',
 'lacrimoauriculodentodigital syndrome 1': 'DOID:0050331',
 'enlarged vestibular aqueduct': 'DOID:0050332',
 'bradyopsia': 'DOID:0050335',
 'hypophosphatemia': 'DOID:0050336',
 'primary bacterial infectious disease': 'DOID:0050338',
 'commensal bacterial infectious disease': 'DOID:0050339',
 'opportunistic bacterial infectious disease': 'DOID:0050340',
 'foodborne botulism': 'DOID:0050352',
 'wound botulism': 'DOID:0050353',
 'infant botulism': 'DOID:0050354',
 'glandular tularemia': 'DOID:0050382',
 'typhoidal tularemia': 'DOID:0050383',
 'nonpapillary renal cell carcinoma': 'DOID:0050387',
 "Carrion's disease": 'DOID:0050398',
 'complement factor I deficiency': 'DOID:0050419',
 'familial adenomatous polyposis': 'DOID:0050424',
 'restless legs syndrome': 'DOID:0050425',
 'Stevens-Johnson syndrome': 'DOID:0050426',
 'xeroderma pigmentosum': 'DOID:0050427',
 'nonepidermolytic palmoplantar keratoderma': 'DOID:0050428',
 'Hailey-Hailey disease': 'DOID:0050429',
 'multiple endocrine neoplasia type 2A': 'DOID:0050430',
 'arrhythmogenic right ventricular cardiomyopathy': 'DOID:0050431',
 'Asperger syndrome': 'DOID:0050432',
 'fatal familial insomnia': 'DOID:0050433',
 'Andersen-Tawil syndrome': 'DOID:0050434',
 'mulibrey nanism': 'DOID:0050436',
 'Danon disease': 'DOID:0050437',
 'Frasier syndrome': 'DOID:0050438',
 'Usher syndrome': 'DOID:0050439',
 'familial partial lipodystrophy': 'DOID:0050440',
 'mucosulfatidosis': 'DOID:0050441',
 'infantile Refsum disease': 'DOID:0050444',
 'X-linked dominant hypophosphatemic rickets': 'DOID:0050445',
 'white sponge nevus': 'DOID:0050448',
 'pachyonychia congenita': 'DOID:0050449',
 'Gitelman syndrome': 'DOID:0050450',
 'Brugada syndrome': 'DOID:0050451',
 'mevalonic aciduria': 'DOID:0050452',
 'lissencephaly': 'DOID:0050453',
 'periventricular nodular heterotopia': 'DOID:0050454',
 'Buruli ulcer disease': 'DOID:0050456',
 'Sertoli cell-only syndrome': 'DOID:0050457',
 'juvenile myelomonocytic leukemia': 'DOID:0050458',
 'hyperphosphatemia': 'DOID:0050459',
 'Wolf-Hirschhorn syndrome': 'DOID:0050460',
 'aspartylglucosaminuria': 'DOID:0050461',
 'Antley-Bixler syndrome with disordered steroidogenesis': 'DOID:0050462',
 'campomelic dysplasia': 'DOID:0050463',
 'Farber lipogranulomatosis': 'DOID:0050464',
 'Muir-Torre syndrome': 'DOID:0050465',
 'Loeys-Dietz syndrome': 'DOID:0050466',
 'erythrokeratodermia variabilis': 'DOID:0050467',
 'yellow nail syndrome': 'DOID:0050468',
 'Costello syndrome': 'DOID:0050469',
 'Donohue syndrome': 'DOID:0050470',
 'Carney complex': 'DOID:0050471',
 'monilethrix': 'DOID:0050472',
 'Alstrom syndrome': 'DOID:0050473',
 'Netherton syndrome': 'DOID:0050474',
 'Weill-Marchesani syndrome': 'DOID:0050475',
 'Barth syndrome': 'DOID:0050476',
 'Liddle syndrome': 'DOID:0050477',
 'epidemic typhus': 'DOID:0050480',
 'endemic typhus': 'DOID:0050481',
 'aneruptive fever': 'DOID:0050484',
 'sennetsu fever': 'DOID:0050485',
 'exanthem': 'DOID:0050486',
 'bacterial exanthem': 'DOID:0050487',
 'early congenital syphilis': 'DOID:0050488',
 'multinodular goiter': 'DOID:0050489',
 'parenchymatous neurosyphilis': 'DOID:0050490',
 'meningovascular neurosyphilis': 'DOID:0050491',
 'exanthema subitum': 'DOID:0050495',
 'variola major': 'DOID:0050508',
 'spinal polio': 'DOID:0050513',
 'bulbospinal polio': 'DOID:0050514',
 'paralytic poliomyelitis': 'DOID:0050515',
 "O'nyong'nyong fever": 'DOID:0050516',
 'Barmah Forest virus disease': 'DOID:0050517',
 'Ross River fever': 'DOID:0050518',
 'Oropouche fever': 'DOID:0050521',
 'Balkan hemorrhagic fever': 'DOID:0050522',
 'adult T-cell leukemia/lymphoma': 'DOID:0050523',
 'maturity-onset diabetes of the young': 'DOID:0050524',
 'Gamstorp-Wohlfart syndrome': 'DOID:0050526',
 'nonphotosensitive trichothiodystrophy 4': 'DOID:0050528',
 'adult spinal muscular atrophy': 'DOID:0050529',
 'intermediate spinal muscular atrophy': 'DOID:0050530',
 'congenital stationary night blindness': 'DOID:0050534',
 'exudative vitreoretinopathy': 'DOID:0050535',
 'posterior polar cataract': 'DOID:0050537',
 'Charcot-Marie-Tooth disease type 1': 'DOID:0050538',
 'Charcot-Marie-Tooth disease type 2': 'DOID:0050539',
 'Charcot-Marie-Tooth disease type 3': 'DOID:0050540',
 'Charcot-Marie-Tooth disease type 4': 'DOID:0050541',
 'Charcot-Marie-Tooth disease type X': 'DOID:0050542',
 'Charcot-Marie-Tooth disease intermediate type': 'DOID:0050543',
 'hypermethioninemia': 'DOID:0050544',
 'visceral heterotaxy': 'DOID:0050545',
 'congenital adrenal insufficiency': 'DOID:0050546',
 'familial medullary thyroid carcinoma': 'DOID:0050547',
 'hereditary sensory neuropathy': 'DOID:0050548',
 'proteasome-associated autoinflammatory syndrome 1': 'DOID:0050553',
 'X-linked sideroblastic anemia with ataxia': 'DOID:0050554',
 'congenital muscular dystrophy': 'DOID:0050557',
 'Ullrich congenital muscular dystrophy': 'DOID:0050558',
 'Fukuyama congenital muscular dystrophy': 'DOID:0050559',
 'Walker-Warburg syndrome': 'DOID:0050560',
 'Lennox-Gastaut syndrome': 'DOID:0050561',
 'West syndrome': 'DOID:0050562',
 'nonsyndromic deafness': 'DOID:0050563',
 'autosomal dominant nonsyndromic deafness': 'DOID:0050564',
 'autosomal recessive nonsyndromic deafness': 'DOID:0050565',
 'X-linked nonsyndromic deafness': 'DOID:0050566',
 'orofacial cleft': 'DOID:0050567',
 'spondylocostal dysostosis': 'DOID:0050568',
 'Seckel syndrome': 'DOID:0050569',
 'congenital disorder of glycosylation type I': 'DOID:0050570',
 'congenital disorder of glycosylation type II': 'DOID:0050571',
 'cone-rod dystrophy': 'DOID:0050572',
 '2-hydroxyglutaric aciduria': 'DOID:0050573',
 'L-2-hydroxyglutaric aciduria': 'DOID:0050574',
 'D-2-hydroxyglutaric aciduria': 'DOID:0050575',
 'Senior-Loken syndrome': 'DOID:0050576',
 'cranioectodermal dysplasia': 'DOID:0050577',
 'occult macular dystrophy': 'DOID:0050578',
 'glycogen storage disease XV': 'DOID:0050579',
 'hereditary lymphedema': 'DOID:0050580',
 'brachydactyly': 'DOID:0050581',
 'gummatous syphilis': 'DOID:0050584',
 'congenital generalized lipodystrophy': 'DOID:0050585',
 'trichotillomania': 'DOID:0050587',
 'muscular dystrophy-dystroglycanopathy type B1': 'DOID:0050588',
 'inflammatory bowel disease': 'DOID:0050589',
 'severe congenital neutropenia': 'DOID:0050590',
 'tooth agenesis': 'DOID:0050591',
 'asphyxiating thoracic dystrophy': 'DOID:0050592',
 'primary congenital glaucoma': 'DOID:0050593',
 'glycogen storage disease IX': 'DOID:0050594',
 'taeniasis': 'DOID:0050596',
 'intestinal schistosomiasis': 'DOID:0050597',
 'extrapulmonary tuberculosis': 'DOID:0050598',
 'abdominal tuberculosis': 'DOID:0050599',
 'ABCD syndrome': 'DOID:0050600',
 'ADULT syndrome': 'DOID:0050601',
 'triple-A syndrome': 'DOID:0050602',
 'acheiropody': 'DOID:0050603',
 'acrocapitofemoral dysplasia': 'DOID:0050604',
 'acrodermatitis enteropathica': 'DOID:0050605',
 'acrokeratosis verruciformis': 'DOID:0050606',
 "Askin's tumor": 'DOID:0050608',
 'oral cavity carcinoma in situ': 'DOID:0050610',
 'pharynx carcinoma in situ': 'DOID:0050611',
 'gallbladder carcinoma in situ': 'DOID:0050612',
 'bile duct carcinoma in situ': 'DOID:0050613',
 'bronchus carcinoma in situ': 'DOID:0050614',
 'respiratory system cancer': 'DOID:0050615',
 'paranasal sinus cancer': 'DOID:0050619',
 'infiltrating renal pelvis transitional cell carcinoma': 'DOID:0050620',
 'respiratory system benign neoplasm': 'DOID:0050621',
 'reproductive organ benign neoplasm': 'DOID:0050622',
 'bladder benign neoplasm': 'DOID:0050623',
 'gastrointestinal system benign neoplasm': 'DOID:0050624',
 'biliary tract benign neoplasm': 'DOID:0050625',
 'gastrointestinal neuroendocrine tumor': 'DOID:0050626',
 'advanced sleep phase syndrome': 'DOID:0050628',
 'Aicardi-Goutieres syndrome': 'DOID:0050629',
 'Aland Island eye disease': 'DOID:0050630',
 'Allan-Herndon-Dudley syndrome': 'DOID:0050631',
 'oculocutaneous albinism': 'DOID:0050632',
 'ocular albinism 1': 'DOID:0050633',
 'alopecia universalis': 'DOID:0050634',
 'alternating hemiplegia of childhood': 'DOID:0050635',
 'familial visceral amyloidosis': 'DOID:0050636',
 'Finnish type amyloidosis': 'DOID:0050637',
 'transthyretin amyloidosis': 'DOID:0050638',
 'primary cutaneous amyloidosis': 'DOID:0050639',
 'anauxetic dysplasia 1': 'DOID:0050640',
 'Rh deficiency syndrome': 'DOID:0050641',
 'hypochromic microcytic anemia': 'DOID:0050642',
 'arterial calcification of infancy': 'DOID:0050644',
 'arterial tortuosity syndrome': 'DOID:0050645',
 'distal arthrogryposis': 'DOID:0050646',
 'Arts syndrome': 'DOID:0050647',
 'atelosteogenesis': 'DOID:0050648',
 'atransferrinemia': 'DOID:0050649',
 'familial atrial fibrillation': 'DOID:0050650',
 'atrioventricular septal defect': 'DOID:0050651',
 'Baller-Gerold syndrome': 'DOID:0050654',
 'Bamforth-Lazarus syndrome': 'DOID:0050655',
 'pseudo-TORCH syndrome 1': 'DOID:0050656',
 'Bannayan-Riley-Ruvalcaba syndrome': 'DOID:0050657',
 'Bart-Pumphrey syndrome': 'DOID:0050658',
 'biotin-responsive basal ganglia disease': 'DOID:0050659',
 'Beare-Stevenson cutis gyrata syndrome': 'DOID:0050660',
 'vitelliform macular dystrophy': 'DOID:0050661',
 'bestrophinopathy': 'DOID:0050662',
 'Bethlem myopathy': 'DOID:0050663',
 'Bietti crystalline corneoretinal dystrophy': 'DOID:0050664',
 'fetal alcohol syndrome': 'DOID:0050665',
 'partial fetal alcohol syndrome': 'DOID:0050666',
 'alcohol-related neurodevelopmental disorder': 'DOID:0050667',
 'alcohol-related birth defects': 'DOID:0050668',
 'spastic cerebral palsy': 'DOID:0050669',
 'ataxic cerebral palsy': 'DOID:0050670',
 'female breast cancer': 'DOID:0050671',
 'dyskinetic cerebral palsy': 'DOID:0050672',
 'mixed cerebral palsy': 'DOID:0050673',
 'congenital bile acid synthesis defect': 'DOID:0050674',
 'Birk-Barel syndrome': 'DOID:0050675',
 'Birt-Hogg-Dube syndrome': 'DOID:0050676',
 'Bjornstad syndrome': 'DOID:0050677',
 'Blau syndrome': 'DOID:0050678',
 'blue cone monochromacy': 'DOID:0050679',
 'Boomerang dysplasia': 'DOID:0050680',
 'Borjeson-Forssman-Lehmann syndrome': 'DOID:0050681',
 'Athabaskan brainstem dysgenesis syndrome': 'DOID:0050682',
 'Bothnia retinal dystrophy': 'DOID:0050683',
 'Bowen-Conradi syndrome': 'DOID:0050684',
 'small cell carcinoma': 'DOID:0050685',
 'organ system cancer': 'DOID:0050686',
 'cell type cancer': 'DOID:0050687',
 'anal canal cancer': 'DOID:0050688',
 'brachydactyly-syndactyly syndrome': 'DOID:0050689',
 'brachyolmia': 'DOID:0050690',
 'branchiooculofacial syndrome': 'DOID:0050691',
 'Brody myopathy': 'DOID:0050692',

# MESH DISEASE

In [8]:
MedGen_CUID_Source_ID = pd.read_csv(f'{BASE_PATH}databases_for_mapping/MESH/MeSH/MedGenIDMappings.txt',sep = '\t') #,index = None)
MedGen_CUID_Source_ID
MedGen_CUID_Source_ID = MedGen_CUID_Source_ID.drop_duplicates(subset=['source_id','source'], keep='first')
MedGen_CUID_Source_ID
MedGen_MeshID_name_dict = dict(zip(MedGen_CUID_Source_ID['source_id'], MedGen_CUID_Source_ID['pref_name']))
MedGen_MeshID_name_dict
MedGen_CUID_Source_ID

# MESH ID TO DOID
MedGen_CUID_HP_CONVERT = MedGen_CUID_Source_ID[
    MedGen_CUID_Source_ID['source_id'].fillna('').str.startswith('HP:')
]
MedGen_CUID_HP_CONVERT

MedGen_CUID_HP_CONVERT_dict = dict(zip(MedGen_CUID_HP_CONVERT['#CUI_or_CN_id'], MedGen_CUID_HP_CONVERT['source_id']))
MedGen_CUID_HP_CONVERT_dict



print(MedGen_CUID_Source_ID[MedGen_CUID_Source_ID['source_id'] == 'D001932'])
print(MedGen_CUID_Source_ID[MedGen_CUID_Source_ID['source_id'] == 'D003110'])
MedGen_CUID_Source_ID[MedGen_CUID_Source_ID['source_id'] == 'D007022']

MedGen_CUID_Source_ID_name_dict = dict(zip(MedGen_CUID_Source_ID['#CUI_or_CN_id'], MedGen_CUID_Source_ID['pref_name']))
MedGen_CUID_Source_ID_name_dict = {k: v.lower() if isinstance(v, str) else v for k, v in MedGen_CUID_Source_ID_name_dict.items()}
MedGen_CUID_Source_ID_name_dict

     #CUI_or_CN_id          pref_name source_id source  Unnamed: 4
3114      C0006118  Neoplasm of brain   D001932   MeSH         NaN
     #CUI_or_CN_id     pref_name source_id source  Unnamed: 4
3265      C0007102  Colon cancer   D003110   MeSH         NaN

{'C0000727': 'acute abdomen',
 'C0000731': 'abdominal distention',
 'C0000734': 'abdominal mass',
 'C0000735': 'neoplasm of abdomen',
 'C0000744': 'abetalipoproteinaemia',
 'C0000765': 'excessive weight gain',
 'C0000768': 'fetal anomaly',
 'C0000772': 'multiple congenital anomalies',
 'C0000774': 'gastrin secretion abnormality',
 'C0000778': 'abo blood group system',
 'C0000790': 'past pregnancy history of pregnancy with abortive outcome',
 'C0000804': 'illegal abortion',
 'C0000809': 'habitual spontaneous abortion',
 'C0000810': 'retained products after miscarriage',
 'C0000814': 'missed abortion',
 'C0000820': 'therapeutic abortion',
 'C0000822': 'miscarriage of tubal ectopic pregnancy',
 'C0000833': 'abscess',
 'C0000729': 'abdominal cramps',
 'C0000880': 'acanthamoeba keratitis',
 'C0000889': 'acanthosis nigricans',
 'C0001075': 'achlorhydria',
 'C0001079': 'achondrogenesis',
 'C0001080': 'achondroplasia',
 'C0001118': 'abnormality of acid-base homeostasis',
 'C0001122': 'acidosis',
 'C0001125': 'lactic acidosis',
 'C0001126': 'renal tubular acidosis',
 'C0000737': 'abdominal pain',
 'C0001139': 'acinetobacter infectious disease',
 'C0001144': 'acne vulgaris',
 'C0001145': 'acne keloid',
 'C0001163': 'vestibulocochlear nerve disorder',
 'C0001169': 'acquired coagulation factor deficiency',
 'C0001197': 'acrodermatitis',
 'C0001202': 'acrokeratosis',
 'C0001206': 'acromegaly',
 'C0001207': 'hypersomatotropic gigantism',
 'C0001231': 'ectopic acth secretion syndrome',
 'C0001255': 'actinomycetales infectious disease',
 'C0001261': 'actinomycotic infection',
 'C0000786': 'spontaneous abortion',
 'C0000821': 'threatened miscarriage',
 'C0001304': 'acute abscess',
 'C0000817': 'abortion, septic',
 'C0001306': 'acute alcoholic liver disease',
 'C0001314': 'acute disease',
 'C0000873': 'academic problem',
 'C0001327': 'acute laryngitis',
 'C0001338': 'herpetic acute necrotizing encephalitis',
 'C0001339': 'acute pancreatitis',
 'C0001342': 'acute pericementitis',
 'C0001360': 'acute thyroiditis',
 'C0001363': 'acute intestinal ischemia',
 'C0001364': 'acute necrosis of liver',
 'C0000887': 'acantholysis',
 'C0001396': 'adams-stokes syndrome',
 'C0001403': 'primary adrenocortical insufficiency',
 'C0001038': 'acetylation',
 'C0001420': 'papillary adenocarcinoma',
 'C0001429': 'warthin tumor',
 'C0000832': 'placental abruption',
 'C0001127': 'respiratory acidosis',
 'C0001193': 'acrocephalosyndactyly type i',
 'C0000848': 'posterior tibial pulse absent',
 'C0001430': 'adenoma',
 'C0001431': 'pituitary gland basophil adenoma',
 'C0001432': 'chromophobe adenoma',
 'C0000771': 'abnormalities, drug-induced',
 'C0001433': 'pituitary gland acidophil adenoma',
 'C0001442': 'adenosarcoma',
 'C0001486': 'adenoviridae infectious disease',
 'C0001519': 'holmes-adie syndrome',
 'C0001529': 'lipomatosis dolorosa',
 'C0001541': 'adjustment disorder with mixed disturbance of emotions and conduct',
 'C0001542': 'adjustment disorder with mixed emotional features',
 'C0001544': 'adjustment disorder with withdrawal',
 'C0001546': 'adjustment disorder',
 'C0001576': 'adnexal diseases',
 'C0001614': 'adrenal cortex disorder',
 'C0001618': 'adrenal cortex neoplasm',
 'C0001622': 'hypercortisolism',
 'C0001623': 'adrenal insufficiency',
 'C0001624': 'neoplasm of the adrenal gland',
 'C0001175': 'aids',
 'C0001627': 'congenital adrenal hyperplasia',
 'C0001247': 'actinobacillosis',
 'C0001630': 'adrenal rest tumor',
 'C0001249': 'actinobacillus infection',
 'C0001676': 'adult antisocial behavior',
 'C0001726': 'affective symptoms',
 'C0001264': 'cervicofacial actinomycosis',
 'C0001727': 'afferent loop syndrome',
 'C0001305': 'acute adenoviral follicular conjunctivitis',
 'C0001308': 'acute and subacute liver necrosis',
 'C0001733': 'afibrinogenemia',
 'C0001768': 'agammaglobulinemia',
 'C0001311': 'acute bronchiolitis',
 'C0001787': 'age-related osteoporosis',
 'C0001801': 'agglutination',
 'C0001811': 'aging',
 'C0001815': 'primary myelofibrosis',
 'C0001816': 'agnosia',
 'C0001818': 'agoraphobia',
 'C0001349': 'acute phase response',
 'C0001263': 'abdominal actinomycosis',
 'C0001361': 'acute tonsillitis',
 'C0001819': 'agoraphobia without history of panic disorder',
 'C0001824': 'agranulocytosis',
 'C0001857': 'aids related complex',
 'C0001418': 'adenocarcinoma',
 'C0001422': 'adenofibroma',
 'C0001860': 'ainhum',
 'C0001882': 'air sickness',
 'C0001427': 'adenoiditis',
 'C0001883': 'airway obstruction',
 'C0001889': 'akinetic mutism',
 'C0001916': 'albinism',
 'C0001922': 'abnormal presence of albumin',
 'C0001511': 'adhesion',
 'C0001940': 'alcohol amnestic disorder',
 'C0001969': 'alcohol intoxication',
 'C0001973': 'alcohol dependence',
 'C0002016': 'aleutian disease',
 'C0002020': 'alexithymia',
 'C0002063': 'alkalosis',
 'C0001539': 'adjustment disorder with depressed mood',
 'C0002064': 'respiratory alkalosis',
 'C0002066': 'alkaptonuria',
 'C0002103': 'atopic rhinitis',
 'C0002170': 'alopecia',
 'C0001577': 'adnexitis',
 'C0002173': 'alopecia mucinosa',
 'C0002176': 'endocrine alopecia',
 'C0002178': 'nutritional alopecia',
 'C0002180': 'postpartum alopecia',
 'C0002181': 'syphilitic alopecia',
 'C0002312': 'alpha thalassemia',
 'C0002351': 'altitude sickness',
 'C0002382': 'alveolar bone loss',
 'C0002390': 'hypersensitivity pneumonitis',
 'C0002395': 'alzheimer disease',
 'C0002418': 'amblyopia',
 'C0001707': 'aerophagia',
 'C0002419': 'tobacco amblyopia',
 'C0001723': 'affective psychosis',
 'C0002438': 'amebiasis',
 'C0002447': 'amelia',
 'C0002448': 'ameloblastoma',
 'C0001807': 'aggressive behavior',
 'C0002453': 'amenorrhea',
 'C0002511': 'activation of amino acids',
 'C0002514': 'inborn error of amino acid metabolism',
 'C0002534': 'renal aminoaciduria',
 'C0002622': 'amnesia',
 'C0000823': 'abortion, veterinary',
 'C0002623': 'post-traumatic amnesia',
 'C0002624': 'retrograde amnesia',
 'C0002625': 'amnestic disorder',
 'C0002631': 'amnionitis',
 'C0002636': 'constriction ring syndrome',
 'C0002726': 'amyloidosis',
 'C0002735': 'amyotonia congenita',
 'C0002768': 'congenital indifference to pain',
 'C0002792': 'anaphylaxis',
 'C0002831': 'ancylostomiasis',
 'C0001825': 'agraphia',
 'C0002871': 'anemia',
 'C0002873': 'anemia due to chronic disorder',
 'C0002874': 'aplastic anemia',
 'C0001849': 'dementia associated with aids',
 'C0002875': 'beta-thalassemia major',
 'C0002876': 'congenital dyserythropoietic anemia',
 'C0001906': 'variola minor infection',
 'C0002878': 'hemolytic anemia',
 'C0002880': 'autoimmune hemolytic anemia',
 'C0002882': 'congenital nonspherocytic hemolytic anemia',
 'C0001925': 'albuminuria',
 'C0002892': 'pernicious anemia',
 'C0002894': 'myelodysplastic syndrome with excess blasts',
 'C0001957': 'alcohol withdrawal delirium',
 'C0002895': 'hb ss disease',
 'C0002896': 'sideroblastic anemia',
 'C0002018': 'alexia',
 'C0002902': 'anencephaly',
 'C0002938': 'aneuploidy',
 'C0002940': 'vascular dilatation',
 'C0002949': 'arterial dissection',
 'C0002959': 'vascular ectasia',
 'C0002963': 'prinzmetal angina',
 'C0001543': 'adjustment disorder with physical complaints',
 'C0002965': 'intermediate coronary syndrome',
 'C0002044': 'algor mortis',
 'C0002983': 'angioid streaks of choroid',
 'C0001621': 'disorder of adrenal gland',
 'C0002098': 'hypersensitivity granuloma',
 'C0002985': 'angiokeratoma',
 'C0002986': 'fabry disease',
 'C0002991': 'dermatofibroma',
 'C0002179': 'hypotrichosis following infectious disease',
 'C0002182': 'traumatic alopecia',
 'C0002992': 'angiomatosis',
 'C0003028': 'anhidrosis',
 'C0003076': 'congenital aniridia',
 'C0003078': 'aniseikonia',
 'C0003079': 'anisocoria',
 'C0003081': 'anisometropia',
 'C0003090': 'ankylosis',
 'C0003102': 'annular grooves',
 'C0003113': 'anomic aphasia',
 'C0003119': 'anophthalmia',
 'C0003123': 'anorexia',
 'C0003128': 'anovulation',
 'C0003130': 'oxygen supply absent',
 'C0003132': 'anoxic encephalopathy',
 'C0003152': 'anterior compartment of tibia syndrome',
 'C0001714': 'polymyxin b sulfate',
 'C0003164': 'anthracosilicosis',
 'C0003165': 'anthracosis',
 'C0003177': 'cutaneous anthrax',
 'C0003255': 'antibody affinity',
 'C0003314': 'humoral immune reaction',
 'C0001748': 'african horse sickness',
 'C0003319': 'antigen variation',
 'C0003460': 'anuria',
 'C0003462': 'anus disorder',
 'C0003463': 'anus neoplasm',
 'C0002416': 'ambidextrous',
 'C0003466': 'imperforate anus',
 'C0003467': 'anxiety',
 'C0003469': 'anxiety disorder',
 'C0003471': 'anxiety disorder of childhood or adolescence',
 'C0000846': 'agenesis',
 'C0003490': 'aortic arch syndrome',
 'C0003492': 'coarctation of aorta',
 'C0003493': 'aortic disorder',
 'C0003496': 'aortic rupture',
 'C0003499': 'supravalvar aortic stenosis',
 'C0003504': 'aortic regurgitation',
 'C0003505': 'aortic valve prolapse',
 'C0003507': 'aortic valve stenosis',
 'C0003509': 'aortitis',
 'C0003511': 'syphilitic aortitis',
 'C0003516': 'aortopulmonary window',
 'C0003546': 'aphasia, acquired',
 'C0003550': 'motor aphasia',
 'C0003564': 'loss of voice',
 'C0003578': 'apnea',
 'C0003635': 'apraxia',
 'C0001890': 'akinetic petit mal',
 'C0003650': 'apudoma',
 'C0003708': 'arachnoiditis',
 'C0003742': 'arcus senilis',
 'C0001956': 'alcohol use disorders',
 'C0003803': 'chiari malformation',
 'C0003811': 'cardiac arrhythmia',
 'C0003843': 'arterio-arterial fistula',
 'C0003848': 'arteriolitis',
 'C0003850': 'arteriosclerosis disorder',
 'C0003855': 'arteriovenous fistula',
 'C0003860': 'arteritis',
 'C0003861': 'pulmonary arteritis',
 'C0003862': 'arthralgia',
 'C0003864': 'arthritis',
 'C0003868': 'gouty arthropathy',
 'C0003872': 'psoriatic arthritis',
 'C0003873': 'rheumatoid arthritis',
 'C0002145': 'allosteric regulation',
 'C0003892': 'neuropathic arthropathy',
 'C0003907': 'arthus reaction',
 'C0003948': 'asbestos exposure',
 'C0002171': 'alopecia areata',
 'C0003950': 'ascariasis',
 'C0003969': 'decreased circulating vitamin c concentration',
 'C0004030': 'aspergillosis',
 'C0004044': 'suffocating',
 'C0004045': 'neonatal asphyxia',
 'C0004090': 'astasia-abasia',
 'C0004093': 'asthenia',
 'C0004095': 'asthenopia',
 'C0004096': 'asthma',
 'C0004099': 'exercise-induced asthma',
 'C0004106': 'astigmatism',
 'C0002452': 'amelogenesis imperfecta',
 'C0002441': 'amebiasis of skin',
 'C0002445': 'ameboma',
 'C0004134': 'dyssynergia',
 'C0004135': 'ataxia-telangiectasia syndrome',
 'C0002736': 'amyotrophic lateral sclerosis',
 'C0004138': 'hereditary ataxia',
 'C0004144': 'atelectasis',
 'C0004153': 'atherosclerosis',
 'C0002793': 'anaplastic lesion',
 'C0002796': 'anaplasmataceae infections',
 'C0004238': 'atrial fibrillation',
 'C0002797': 'anaplasmosis',
 'C0004239': 'atrial flutter',
 'C0004269': 'child attention deficit disorder',
 'C0004277': 'dental attrition',
 'C0004310': 'auditory processing disorder',
 'C0004317': 'aural headache',
 'C0004331': 'atrioventricular dissociation',
 'C0004352': 'autism',
 'C0004364': 'autoimmune disease',
 'C0004377': 'automatism',
 'C0004443': 'avoidant disorder of childhood or adolescence',
 'C0004444': 'avoidant personality disorder',
 'C0004509': 'azoospermia',
 'C0004565': 'b16 malignant melanoma',
 'C0002881': 'familial hemolytic anemia',
 'C0002884': 'hypochromic anemia',
 'C0002886': 'macrocytic anemia',
 'C0002888': 'megaloblastic anemia',
 'C0002757': 'anal gland neoplasm',
 'C0002893': 'refractory anemia',
 'C0004576': 'babesiosis',
 'C0004599': 'bacitracin',
 'C0004610': 'bacterial infectious disease with sepsis',
 'C0004616': 'bacterial aneurysm',
 'C0004623': 'bacterial infectious disease',
 'C0004626': 'bacterial pneumonia',
 'C0004659': 'bacteriuria',
 'C0004669': 'bacteroides infectious disease',
 'C0004681': 'bagassosis',
 'C0004690': 'balanitis',
 'C0004691': 'balanoposthitis',
 'C0002899': 'anemia due to disorder of glutathione metabolism',
 'C0004692': 'balantidiasis',
 'C0004698': 'balkan nephropathy',
 'C0004712': 'balo concentric sclerosis',
 'C0004763': 'barrett esophagus',
 'C0004771': 'bartonellosis',
 'C0002962': 'angina pectoris',
 'C0004773': 'bartonellaceae infectious disease',
 'C0004775': 'bartter syndrome',
 'C0004779': 'gorlin syndrome',
 'C0004823': 'basophilic hyperplasia',
 'C0004903': 'beckwith-wiedemann syndrome',
 'C0004943': 'behcet disease',
 'C0004945': 'bejel',
 'C0002982': 'angioid streaks',
 'C0004991': 'benign colon neoplasm',
 'C0005122': 'beriberi',
 'C0005129': 'bernard soulier syndrome',
 'C0005136': 'berry aneurysm',
 'C0002989': 'skin epithelioid hemangioma',
 'C0005146': 'infection by besnoitia',
 'C0002994': 'angioedema',
 'C0005395': 'bile duct disorder',
 'C0005398': 'extrahepatic cholestasis',
 'C0005403': 'bile reflux',
 'C0005409': 'schistosomal pigment deposition',
 'C0005411': 'biliary atresia',
 'C0003107': 'pruritis of skin of anogenital region',
 'C0005416': 'biliary dyskinesia',
 'C0005417': 'fistula of bile duct',
 'C0003125': 'anorexia nervosa',
 'C0005424': 'disorder of biliary tract',
 'C0005426': 'biliary tract neoplasm',
 'C0003126': 'anosmia',
 'C0005458': 'competitive binding',
 'C0005461': 'binocular vision disease',
 'C0005586': 'bipolar affective disorder',
 'C0005591': 'bird diseases',
 'C0005592': 'bird-fanciers lung',
 'C0005603': 'birth history',
 'C0005607': 'place in family order',
 'C0005683': 'bladder stones',
 'C0005689': 'bladder exstrophy',
 'C0005690': 'bladder fistula',
 'C0005695': 'bladder neoplasm',
 'C0005697': 'neurogenic bladder',
 'C0005699': 'blast phase chronic myelogenous leukemia, bcr-abl1 positive',
 'C0005716': 'blastomycosis',
 'C0005721': 'cutaneous paracoccioidomycosis',
 'C0005724': 'visceral paracoccidioidomycosis',
 'C0005741': 'blepharitis',
 'C0005742': 'blepharochalasis',
 'C0001309': 'angelucci syndrome',
 'C0005743': 'blepharoconjunctivitis',
 'C0002879': 'acquired hemolytic anemia',
 'C0001344': 'acute pharyngitis',
 'C0002890': 'myelophthisic anemia',
 'C0002891': 'neonatal anemia',
 'C0005744': 'blepharophimosis',
 'C0005745': 'ptosis',
 'C0003175': 'anthrax infection',
 'C0001416': 'adenitides',
 'C0005747': 'blepharospasm',
 'C0002945': 'aneurysm of other specified arteries',
 'C0005750': 'blind loop syndrome',
 'C0001487': 'adenovirus infections, human',
 'C0005758': 'blister',
 'C0005779': 'abnormality of the coagulation cascade',
 'C0005806': 'blood group incompatibility',
 'C0005818': 'inherited bleeding disorder, platelet-type',
 'C0001540': 'adjustment disorder with disturbance of conduct',
 'C0005826': 'abnormal blood pressure',
 'C0001548': 'brief depressive adjustment reaction',
 'C0005859': 'bloom syndrome',
 'C0003257': 'antibody deficiency syndrome',
 'C0005887': 'body dysmorphic disorder',
 'C0003431': 'antisocial personality disorder',
 'C0005904': 'body temperature change',
 'C0005911': 'weight change',
 'C0005937': 'bone cyst',
 'C0005940': 'disorder of bone',
 'C0005941': 'bone development disease',
 'C0005943': 'bone diseases, infectious',
 'C0005944': 'metabolic bone disorder',
 'C0005956': 'bone marrow disorder',
 'C0005967': 'bone neoplasm',
 'C0005974': 'bone resorption disease',
 'C0003476': 'castration anxiety complex',
 'C0006009': 'intellectual disability, borderline',
 'C0006015': 'bordetellosis',
 'C0003477': 'separation anxiety disorder',
 'C0006035': 'borrelia infectious disease',
 'C0006057': 'botulism',
 'C0006060': 'boutonneuse fever',
 'C0001752': 'african swine fever',
 'C0006091': 'brachial plexus neuropathy from injury',
 'C0006109': 'chronic brain syndrome',
 'C0003259': 'antibody diversity',
 'C0006110': 'brain death',
 'C0003264': 'antibody specificity',
 'C0006111': 'brain disorder',
 'C0006118': 'neoplasm of brain',
 'C0006123': 'branch retinal artery occlusion',
 'C0006131': 'branchial cyst',
 'C0006145': 'breast disorder',
 'C0003486': 'aortic aneurysm',
 'C0006152': 'swelling of breast',
 'C0006160': 'brenner tumor',
 'C0006181': 'brill-zinsser disease',
 'C0006261': 'abnormality of the bronchi',
 'C0006262': 'bronchial fistula',
 'C0006264': 'bronchial neoplasm',
 'C0006266': 'bronchospasm',
 'C0006271': 'bronchiolitis',
 'C0006277': 'bronchitis',
 'C0006281': 'bronchogenic cyst',
 'C0006285': 'bronchopneumonia',
 'C0001828': 'agricultural workers diseases',
 'C0006287': 'bronchopulmonary dysplasia of newborn',
 'C0006309': 'brucellosis',
 'C0006325': 'bruxism',
 'C0006384': 'bundle branch block',
 'C0006396': 'disease caused by bunyaviridae',
 'C0006413': 'burkitt lymphoma',
 'C0006430': 'burning mouth syndrome',
 'C0006444': 'bursitis',
 'C0006542': 'byssinosis',
 'C0006625': 'cachexia',
 'C0006646': 'organic mental disorder caused by caffeine',
 'C0006663': 'calcinosis',
 'C0006664': 'calcinosis cutis',
 'C0006818': 'campylobacteriosis',
 'C0006826': 'malignant neoplastic disease',
 'C0006840': 'candidiasis',
 'C0006845': 'chronic mucocutaneous candidiasis',
 'C0006846': 'cutaneous candidiasis',
 'C0006849': 'oral candidiasis',
 'C0006868': 'cannabis abuse',
 'C0006870': 'cannabis dependence',
 'C0006897': 'capillariasis',
 'C0006899': 'capillaria philippinensis infection',
 'C0006902': 'capillaritis',
 'C0006905': 'capillary fragility',
 'C0007001': 'inborn carbohydrate metabolic disorder',
 'C0003510': 'aortitis syndrome',
 'C0007078': 'carbuncle',
 'C0007095': 'carcinoid tumor',
 'C0007097': 'carcinoma',
 'C0007099': 'in situ carcinoma',
 'C0003534': 'aphakia',
 'C0007102': 'colon cancer',
 'C0003537': 'aphasia',
 'C0007103': 'endometrial cancer',
 'C0007104': 'female breast carcinoma',
 'C0003614': 'appendiceal neoplasm',
 'C0007112': 'prostate adenocarcinoma',
 'C0007113': 'rectal carcinoma',
 'C0007117': 'basal cell carcinoma',
 'C0003615': 'appendicitis',
 'C0003706': 'arachnodactyly',
 'C0003721': 'arbovirus hemorrhagic fever',
 'C0003723': 'arbovirus infection',
 'C0003810': 'ovarian sertoli-leydig cell tumor',
 'C0002682': 'ampicillin resistance',
 'C0003813': 'sinus arrhythmia',
 'C0003851': 'arteriosclerosis obliterans',
 'C0003857': 'arteriovenous malformation',
 'C0003869': 'infective arthritis',
 'C0003886': 'arthrogryposis',
 'C0003756': 'disease caused by arenavirus',
 'C0003910': 'articulation disorder',
 'C0003949': 'asbestosis',
 'C0007118': 'basosquamous carcinoma',
 'C0003834': 'arterial insufficiency',
 'C0007120': 'minimally invasive lung adenocarcinoma',
 'C0007121': 'bronchogenic carcinoma',
 'C0007125': 'ehrlich tumor carcinoma',
 'C0007128': 'krebs 2 carcinoma',
 'C0007129': 'cutaneous neuroendocrine carcinoma',
 'C0007130': 'mucinous adenocarcinoma',
 'C0007131': 'non-small cell lung carcinoma',
 'C0007133': 'papillary carcinoma',
 'C0007135': 'scirrhous adenocarcinoma',
 'C0007137': 'squamous cell carcinoma',
 'C0007138': 'transitional cell carcinoma',
 'C0007140': 'carcinosarcoma',
 'C0007166': 'decreased cardiac output',
 'C0007177': 'cardiac tamponade',
 'C0007192': 'alcoholic cardiomyopathy',
 'C0007193': 'primary dilated cardiomyopathy',
 'C0007196': 'restrictive cardiomyopathy',
 'C0007222': 'disorder of cardiovascular system',
 'C0007274': 'carotid artery thrombosis',
 'C0007279': 'carotid body paraganglioma',
 'C0007280': 'carotid bruit',
 'C0007283': 'carotene pigmentation of skin',
 'C0003952': 'ascaridiasis',
 'C0007286': 'carpal tunnel syndrome',
 'C0003962': 'ascites',
 'C0007294': 'genetic disorder carrier',
 'C0007297': 'car sickness',
 'C0007361': 'cat scratch disease',
 'C0007370': 'catalepsy',
 'C0004032': 'disseminated aspergillosis',
 'C0007384': 'cataplexy',
 'C0007527': 'cecal disorder',
 'C0004058': 'allergy to aspirin',
 'C0007570': 'celiac disease',
 'C0007642': 'cellulitis',
 'C0003874': 'acute suppurative arthritis caused by bacteria',
 'C0007657': 'cementitis',
 'C0007659': 'cementoma',
 'C0003875': 'arthritis due to viral infection',
 'C0007682': 'disorder of the central nervous system',
 'C0007684': 'infectious disease of central nervous system',
 'C0007688': 'central retinal artery occlusion',
 'C0007722': 'cephalohematoma',
 'C0007758': 'cerebellar ataxia',
 'C0007760': 'cerebellar disorder',
 'C0007771': 'intracranial arteriosclerosis',

## Mesh 2

In [9]:
import pandas as pd
MESH =  pd.read_csv(f'{BASE_PATH}databases_for_mapping/MESH/MESH_Combined.csv') #,index = None))
MESH_dict = dict(zip(MESH['ID'],MESH['Name']))
MESH_dict
MESH
MESH['Pubchem_ID'] = MESH['Name'].map(Pubchem_Syn_fil_dict)
MESH["Pubchem_ID"] = MESH["Pubchem_ID"].astype(str).str.replace(r'\.0$', '', regex=True)
MESH

MESH = MESH[MESH['Pubchem_ID']!= 'nan']
MESH

Mesh_PUBCHEM_dict = dict(zip(MESH['ID'], MESH['Pubchem_ID']))
Mesh_PUBCHEM_dict

{'D000001': '16211531',
 'D000002': '5392',
 'D000053': '9576412',
 'D000072': '6477',
 'D000080': '7765',
 'D000085': '31229',
 'D000112': '5284512',
 'D000113': '10350481',
 'D000120': '4342',
 'D000166': '9215',
 'D000167': '443101',
 'D000175': '345512',
 'D000198': '15541',
 'D000242': '6076',
 'D000323': '5898',
 'D000362': '71571511',
 'D000439': '6276',
 'D000440': '263',
 'D000441': '8103',
 'D000443': '21158560',
 'D000475': '32932',
 'D000487': '11442',
 'D000496': '5781',
 'D000517': '7290',
 'D000546': '3084077',
 'D000548': '13506',
 'D000561': '115163',
 'D000585': '7019',
 'D000607': '10901',
 'D000629': '1647',
 'D000631': '10439',
 'D000640': '1639',
 'D000676': '3698',
 'D000691': '641266',
 'D000701': '126961754',
 'D000872': '145858',
 'D000926': '16133935',
 'D000968': '16218979',
 'D000976': '124527305',
 'D000996': '8980',
 'D001030': '171378780',
 'D001081': '131750176',
 'D001101': '5283064',
 'D001138': '66067',
 'D001148': '10749',
 'D001152': '5359596',
 'D001168': '25213',
 'D001204': '168009863',
 'D001279': '47319',
 'D001373': '10023199',
 'D001374': '9444',
 'D001375': '135403646',
 'D001376': '15443',
 'D001380': '5901',
 'D001386': '33558',
 'D001387': '2268',
 'D001393': '699591',
 'D001429': '11953947',
 'D001455': '6433554',
 'D001514': '133082063',
 'D001541': '89617',
 'D001556': '727',
 'D001572': '253613',
 'D001576': '17170',
 'D001583': '9228',
 'D001594': '14196',
 'D001627': '2368',
 'D001639': '769',
 'D001645': '5939',
 'D001646': '4366058',
 'D001737': '7913',
 'D001880': '6331',
 'D001893': '153974',
 'D001958': '11151',
 'D001959': '84979',
 'D001973': '6035',
 'D002026': '2468',
 'D002027': '10257',
 'D002035': '36131',
 'D002085': '19665',
 'D002093': '9820',
 'D002096': '16157840',
 'D002108': '16129675',
 'D002112': '6441383',
 'D002116': '16220016',
 'D002147': '25244460',
 'D002159': '33309',
 'D002182': '446220',
 'D002186': '9852188',
 'D002210': '119389',
 'D002211': '1548943',
 'D002219': '276',
 'D002225': '2569',
 'D002231': '31072',
 'D002232': '5709754',
 'D002244': '5462310',
 'D002254': '19660',
 'D002271': '9564',
 'D002323': '33672',
 'D002329': '25113282',
 'D002331': '288',
 'D002336': '439224',
 'D002355': '32170',
 'D002360': '443831',
 'D002480': '440950',
 'D002505': '91562',
 'D002510': '168010178',
 'D002599': '637760',
 'D002703': '8371',
 'D002704': '104770',
 'D002706': '11954021',
 'D002709': '5377791',
 'D002712': '312',
 'D002714': '6244',
 'D002716': '13837',
 'D002719': '10783',
 'D002721': '10757',
 'D002724': '5977',
 'D002731': '11136',
 'D002733': '6028',
 'D002742': '22544',
 'D002750': '6301',
 'D002865': '131750203',
 'D002866': '12604',
 'D002922': '5311333',
 'D002949': '12012',
 'D002957': '18818',
 'D003007': '18087',
 'D003039': '16132280',
 'D003041': '446220',
 'D003077': '6432481',
 'D003092': '5359367',
 'D003189': '104735',
 'D003281': '73346591',
 'D003311': '131750187',
 'D003374': '54678486',
 'D003471': '9723',
 'D003485': '105034',
 'D003486': '5975',
 'D003489': '20243',
 'D003494': '7533',
 'D003505': '320760',
 'D003511': '7966',
 'D003512': '26534',
 'D003517': '9253',
 'D003529': '46494862',
 'D003539': '54601828',
 'D003544': '72886',
 'D003575': '44144406',
 'D003632': '6294',
 'D003633': '3035',
 'D003634': '3036',
 'D003642': '7902',
 'D003647': '2966',
 'D003671': '4284',
 'D003687': '5881',
 'D003703': '220401',
 'D003708': '2997',
 'D003847': '108223',
 'D003894': '5311065',
 'D003910': '167312536',
 'D003912': '62698',
 'D003918': '8730',
 'D003957': '37384',
 'D003961': '15942827',
 'D003962': '8411',
 'D003963': '3007857',
 'D003983': '5820',
 'D004002': '25419',
 'D004003': '3037',
 'D004004': '5894',
 'D004023': '123886',
 'D004050': '8987',
 'D004052': '5921',
 'D004070': '441207',
 'D004072': '171121767',
 'D004073': '4369270',
 'D004076': '15478',
 'D004090': '5359421',
 'D004092': '8956',
 'D004095': '407038',
 'D004098': '670',
 'D004105': '9305',
 'D004109': '3074',
 'D004113': '2724354',
 'D004118': '8421',
 'D004124': '6053',
 'D004125': '3566770',
 'D004126': '6228',
 'D004127': '61870',
 'D004128': '6124',
 'D004136': '156614059',
 'D004137': '6',
 'D004139': '6264',
 'D004159': '11487',
 'D004160': '8789',
 'D004174': '443408',
 'D004179': '72201066',
 'D004226': '439352',
 'D004229': '446094',
 'D004308': '5282426',
 'D004328': '91739',
 'D004391': '6468',
 'D004397': '13676',
 'D004399': '16129685',
 'D004441': '5459840',
 'D004448': '138402870',
 'D004731': '53481793',
 'D004745': '461776',
 'D004801': '11048',
 'D004809': '9294',
 'D004845': '10204',
 'D004849': '16421',
 'D004872': '5280793',
 'D004873': '6857537',
 'D004928': '138454862',
 'D004929': '5281417',
 'D004967': '23676225',
 'D004985': '162262',
 'D004996': '3624',
 'D005001': '25674',
 'D005009': '16058',
 'D005031': '2723650',
 'D005036': '5359271',
 'D005038': '12967',
 'D005039': '3306',
 'D005041': '37497',
 'D005045': '667484',
 'D005048': '73951893',
 'D005200': '32486',
 'D005344': '25078015',
 'D005345': '16132131',
 'D005363': '6199',
 'D005372': '168313253',
 'D005405': '101981638',
 'D005406': '33295',
 'D005419': '11349',
 'D005450': '37927',
 'D005452': '3259',
 'D005459': '28179',
 'D005464': '10008',
 'D005478': '15209',
 'D005481': '9528',
 'D005484': '3396',
 'D005562': '9567750',
 'D005573': '135480691',
 'D005576': '47936',
 'D005589': '100039',
 'D005601': '8378',
 'D005610': '3050747',
 'D005650': '5460307',
 'D005662': '7362',
 'D005666': '3002119',
 'D005677': '9963963',
 'D005679': '86583360',
 'D005702': '9651',
 'D005711': '1234',
 'D005755': '16132262',
 'D005839': '3467',
 'D005867': '27812',
 'D005873': '6239',
 'D005875': '102004933',
 'D005942': '10692',
 'D005960': '64689',
 'D005976': '3485',
 'D006017': '44176376',
 'D006020': '56928060',
 'D006023': '439212',
 'D006027': '637579',
 'D006033': '11163',
 'D006035': '21852',
 'D006108': '5462310',
 'D006144': '15078',
 'D006178': '3373',
 'D006225': '702',
 'D006262': '31239',
 'D006415': '11103',
 'D006492': '12679',
 'D006531': '23831',
 'D006536': '8900',
 'D006583': '24769',
 'D006586': '7892',
 'D006591': '3608',
 'D006592': '5777',
 'D006601': '24749',
 'D006629': '72941487',
 'D006657': '168009929',
 'D006688': '3496',
 'D006690': '2392',
 'D006821': '91820602',
 'D006827': '10006',
 'D006829': '3767',
 'D006834': '9321',
 'D006859': '783',
 'D006881': '5896',
 'D006907': '91451',
 'D006910': '569605',
 'D006912': '23696930',
 'D006917': '9061',
 'D006920': '702',
 'D006923': '5280567',
 'D007094': '443040',
 'D007095': '21389',
 'D007191': '9221',
 'D007194': '150905',
 'D007211': '139191468',
 'D007454': '30165',
 'D007457': '167196',
 'D007470': '439744',
 'D007471': '17477',
 'D007476': '44297815',
 'D007488': '21722',
 'D007496': '66373',
 'D007498': '3776',
 'D007510': '7054',
 'D007529': '72304',
 'D007531': '5936',
 'D007532': '6306',
 'D007541': '24405',
 'D007555': '9254',
 'D007627': '3828',
 'D007650': '3822',
 'D007799': '44661266',
 'D007851': '8193',
 'D007856': '56842199',
 'D007933': '53394899',
 'D008128': '51605',
 'D008149': '1614',
 'D008155': '118984381',
 'D008162': '110937',
 'D008194': '54707177',
 'D008241': '432092',
 'D008244': '5311264',
 'D008248': '167312533',
 'D008299': '7923',
 'D008315': '10964',
 'D008351': '25147451',
 'D008357': '3033867',
 'D008470': '5288826',
 'D008511': '14184',
 'D008543': '6325610',
 'D008550': '896',
 'D008555': '16133648',
 'D008618': '8271',
 'D008621': '41049',
 'D008623': '1567',
 'D008634': '23690449',
 'D008655': '15020',
 'D008676': '21100',
 'D008693': '3003791',
 'D008695': '229021',
 'D008720': '667492',
 'D008726': '5366546',
 'D008747': '51063134',
 'D008748': '1674',
 'D008749': '5934',
 'D008753': '7543',
 'D008769': '135436526',
 'D008770': '12699',
 'D008771': '164739',
 'D008801': '4178',
 'D008898': '440473',
 'D008920': '26105',
 'D008936': '5284380',
 'D008970': '124222684',
 'D009002': '6061',
 'D009019': '6857497',
 'D009093': '3516',
 'D009113': '131750181',
 'D009195': '9865515',
 'D009243': '5892',
 'D009249': '57525501',
 'D009255': '19592',
 'D009256': '4416',
 'D009269': '5284595',
 'D009284': '8663',
 'D009285': '4227422',
 'D009327': '25043',
 'D009387': '31369',
 'D009429': '4461',
 'D009478': '16132350',
 'D009526': '4472',
 'D009528': '9507',
 'D009533': '5284586',
 'D009552': '5497',
 'D009554': '23009',
 'D009560': '6093',
 'D009564': '20628',
 'D009566': '943',
 'D009573': '946',
 'D009584': '947',
 'D009593': '10701',
 'D009596': '88473196',
 'D009604': '12660',
 'D009605': '12001',
 'D009611': '15532',
 'D009627': '4528',
 'D009637': '71398',
 'D009666': '5284443',
 'D009677': '5251503',
 'D009705': '139092512',
 'D009762': '7340',
 'D009763': '17604',
 'D009764': '4807',
 'D009795': '356',
 'D009840': '78358496',
 'D009848': '3084072',
 'D009888': '9417',
 'D009915': '43234',
 'D009950': '28061',
 'D010070': '6328935',
 'D010080': '9255',
 'D010081': '1712094',
 'D010082': '6451477',
 'D010094': '4604',
 'D010095': '4630',
 'D010097': '16779',
 'D010117': '135398752',
 'D010128': '6051',
 'D010134': '4652',
 'D010368': '445929',
 'D010393': '6603',
 'D010420': '8003',
 'D010451': '16132386',
 'D010590': '441542',
 'D010616': '168339423',
 'D010618': '67473',
 'D010624': '3675',
 'D010628': '9076',
 'D010657': '23611',
 'D010670': '676454',
 'D010692': '72511',
 'D010695': '6072',
 'D010704': '154992',
 'D010706': '12901',
 'D010710': '1061',
 'D010761': '156614170',
 'D010803': '44359653',
 'D010836': '5366244',
 'D010837': '5284607',
 'D010880': '44237242',
 'D010881': '12665',
 'D010883': '6040',
 'D010892': '9331',
 'D010917': '33478',
 'D010971': '21881166',
 'D011035': '10607',
 'D011060': '24751',
 'D011160': '13116',
 'D011205': '6917',
 'D011219': '135398003',
 'D011280': '31402',
 'D011294': '42396',
 'D011298': '35455',
 'D011353': '135471926',
 'D011370': '7099',
 'D011396': '20055107',
 'D011397': '36709',
 'D011400': '4929',
 'D011410': '15004',
 'D011420': '2365',
 'D011430': '6843',
 'D011431': '10100',
 'D011453': '6145931',
 'D011526': '408888',
 'D011562': '10624',
 'D011621': '1043',
 'D011684': '68368',
 'D011719': '9261',
 'D011722': '76007601',
 'D011725': '581866',
 'D011727': '4990',
 'D011740': '94271',
 'D011744': '162786624',
 'D011746': '14190',
 'D011754': '7085',
 'D011756': '644102',
 'D011758': '8027',
 'D011759': '10176084',
 'D011764': '13916',
 'D011791': '24261',
 'D011799': '9210',
 'D011803': '3034034',
 'D011810': '7045',
 'D011812': '7527',
 'D011929': '30623',
 'D012018': '9570991',
 'D012083': '168266266',
 'D012155': '439653',
 'D012294': '46835651',
 'D012368': '5087',
 'D012370': '38988396',
 'D012394': '12447',
 'D012408': '6557',
 'D012459': '54675850',
 'D012502': '21139920',
 'D012504': '6324663',
 'D012531': '29569',
 'D012535': '338',
 'D012556': '11054',
 'D012645': '15103',
 'D012787': '169494539',
 'D012841': '6433516',
 'D012844': '9833444',
 'D012855': '3084097',
 'D012862': '6736',
 'D012914': '446220',
 'D013034': '644020',
 'D013184': '5284340',
 'D013228': '23673840',
 'D013256': '139082353',
 'D013261': '1107',
 'D013267': '638088',
 'D013270': '16682734',
 'D013310': '135462992',
 'D013326': '5486204',
 'D013373': '36511',
 'D013381': '3086051',
 'D013408': '20055036',
 'D013433': '6451121',
 'D013440': '402',
 'D013447': '1099',
 'D013448': '5345',
 'D013450': '12501714',
 'D013457': '5362487',
 'D013542': '807',
 'D013578': '7172',
 'D013619': '1935',
 'D013645': '164825',
 'D013721': '11016',
 'D013751': '5842000',
 'D013759': '16078',
 'D013765': '18519',
 'D013828': '9568512',
 'D013844': '9256',
 'D013859': '21226412',
 'D013867': '1274030',
 'D013875': '3032792',
 'D013876': '8030',
 'D013885': '1084',
 'D013889': '1269845',
 'D013931': '114873',
 'D013948': '4260',
 'D013970': '5461103',
 'D013989': '38409',
 'D014053': '28523',
 'D014058': '5899068',
 'D014101': '33497',
 'D014144': '54172484',
 'D014147': '33741',
 'D014203': '5534',
 'D014213': '656634',
 'D014230': '67516',
 'D014239': '18321',
 'D014240': '6278',
 'D014243': '102515163',
 'D014265': '5799',
 'D014270': '6409',
 'D014271': '6256',
 'D014272': '5567',
 'D014288': '12028',
 'D014289': '135565598',
 'D014290': '31477',
 'D014301': '7434',
 'D014303': '8376',
 'D014304': '5497163',
 'D014315': '451674',
 'D014334': '10789',
 'D014368': '167312512',
 'D014440': '16129635',
 'D014451': '5281915',
 'D014494': '2724039',
 'D014503': '14228836',
 'D014577': '1179',
 'D014631': '114781',
 'D014638': '61672',
 'D014667': '11979316',
 'D014688': '197701',
 'D014740': '21704',
 'D014769': '168318667',
 'D014801': '445354',
 'D014805': '118701720',
 'D014814': '16217806',
 'D014908': '62935',
 'D014934': '887',
 'D014966': '7107',
 'D014975': '5281243',
 'D014980': '66376',
 'D015016': '8969',
 'D015021': '104760',
 'D015026': '449093',
 'D015031': '5365247',
 'D015049': '6103',
 'D015058': '11080',
 'D015070': '64970',
 'D015071': '21150757',
 'D015073': '5897',
 'D015078': '1000',
 'D015082': '1474',
 'D015100': '7071',
 'D015107': '7302',
 'D015112': '5955',
 'D015114': '10634',
 'D015115': '21163',
 'D015121': '5280888',
 'D015123': '41322',
 'D015125': '1923',
 'D015127': '6001',
 'D015232': '5280360',
 'D015251': '41867',
 'D015282': '448601',
 'D015287': '5311312',
 'D015363': '6038',
 'D015366': '51081',
 'D015377': '6435415',
 'D015474': '5282379',
 'D015497': '25080835',
 'D015632': '1388',
 'D015644': '5282188',
 'D015645': '168314097',
 'D015647': '1242',
 'D015652': '5710148',
 'D015662': '358641',
 'D015762': '8974',
 'D015772': '47795',
 'D015773': '5462501',
 'D015780': '134085',
 'D016081': '753',
 'D016202': '22880',
 'D016209': '44357137',
 'D016212': '56842206',
 'D016422': '23666112',
 'D016424': '5480431',
 'D016644': '5281227',
 'D016685': '5746',
 'D016700': '48041',
 'D016712': '446596',
 'D016912': '13109',
 'D017255': '5284513',
 'D017259': '3077',
 'D017307': '155774',
 'D017330': '54477',
 'D017338': '20279',
 'D017572': '5280383',
 'D017705': '443013',
 'D017762': '772',
 'D017886': '14781',
 'D017905': '107908',
 'D017953': '105034',
 'D017985': '772',
 'D018085': '2343',
 'D018496': '977',
 'D018539': '34192',
 'D019207': '5280489',
 'D019326': '6238',
 'D019332': '16212950',
 'D019333': '16219332',
 'D019365': '4130',
 'D019369': '12309456',
 'D019415': '16683004',
 'D019490': '182380',
 'D019539': '12658395',
 'D019662': '145751',
 'D019788': '68614',
 'D019789': '5413',
 'D019796': '5354027',
 'D019797': '60860',
 'D019805': '441350',
 'D019806': '443423',
 'D019825': '77231639',
 'D019830': '448222',
 'D019832': '71183',
 'D019840': '3776',
 'D019850': '8129',
 'D019856': '700',
 'D019894': '56841989',
 'D019900': '3036289',
 'D019938': '72998476',
 'D020008': '5625',
 'D020032': '2051',
 'D020111': '40470',
 'D020112': '9929799',
 'D020120': '68618',
 'D020122': '6410',
 'D020123': '5284616',
 'D020366': '6658',
 'D020372': '66265',
 'D020595': '292779',
 'D020652': '148754',
 'D020724': '6557',
 'D020738': '157010069',
 'D020748': '60663',
 'D020838': '260656',
 'D020843': '5280443',
 'D020867': '56841669',
 'D020901': '5281052',
 'D020902': '9548591',
 'D020926': '68602',
 'D020946': '36314',
 'D023303': '73949',
 'D024482': '5283547',
 'D024483': '4055',
 'D024502': '14985',
 'D024504': '92729',
 'D024505': '14986',
 'D024508': '9929901',
 'D025101': '104817',
 'D025364': '5459319',
 'D025381': '11136668',
 'D025441': '168871',
 'D025442': '107715',
 'D025443': '44272237',
 'D025801': '311',
 'D026023': '40326',
 'D027441': '5144',
 'D028341': '4435',
 'D029662': '4133',
 'D029788': '101293601',
 'D029866': '6758',
 'D030022': '2236',
 'D030024': '969516',
 'D030221': '446220',
 'D031053': '5668',
 'D031178': '135565560',
 'D031217': '5497',
 'D031231': '7129',
 'D031309': '441753',
 'D031315': '81263',
 'D031364': '94280',
 'D031451': '5304',
 'D031605': '31304',
 'D031669': '1183',
 'D031786': '5988',
 'D031944': '25113438',
 'D032108': '3440',
 'D032444': '10125785',
 'D032502': '162941839',
 'D034261': '448799',
 'D036145': '3086007',
 'D036625': '6918840',
 'D037741': '123591',
 'D038961': '72193709',
 'D039321': '969516',
 'D039821': '26049',
 'D039823': '453214',
 'D043169': '187888',
 'D043324': '18692',
 'D043424': '90477353',
 'D043564': '168266391',
 'D043582': '92810',
 'D044182': '22169421',
 'D044423': '2247',
 'D044503': '65040',
 'D044646': '91666323',
 'D044945': '107876',
 'D047071': '439262',
 'D047090': '136721',
 'D047250': '3081771',
 'D047288': '13194807',
 'D047392': '444041',
 'D048271': '21896651',
 'D048289': '449488',
 'D048789': '56842207',
 'D049883': '16692',
 'D049934': '68108',
 'D050178': '3681',
 'D050477': '62819',
 'D050858': '56841626',
 'D051844': '10307709',
 'D053492': '44201346',
 'D053607': '91976826',
 'D053644': '66491',
 'D053771': '126332',
 'D053772': '121494088',
 'D053778': '10444',
 'D054358': '11049407',
 'D054713': '44277532',
 'D054728': '119287',
 'D054795': '16140499',
 'D054816': '200742',
 'D054848': '16132327',
 'D054883': '44581450',
 'D055315': '95924',
 'D056649': '4381936',
 'D058766': '135398559',
 'D058828': '11842633',
 'D058830': '5311271',
 'D058832': '177336',
 'D058965': '18375622',
 'D058988': '656969',
 'D059648': '71306396',
 'D060754': '91469',
 'D061386': '118984375',
 'D061466': '92727',
 'D062366': '4876',
 'D062605': '138756749',
 'D063065': '177605',
 'D064098': '16048656',
 'D064412': '123600',
 'D064695': '1548953',
 'D064696': '1548955',
 'D064697': '876',
 'D064705': '838',
 'D064729': '1122655',
 'D064730': '71384',
 'D064805': '3914',
 'D065146': '5280899',
 'D065366': '5281235',
 'D065819': '71616',
 'D000068180': '60795',
 'D000068238': '157920',
 'D000068297': '56841124',
 'D000068338': '6442177',
 'D000068437': '135410875',
 'D000068538': '6918296',
 'D000068577': '134378124',
 'D000068580': '45263226',
 'D000068581': '110635',
 'D000068599': '11387895',
 'D000068600': '24847804',
 'D000068679': '60877',
 'D000068696': '6451164',
 'D000068698': '464205',
 'D000068758': '118987285',
 'D000068801': '23653552',
 'D000068856': '12658395',
 'D000068882': '9852746',
 'D000068896': '24812758',
 'D000068899': '24848107',
 'D000069286': '387447',
 'D000069438': '150311',
 'D000069439': '3062316',
 'D000069449': '156419',
 'D000069450': '16134956',
 'D000069454': '213039',
 'D000069465': '134018',
 'D000069468': '9800068',
 'D000069476': '10096344',
 'D000069479': '11274356',
 'D000069480': '11954236',
 'D000069502': '56841116',
 'D000069545': '44232548',
 'D000069547': '25151504',
 'D000069552': '9875401',
 'D000069557': '5282226',
 'D000069580': '5311027',
 'D000069582': '969472',
 'D000069583': '5486971',
 'D000069603': '3085017',
 'D000069604': '216210',
 'D000069877': '10220511',
 'D000072318': '568',
 'D000073156': '9576412',
 'D000073861': '56841713',
 'D000075385': '121564',
 'D000077122': '168013289',
 'D000077123': '441290',
 'D000077156': '123631',
 'D000077157': '216239',
 'D000077205': '4829',
 'D000077209': '451668',
 'D000077210': '5329102',
 'D000077212': '175805',
 'D000077215': '56841952',
 'D000077267': '104741',
 'D000077269': '216326',
 'D000077270': '138394057',
 'D000077285': '104850',
 'D000077287': '5284583',
 'D000077300': '104865',
 'D000077332': '146160078',
 'D000077333': '65999',
 'D000077336': '139586083',
 'D000077337': '5311',
 'D000077341': '208908',
 'D000077385': '124304713',
 'D000077404': '60613',
 'D000077422': '71188',
 'D000077423': '656641',
 'D000077425': '5282448',
 'D000077432': '9838022',
 'D000077442': '9911821',
 'D000077443': '71158',
 'D000077464': '60867',
 'D000077484': '42611257',
 'D000077486': '9871419',
 'D000077542': '448812',
 'D000077545': '443872',
 'D000077547': '11626560',
 'D000077549': '68911',
 'D000077550': '132999',
 'D000077551': '477468',
 'D000077554': '92253',
 'D000077556': '449171',
 'D000077557': '60852',
 'D000077560': '16130199',
 'D000077562': '135413535',
 'D000077584': '66414',
 'D000077585': '72081',
 'D000077588': '214348',
 'D000077590': '5281042',
 'D000077591': '2758',
 'D000077592': '3002977',

# Mesh 3

In [10]:
Mesh_supp = pd.read_csv(f'{BASE_PATH}databases_for_mapping/MESH/Mesh_Supplementary_Info.csv')
Mesh_supp
# Mesh_supp['Pubchem_ID'] = Mesh_supp['Name'].map(Pubchem_Syn_fil_dict)
Mesh_supp_dict = dict(zip(Mesh_supp['ID'], Mesh_supp['Name']))
# Mesh_supp_dict
Mesh_supp

Mesh_supp["Pubchem_ID"] = Mesh_supp["Pubchem_ID"].astype(str).str.replace(r'\.0$', '', regex=True)
Mesh_supp = Mesh_supp[Mesh_supp['Pubchem_ID']!= 'nan']
Mesh_supp

Mesh_supp_PUBCHEM_dict = dict(zip(Mesh_supp['ID'], Mesh_supp['Pubchem_ID']))
Mesh_supp_PUBCHEM_dict

{'C000009': '123826',
 'C000020': '123914',
 'C000025': '192073',
 'C000056': '198045',
 'C000061': '160603',
 'C000078': '6451193',
 'C000090': '3037582',
 'C000102': '661819',
 'C000123': '2313',
 'C000133': '6444345',
 'C000134': '130476797',
 'C000140': '197983',
 'C000165': '6444987',
 'C000185': '23665578',
 'C000188': '2078',
 'C000199': '96683',
 'C000201': '194116',
 'C000217': '16130295',
 'C000240': '96664',
 'C000263': '135580626',
 'C000277': '28768',
 'C000290': '193174',
 'C000291': '102068',
 'C000295': '154701734',
 'C000307': '121987',
 'C000317': '121894',
 'C000324': '82276',
 'C000339': '96226',
 'C000347': '6005081',
 'C000364': '23681183',
 'C000380': '3418',
 'C000405': '31124',
 'C000406': '70403',
 'C000411': '6313',
 'C000417': '192770',
 'C000425': '4617',
 'C000434': '21486',
 'C000440': '126961343',
 'C000446': '432263',
 'C000458': '9800166',
 'C000470': '27833',
 'C000475': '91477',
 'C000486': '14520',
 'C000511': '73467',
 'C000513': '192090',
 'C000670': '56843136',
 'C000813': '188236',
 'C000841': '192853',
 'C000852': '97577',
 'C000863': '193084',
 'C000878': '3489',
 'C000896': '74537',
 'C000905': '123131967',
 'C000934': '192049',
 'C000938': '193158',
 'C000954': '10245201',
 'C000961': '192778',
 'C000966': '45266921',
 'C000975': '63227',
 'C000978': '135398662',
 'C000979': '29110',
 'C000986': '440384',
 'C000993': '193180',
 'C001028': '26008',
 'C001031': '6433246',
 'C001047': '167995',
 'C001053': '31898',
 'C001060': '6433800',
 'C001079': '91585',
 'C001116': '187745',
 'C001143': '866',
 'C001147': '108123',
 'C001155': '6455355',
 'C001175': '198121',
 'C001176': '101105',
 'C001179': '32888',
 'C001181': '26990',
 'C001182': '3289',
 'C001189': '3082362',
 'C001205': '65404',
 'C001206': '192102',
 'C001244': '94937',
 'C001256': '124201540',
 'C001259': '3032624',
 'C001274': '192111',
 'C001277': '134694652',
 'C001279': '56842112',
 'C001280': '192109',
 'C001293': '439217',
 'C001295': '21120152',
 'C001338': '198498',
 'C001339': '192819',
 'C001357': '3086075',
 'C001377': '197993',
 'C001380': '124514955',
 'C001413': '74215',
 'C001421': '161109',
 'C001432': '28346',
 'C001441': '18949',
 'C001444': '56842756',
 'C001451': '3168',
 'C001453': '3080653',
 'C001481': '218945',
 'C001483': '193247',
 'C001495': '439318',
 'C001524': '66917',
 'C001527': '54692967',
 'C001536': '121895',
 'C001569': '100308',
 'C001570': '2090',
 'C001572': '189090',
 'C001584': '2318',
 'C001594': '192125',
 'C001647': '984',
 'C001654': '441298',
 'C001655': '800',
 'C001660': '71644',
 'C001664': '71388',
 'C001678': '4993',
 'C001709': '16684709',
 'C001710': '16684342',
 'C001713': '92135813',
 'C001719': '197796',
 'C001739': '160243',
 'C001742': '37770',
 'C001743': '117656',
 'C001747': '67771',
 'C001749': '15466',
 'C001784': '5614',
 'C001795': '71902',
 'C001814': '9578261',
 'C001833': '3505109',
 'C001849': '192890',
 'C001887': '198179',
 'C001888': '198105',
 'C001899': '107985',
 'C001929': '198160',
 'C001932': '33670',
 'C001933': '123658',
 'C001953': '13083',
 'C001961': '193249',
 'C001962': '94438',
 'C001963': '31752',
 'C001969': '1982',
 'C001970': '132274794',
 'C001983': '20389236',
 'C001986': '119667',
 'C001996': '6438394',
 'C002022': '11869379',
 'C002023': '168266277',
 'C002026': '159972',
 'C002051': '3034020',
 'C002055': '439507',
 'C002083': '192204',
 'C002099': '11033',
 'C002109': '164997',
 'C002116': '191051',
 'C002118': '9909482',
 'C002122': '193049',
 'C002130': '54681537',
 'C002139': '63235',
 'C002149': '169123',
 'C002172': '95155',
 'C002176': '160742',
 'C002184': '23034',
 'C002193': '78759276',
 'C002201': '67954',
 'C002239': '43268',
 'C002241': '150873',
 'C002251': '9578242',
 'C002255': '46266',
 'C002256': '22194',
 'C002271': '192998',
 'C002272': '1868',
 'C002276': '2453',
 'C002340': '191111',
 'C002351': '107941',
 'C002356': '165676',
 'C002384': '432584',
 'C002416': '121882',
 'C002447': '161718',
 'C002449': '5459861',
 'C002454': '44339430',
 'C002459': '191022',
 'C002480': '121990',
 'C002489': '3034459',
 'C002490': '159975',
 'C002493': '38114',
 'C002495': '198182',
 'C002522': '56842980',
 'C002525': '21123897',
 'C002528': '10286365',
 'C002569': '1215',
 'C002604': '193588',
 'C002605': '29643',
 'C002607': '191000',
 'C002616': '38089',
 'C002647': '107737',
 'C002656': '123743',
 'C002669': '124463365',
 'C002714': '4496',
 'C002746': '82149',
 'C002759': '191497',
 'C002764': '15249',
 'C002778': '56842690',
 'C002785': '66465',
 'C002825': '13938',
 'C002829': '151288',
 'C002843': '123684',
 'C002844': '123929',
 'C002852': '6436089',
 'C002874': '198225',
 'C002886': '73222',
 'C002889': '725',
 'C002906': '191030',
 'C002934': '191439',
 'C002953': '46878382',
 'C002957': '11309850',
 'C002968': '122250',
 'C002976': '443935',
 'C002988': '197948',
 'C003022': '193032',
 'C003027': '135524616',
 'C003028': '2724305',
 'C003048': '165681',
 'C003053': '198289',
 'C003066': '192854',
 'C003076': '133082075',
 'C003080': '61927',
 'C003100': '133082406',
 'C003109': '88892',
 'C003117': '4793',
 'C003121': '25244585',
 'C003126': '490',
 'C003129': '115254',
 'C003203': '130476753',
 'C003208': '192856',
 'C003213': '87291',
 'C003237': '4977',
 'C003264': '192209',
 'C003278': '5217',
 'C003330': '5284631',
 'C003342': '115244',
 'C003356': '6452619',
 'C003361': '87190',
 'C003371': '5362',
 'C003384': '5281143',
 'C003444': '44154285',
 'C003486': '159950',
 'C003489': '169510',
 'C003602': '72142',
 'C003681': '122166',
 'C003705': '100586',
 'C003716': '5462821',
 'C003741': '9962735',
 'C003752': '3083806',
 'C003799': '105003',
 'C003807': '193445',
 'C003808': '206186',
 'C003816': '193737',
 'C003824': '33208',
 'C003826': '87757',
 'C003832': '23620393',
 'C003833': '193026',
 'C003903': '56842111',
 'C003922': '51026956',
 'C003932': '193767',
 'C003946': '3014700',
 'C003949': '107812',
 'C003959': '2724126',
 'C004158': '35909',
 'C004221': '193265',
 'C004222': '191056',
 'C004223': '189937',
 'C004233': '23672589',
 'C004278': '21124022',
 'C004297': '1663',
 'C004315': '2950',
 'C004327': '4822',
 'C004345': '5563',
 'C004357': '2722',
 'C004371': '101008927',
 'C004373': '14607',
 'C004376': '30770',
 'C004377': '4832',
 'C004378': '26348',
 'C004379': '161394',
 'C004380': '166842',
 'C004382': '21260',
 'C004384': '28815',
 'C004406': '156588128',
 'C004451': '3515',
 'C004468': '3955344',
 'C004470': '2481',
 'C004541': '5280373',
 'C004551': '81831',
 'C004554': '1483',
 'C004580': '4846',
 'C004605': '2482',
 'C004612': '24185173',
 'C004639': '2910',
 'C004648': '9416',
 'C004649': '2564',
 'C004704': '2895',
 'C004742': '5281708',
 'C004768': '648',
 'C004783': '16010',
 'C004784': '1068',
 'C004808': '445713',
 'C004809': '1195',
 'C004820': '3081487',
 'C004839': '8569',
 'C004921': '30869',
 'C004936': '5795',
 'C004940': '129627904',
 'C004946': '763',
 'C004955': '3032325',
 'C004965': '3663',
 'C004999': '445858',
 'C005002': '7327',
 'C005013': '61680',
 'C005031': '2682',
 'C005034': '3601',
 'C005041': '16683105',
 'C005054': '74370',
 'C005087': '58',
 'C005096': '4031',
 'C005134': '3806',
 'C005150': '44152178',
 'C005156': '724',
 'C005164': '191113',
 'C005172': '138399674',
 'C005177': '123809',
 'C005188': '64113',
 'C005249': '4487',
 'C005270': '3032297',
 'C005273': '667495',
 'C005274': '442428',
 'C005284': '1985',
 'C005290': '4632',
 'C005296': '1047',
 'C005311': '412',
 'C005313': '65098',
 'C005355': '708392',
 'C005364': '44152708',
 'C005390': '18674933',
 'C005396': '4753',
 'C005419': '4634',
 'C005425': '452306',
 'C005436': '21120283',
 'C005437': '24892730',
 'C005489': '192962',
 'C005518': '9578079',
 'C005522': '2816',
 'C005525': '9231',
 'C005532': '192909',
 'C005539': '193268',
 'C005540': '54684780',
 'C005543': '3037648',
 'C005544': '3037650',
 'C005548': '4886',
 'C005553': '688020',
 'C005559': '15788362',
 'C005589': '4994',
 'C005612': '95219',
 'C005618': '448223',
 'C005629': '6452259',
 'C005649': '5464827',
 'C005662': '514186',
 'C005669': '160258',
 'C005671': '443947',
 'C005672': '170652',
 'C005674': '20056650',
 'C005679': '5430',
 'C005696': '439503',
 'C005699': '14978',
 'C005711': '71490',
 'C005759': '97711',
 'C005810': '5419',
 'C005847': '13943',
 'C005893': '64959',
 'C005894': '22951',
 'C005905': '123925',
 'C005906': '6419726',
 'C005912': '192940',
 'C005913': '190999',
 'C005914': '193668',
 'C005935': '192857',
 'C005938': '67538',
 'C005941': '123926',
 'C005954': '96215',
 'C005974': '191171',
 'C005979': '193157',
 'C005986': '162271',
 'C006007': '193072',
 'C006008': '135882',
 'C006009': '39423',
 'C006011': '191273',
 'C006013': '32249',
 'C006015': '39876',
 'C006017': '191018',
 'C006018': '22400',
 'C006019': '137171757',
 'C006021': '191045',
 'C006022': '171155',
 'C006023': '74015',
 'C006024': '191328',
 'C006025': '6438326',
 'C006026': '191330',
 'C006028': '20839734',
 'C006033': '193228',
 'C006040': '198052',
 'C006043': '193488',
 'C006049': '134533',
 'C006053': '8994',
 'C006054': '170685',
 'C006055': '23695981',
 'C006059': '123131984',
 'C006064': '3032295',
 'C006065': '86554',
 'C006069': '4066',
 'C006070': '191168',
 'C006072': '5014',
 'C006074': '161793',
 'C006075': '166875',
 'C006076': '12272670',
 'C006079': '63217',
 'C006081': '37534',
 'C006082': '40315',
 'C006083': '191272',
 'C006086': '197073',
 'C006087': '198211',
 'C006098': '9578230',
 'C006102': '63236',
 'C006104': '21632',
 'C006107': '3369',
 'C006108': '32264',
 'C006109': '25087096',
 'C006115': '45221',
 'C006125': '193040',
 'C006128': '191583',
 'C006135': '3037672',
 'C006138': '191116',
 'C006141': '192807',
 'C006146': '43260',
 'C006148': '187754',
 'C006149': '4199',
 'C006151': '9578226',
 'C006152': '3083827',
 'C006153': '6419536',
 'C006156': '3084644',
 'C006157': '198328',
 'C006158': '123131953',
 'C006159': '187075',
 'C006166': '4767',
 'C006167': '167016',
 'C006171': '160196',
 'C006178': '191267',
 'C006180': '15639',
 'C006184': '198237',
 'C006185': '192164',
 'C006187': '198189',
 'C006189': '833992',
 'C006193': '130476783',
 'C006196': '187762',
 'C006201': '121749',
 'C006207': '10065',
 'C006210': '182525',
 'C006212': '192845',
 'C006215': '187760',
 'C006219': '164715',
 'C006220': '15179',
 'C006222': '18924',
 'C006223': '198063',
 'C006226': '5121',
 'C006227': '191128',
 'C006228': '191162',
 'C006229': '191222',
 'C006231': '2787',
 'C006232': '193122',
 'C006233': '6442702',
 'C006235': '65482',
 'C006236': '191226',
 'C006237': '65804',
 'C006242': '9909202',
 'C006245': '193079',
 'C006246': '193155',
 'C006248': '187768',
 'C006255': '78759272',
 'C006257': '78902',
 'C006258': '2475',
 'C006259': '192851',
 'C006262': '3084994',
 'C006263': '169688',
 'C006264': '193834',
 'C006265': '78759271',
 'C006266': '164903',
 'C006268': '78759270',
 'C006269': '3084602',
 'C006271': '23201',
 'C006272': '198023',
 'C006274': '5360854',
 'C006275': '193037',
 'C006276': '191242',
 'C006278': '15558776',
 'C006279': '23717270',
 'C006282': '5376329',
 'C006283': '161969',
 'C006285': '191219',
 'C006286': '10387872',
 'C006290': '193176',
 'C006291': '193178',
 'C006292': '31755',
 'C006293': '130476743',
 'C006294': '90174',
 'C006296': '193243',
 'C006298': '193623',
 'C006299': '191318',
 'C006301': '193715',
 'C006302': '16132201',
 'C006303': '294641',
 'C006318': '191164',
 'C006319': '193267',
 'C006323': '191192',
 'C006325': '119058382',
 'C006326': '5311100',
 'C006328': '6438146',
 'C006329': '191024',
 'C006358': '1990',
 'C006359': '79041',
 'C006362': '36573',
 'C006389': '903',
 'C006434': '2075',
 'C006475': '6441696',
 'C006480': '2122',
 'C006481': '5372477',
 'C006495': '215',
 'C006500': '1725',
 'C006509': '118',
 'C006552': '5280863',
 'C006587': '191297',
 'C006624': '2227',
 'C006648': '114965',
 'C006661': '11622340',
 'C006680': '5281605',
 'C006688': '86853',
 'C006694': '22570228',
 'C006717': '6957673',
 'C006727': '170882',
 'C006735': '99625',
 'C006741': '66065',
 'C006749': '10047593',
 'C006820': '2448',
 'C006827': '2450',
 'C006834': '198092',
 'C006836': '5284194',
 'C006864': '193102',
 'C006915': '176364',
 'C006922': '2580',
 'C006927': '123131970',
 'C006933': '123727',
 'C006963': '73356211',
 'C006972': '300',
 'C006991': '122278',
 'C007005': '2581',
 'C007027': '2723',
 'C007042': '99470',
 'C007064': '17550',
 'C007077': '123830',
 'C007111': '441082',
 'C007133': '23694214',
 'C007165': '326',
 'C007252': '198210',
 'C007253': '122305',
 'C007267': '65063',
 'C007296': '171353',
 'C007331': '10070225',
 'C007409': '663',
 'C007419': '649',
 'C007424': '15942885',
 'C007428': '124011',
 'C007429': '586807',
 'C007445': '122254',
 'C007471': '123988',
 'C007484': '6449898',
 'C007552': '191487',
 'C007558': '122136',
 'C007621': '56842870',
 'C007639': '3280',
 'C007665': '6453004',
 'C007676': '6443537',
 'C007687': '5139',
 'C007701': '448701',
 'C007704': '16887',
 'C007725': '2314',
 'C007729': '129010909',
 'C007734': '82153',
 'C007768': '5280378',
 'C007772': '439788',
 'C007792': '156614042',
 'C007817': '123986',
 'C007829': '6336690',
 'C007845': '442793',
 'C007904': '3565',
 'C007906': '17734',
 'C007908': '91453',
 'C007931': '439210',
 'C007946': '54685921',
 'C007961': '368',
 'C007982': '77262',
 'C007999': '123908',
 'C008047': '5288565',
 'C008064': '189145',
 'C008070': '127',
 'C008087': '54094975',
 'C008088': '163285106',
 'C008117': '46878464',
 'C008122': '803',
 'C008124': '4537',
 'C008125': '442042',
 'C008129': '9578160',
 'C008215': '10486087',
 'C008252': '3884',
 'C008285': '11369954',
 'C008301': '73755142',
 'C008315': '139024271',
 'C008317': '134731361',
 'C008322': '440049',
 'C008352': '5284587',
 'C008366': '98',
 'C008376': '10633',
 'C008446': '4141',
 'C008478': '54694264',
 'C008498': '191134',
 'C008500': '439176',
 'C008527': '44152261',
 'C008534': '26175',
 'C008535': '188192',
 'C008542': '4247',
 'C008548': '5281670',
 'C008570': '6335494',
 'C008599': '4511',
 'C008698': '11953814',
 'C008704': '1570',
 'C008710': '16015',
 'C008733': '21133122',
 'C008745': '12111',
 'C008757': '445638',
 'C008784': '91343789',
 'C008837': '4770',
 'C008847': '129703981',
 'C008884': '91493',
 'C008885': '59',
 'C008886': '4797',
 'C008890': '445114',
 'C008922': '638024',
 'C009021': '93055',
 'C009061': '92753',
 'C009091': '72',
 'C009093': '4970',
 'C009106': '171266',
 'C009158': '7157',
 'C009167': '444596',
 'C009185': '4904',
 'C009193': '6443641',
 'C009194': '122306',
 'C009265': '104778',
 'C009272': '70678579',
 'C009282': '20587905',
 'C009293': '510',
 'C009335': '123989',
 'C009342': '5315',
 'C009349': '5334',
 'C009350': '3034019',
 'C009365': '65307',
 'C009367': '124201513',
 'C009375': '12620',
 'C009438': '73078',
 'C009500': '610479',
 'C009544': '102133',
 'C009616': '12303782',
 'C009621': '117587708',
 'C009626': '68953',
 'C009636': '192183',
 'C009658': '133562811',
 'C009659': '122361360',
 'C009662': '17407',
 'C009695': '5709',
 'C009710': '191334',
 'C009711': '3036948',
 'C009714': '162751',
 'C009721': '92975',
 'C009727': '123880',
 'C009739': '16244336',
 'C009743': '73013',
 'C009744': '6450208',
 'C009776': '92145762',
 'C009777': '121896',
 'C009819': '134748002',
 'C009850': '2272',
 'C009871': '3103',
 'C009910': '191354',
 'C009935': '5834',
 'C009947': '13',
 'C009955': '191841',
 'C009965': '30746',
 'C009967': '68053',
 'C009968': '41818',
 'C009975': '171399',
 'C009977': '193204',
 'C009982': '193077',
 'C009985': '3085126',
 'C009988': '3086105',
 'C009989': '37408',
 'C009991': '135444498',
 'C009992': '191357',
 'C009993': '191050',
 'C009994': '135487866',
 'C009995': '3084687',
 'C009996': '182603',
 'C009998': '205980',
 'C010001': '10063495',
 'C010038': '2266',
 'C010047': '6453972',
 'C010052': '104762',
 'C010086': '90454',
 'C010098': '6437867',
 'C010121': '3084298',
 'C010161': '135450591',
 'C010163': '156963378',
 'C010192': '3206',
 'C010199': '122331',
 'C010212': '5486808',
 'C010247': '107748',
 'C010272': '11105289',
 'C010277': '122307',
 'C010285': '70343',
 'C010293': '4839',
 'C010312': '4969',
 'C010317': '133565271',
 'C010327': '3085092',
 'C010329': '5281303',
 'C010333': '192200',
 'C010346': '5383',
 'C010395': '91626',
 'C010400': '102302',
 'C010402': '93307',
 'C010408': '8386',
 'C010513': '6917970',
 'C010514': '122082',
 'C010527': '100434',
 'C010528': '39832',
 'C010531': '443600',
 'C010543': '123131907',
 'C010585': '6454255',
 'C010627': '1053',
 'C010631': '5146',
 'C010638': '189117',
 'C010648': '176160',
 'C010649': '36582',
 'C010650': '124165',
 'C010652': '34772',
 'C010657': '197125',
 'C010660': '193731',
 'C010679': '2197',
 'C010680': '123865',
 'C010685': '72774',
 'C010701': '5497143',
 'C010714': '5282415',
 'C010725': '3335',
 'C010745': '493591',
 'C010809': '5606',
 'C010812': '53463627',
 'C010814': '182562',
 'C010817': '41489',
 'C010823': '3082317',
 'C010834': '42479',
 'C010854': '121973',
 'C010861': '2735434',
 'C010892': '3080894',
 'C010893': '71386',
 'C010919': '36649',
 'C010920': '135398604',
 'C010944': '5312531',
 'C010948': '168013030',
 'C010959': '133128',
 'C010972': '756',
 'C010991': '122155',
 'C011028': '271070',
 'C011043': '94803',
 'C011069': '168311681',
 'C011075': '192161',
 'C011088': '4931',
 'C011107': '5192',
 'C011136': '123648',
 'C011141': '73323',
 'C011142': '171633',
 'C011145': '135399235',
 'C011146': '78292',
 'C011266': '185944',
 'C011267': '3002143',
 'C011275': '101',
 'C011276': '102',
 'C011283': '90274',
 'C011295': '192127',
 'C011309': '162906601',
 'C011351': '3035448',
 'C011358': '102818',
 'C011380': '191530',
 'C011383': '38312',
 'C011384': '204075',
 'C011387': '3015633',
 'C011394': '123787',
 'C011395': '122652044',
 'C011410': '2444',
 'C011436': '72720474',
 'C011439': '66021',
 'C011440': '92043891',
 'C011465': '12598380',
 'C011483': '126',
 'C011488': '121994',
 'C011509': '4594',
 'C011523': '66443',
 'C011533': '38622',
 'C011536': '123786',
 'C011539': '121893',
 'C011552': '135453284',
 'C011556': '5750263',
 'C011572': '16219292',
 'C011574': '6446338',
 'C011580': '6441669',
 'C011581': '4814',
 'C011584': '12382989',
 'C011586': '193281',
 'C011587': '28247',
 'C011588': '194064',
 'C011593': '31679',
 'C011600': '197183',
 'C011607': '6441423',
 'C011610': '162356',
 'C011611': '173662',
 'C011613': '5283079',
 'C011617': '70073',
 'C011619': '118749',
 'C011632': '186',
 'C011638': '123672',
 'C011639': '3153',
 'C011666': '3081545',
 'C011674': '441397',
 'C011705': '40118',
 'C011729': '4377441',
 'C011757': '364',
 'C011775': '123703',
 'C011786': '5463010',
 'C011800': '123857',
 'C011804': '195931',
 'C011820': '136170947',
 'C011821': '193443',
 'C011835': '104556',
 'C011856': '66418',
 'C011870': '122047',
 'C011878': '156614111',
 'C011889': '45934481',
 'C011890': '3840',
 'C011916': '3036488',
 'C011961': '73981',
 'C011987': '5283213',
 'C012008': '6453768',
 'C012037': '129316900',
 'C012048': '165682',
 'C012086': '124349',
 'C012093': '565690',
 'C012099': '122034',
 'C012102': '3172',
 'C012105': '173884',
 'C012106': '3085028',
 'C012111': '6440846',
 'C012115': '124946',
 'C012123': '159963',
 'C012127': '6443559',
 'C012128': '151580',
 'C012131': '133082267',
 'C012134': '56840988',
 'C012137': '193057',
 'C012139': '162367',
 'C012141': '198325',
 'C012145': '9884658',
 'C012148': '44144573',
 'C012149': '162898',
 'C012151': '169573',
 'C012152': '64390',
 'C012153': '123920',
 'C012168': '447145',
 'C012177': '1539',
 'C012183': '53486222',
 'C012186': '5280746',
 'C012210': '73243',
 'C012224': '91824750',
 'C012260': '2896',
 'C012262': '2911',
 'C012267': '7206',
 'C012271': '135398593',
 'C012293': '5282230',
 'C012301': '5282253',
 'C012316': '26696',
 'C012332': '67156',
 'C012333': '440772',
 'C012335': '53462729',
 'C012343': '3526',
 'C012375': '964',
 'C012385': '40065',

## ENSEMBL to Gene Name

In [11]:
ENS_2NCBI = pd.read_csv(f'{BASE_PATH}databases_for_mapping/ENSEMBL/ENSEMBLE_ID_2_NCBI_Gene_SYM.csv') # 86402 ENS ID's
ENS_2NCBI = ENS_2NCBI[~ENS_2NCBI['name'].isna()] # 42530 ENS ID's without nan
ENS_2NCBI.head(3)
NCBI_2ENS__dict = dict(zip(ENS_2NCBI['name'], ENS_2NCBI['initial_alias']))

## NCBI

In [12]:
NCBI_ALL_GENE = pd.read_csv(f'{BASE_PATH}databases_for_mapping/ncbi/Homo_sapiens.gene_info',sep = '\t') # NCBI_2ENS__dict
# NCBI_ALL_GENEname_dict =  dict(zip(NCBI_ALL_GENE['Symbol'], NCBI_ALL_GENE['description']))
NCBI_ALL_GENE['ENSEMBLE_ID'] = NCBI_ALL_GENE['Symbol'].map(NCBI_2ENS__dict)
NCBI_ALL_GENEname_dict =  dict(zip(NCBI_ALL_GENE['Symbol'], NCBI_ALL_GENE['description']))
NCBI_ALL_GENE.head()

,#tax_id,GeneID,Symbol,LocusTag,Synonyms,dbXrefs,chromosome,map_location,description,type_of_gene,Symbol_from_nomenclature_authority,Full_name_from_nomenclature_authority,Nomenclature_status,Other_designations,Modification_date,Feature_type,ENSEMBLE_ID
0,9606,1,A1BG,-,A1B|ABG|GAB|HYST2477,MIM:138670|HGNC:HGNC:5|Ensembl:ENSG00000121410...,19,19q13.43,alpha-1-B glycoprotein,protein-coding,A1BG,alpha-1-B glycoprotein,O,alpha-1B-glycoprotein|HEL-S-163pA|epididymis s...,20250208,-,ENSG00000121410
1,9606,2,A2M,-,A2MD|CPAMD5|FWP007|S863-7,MIM:103950|HGNC:HGNC:7|Ensembl:ENSG00000175899...,12,12p13.31,alpha-2-macroglobulin,protein-coding,A2M,alpha-2-macroglobulin,O,alpha-2-macroglobulin|C3 and PZP-like alpha-2-...,20250208,-,ENSG00000175899
2,9606,3,A2MP1,-,A2MP,HGNC:HGNC:8|Ensembl:ENSG00000291190|AllianceGe...,12,12p13.31,alpha-2-macroglobulin pseudogene 1,pseudo,A2MP1,alpha-2-macroglobulin pseudogene 1,O,pregnancy-zone protein pseudogene,20241210,-,ENSG00000291190
3,9606,9,NAT1,-,AAC1|MNAT|NAT-1|NATI,MIM:108345|HGNC:HGNC:7645|Ensembl:ENSG00000171...,8,8p22,N-acetyltransferase 1,protein-coding,NAT1,N-acetyltransferase 1,O,arylamine N-acetyltransferase 1|N-acetyltransf...,20250208,-,ENSG00000171428
4,9606,10,NAT2,-,AAC2|NAT-2|PNAT,MIM:612182|HGNC:HGNC:7646|Ensembl:ENSG00000156...,8,8p22,N-acetyltransferase 2,protein-coding,NAT2,N-acetyltransferase 2,O,arylamine N-acetyltransferase 2|N-acetyltransf...,20250208,-,ENSG00000156006

# AgeAnno

## Drug_Gene

In [13]:
Dis_Drug = pd.read_csv(f'{BASE_PATH}ageanno/AgeAnno-main/Disease&Drug/Related_diseases.txt', sep=',')
Dis_Drug = Dis_Drug.rename(columns={'geneSymbol':'Head','source':'Source'})
Dis_Drug

,geneId,Head,DSI,DPI,diseaseId,score,EI,YearInitial,YearFinal,number of pmid,Source
0,1,A1BG,0.70,0.538,C0001418,0.01,1.0,2008.0,2008.0,20,LHGDN
1,1,A1BG,0.70,0.538,C0002736,0.01,1.0,2008.0,2008.0,20,BEFREE
2,1,A1BG,0.70,0.538,C0003578,0.01,1.0,2017.0,2017.0,20,BEFREE
3,1,A1BG,0.70,0.538,C0003864,0.01,1.0,2019.0,2019.0,20,BEFREE
4,1,A1BG,0.70,0.538,C0008373,0.01,1.0,2020.0,2020.0,20,BEFREE
...,...,...,...,...,...,...,...,...,...,...,...
590714,100996492,CTXND1,0.89,0.077,C0024623,0.01,1.0,2019.0,2019.0,2,BEFREE
590715,100996492,CTXND1,0.89,0.077,C0027651,0.01,1.0,2018.0,2018.0,2,BEFREE
590716,100996492,CTXND1,0.89,0.077,C0206624,0.01,1.0,2018.0,2018.0,2,BEFREE
590717,100996492,CTXND1,0.89,0.077,C0699791,0.01,1.0,2019.0,2019.0,2,BEFREE
590718,100996492,CTXND1,0.89,0.077,C1269955,0.01,1.0,2019.0,2019.0,2,BEFREE

In [14]:
Dis_Drug['Tail'] = Dis_Drug['diseaseId'].map(Mesh2DOID_dict).fillna(Dis_Drug['diseaseId'])
Dis_Drug['Tail_detail_name'] = Dis_Drug['Tail'].map(DOID_disname_dict).fillna(Dis_Drug['Tail'].map(Mesh2DOID_dict).fillna(Dis_Drug['Tail'].map(MedGen_CUID_Source_ID_name_dict)))
Dis_Drug

,geneId,Head,DSI,DPI,diseaseId,score,EI,YearInitial,YearFinal,number of pmid,Source,Tail,Tail_detail_name
0,1,A1BG,0.70,0.538,C0001418,0.01,1.0,2008.0,2008.0,20,LHGDN,C0001418,adenocarcinoma
1,1,A1BG,0.70,0.538,C0002736,0.01,1.0,2008.0,2008.0,20,BEFREE,C0002736,amyotrophic lateral sclerosis
2,1,A1BG,0.70,0.538,C0003578,0.01,1.0,2017.0,2017.0,20,BEFREE,C0003578,apnea
3,1,A1BG,0.70,0.538,C0003864,0.01,1.0,2019.0,2019.0,20,BEFREE,C0003864,arthritis
4,1,A1BG,0.70,0.538,C0008373,0.01,1.0,2020.0,2020.0,20,BEFREE,C0008373,cholesteatoma
...,...,...,...,...,...,...,...,...,...,...,...,...,...
590714,100996492,CTXND1,0.89,0.077,C0024623,0.01,1.0,2019.0,2019.0,2,BEFREE,C0024623,gastric cancer
590715,100996492,CTXND1,0.89,0.077,C0027651,0.01,1.0,2018.0,2018.0,2,BEFREE,C0027651,neoplasm
590716,100996492,CTXND1,0.89,0.077,C0206624,0.01,1.0,2018.0,2018.0,2,BEFREE,C0206624,hepatoblastoma
590717,100996492,CTXND1,0.89,0.077,C0699791,0.01,1.0,2019.0,2019.0,2,BEFREE,C0699791,gastric carcinoma
590718,100996492,CTXND1,0.89,0.077,C1269955,0.01,1.0,2019.0,2019.0,2,BEFREE,C1269955,tumor cell invasion

In [15]:
Dis_Drug['Head_detail_name'] = Dis_Drug['Head'].map(NCBI_ALL_GENEname_dict)
Dis_Drug

,geneId,Head,DSI,DPI,diseaseId,score,EI,YearInitial,YearFinal,number of pmid,Source,Tail,Tail_detail_name,Head_detail_name
0,1,A1BG,0.70,0.538,C0001418,0.01,1.0,2008.0,2008.0,20,LHGDN,C0001418,adenocarcinoma,alpha-1-B glycoprotein
1,1,A1BG,0.70,0.538,C0002736,0.01,1.0,2008.0,2008.0,20,BEFREE,C0002736,amyotrophic lateral sclerosis,alpha-1-B glycoprotein
2,1,A1BG,0.70,0.538,C0003578,0.01,1.0,2017.0,2017.0,20,BEFREE,C0003578,apnea,alpha-1-B glycoprotein
3,1,A1BG,0.70,0.538,C0003864,0.01,1.0,2019.0,2019.0,20,BEFREE,C0003864,arthritis,alpha-1-B glycoprotein
4,1,A1BG,0.70,0.538,C0008373,0.01,1.0,2020.0,2020.0,20,BEFREE,C0008373,cholesteatoma,alpha-1-B glycoprotein
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
590714,100996492,CTXND1,0.89,0.077,C0024623,0.01,1.0,2019.0,2019.0,2,BEFREE,C0024623,gastric cancer,cortexin domain containing 1
590715,100996492,CTXND1,0.89,0.077,C0027651,0.01,1.0,2018.0,2018.0,2,BEFREE,C0027651,neoplasm,cortexin domain containing 1
590716,100996492,CTXND1,0.89,0.077,C0206624,0.01,1.0,2018.0,2018.0,2,BEFREE,C0206624,hepatoblastoma,cortexin domain containing 1
590717,100996492,CTXND1,0.89,0.077,C0699791,0.01,1.0,2019.0,2019.0,2,BEFREE,C0699791,gastric carcinoma,cortexin domain containing 1
590718,100996492,CTXND1,0.89,0.077,C1269955,0.01,1.0,2019.0,2019.0,2,BEFREE,C1269955,tumor cell invasion,cortexin domain containing 1

In [16]:
Dis_Drug['Head_type'] = 'Gene'
Dis_Drug['Tail_type'] = 'Disease'
Dis_Drug['Relation'] = 'Gene_Disease'
Dis_Drug['Relation_Source'] = 'AgeAnno'
Dis_Drug['Head_ID_IS'] = 'NCBI_ID'
Dis_Drug['Tail_ID_IS'] = np.where(
    Dis_Drug['Tail'].isna(),
    None,                          # ← None instead of np.nan
    np.where(
        Dis_Drug['Tail'].str.startswith('DOID'),
        'DOID',
        'MESH_ID'
    )
)
Dis_Drug['Species'] = 'Homo sapiens'
Dis_Drug

desired_cols = ["Head", "Relation", "Tail", "Head_type", "Relation_type", "Tail_type", 
                "KG_Source", "Head_UBERON_ID", "Head_GO_ID", "Head_HP_ID", "Head_Alias_mapped", 
                "Head_detail_name", "Head_ENS", "Head_DO_name", "Head_DO_Alt_ids", "Tail_UBERON_ID", "Tail_Alias_mapped",
                "Tail_detail_name", "Relation_Source","Head_ID_IS", "Tail_ID_IS", "Tail_GO_ID", "Tail_ENS", "evidence", "response","disease", "Species"]
# Filter out the columns that don't exist in the DataFrame
existing_cols = [col for col in desired_cols if col in Dis_Drug.columns]

# Reorder the DataFrame using only the columns that exist
Dis_Drug = Dis_Drug[existing_cols]
Dis_Drug

,Head,Relation,Tail,Head_type,Tail_type,Head_detail_name,Tail_detail_name,Relation_Source,Head_ID_IS,Tail_ID_IS,Species
0,A1BG,Gene_Disease,C0001418,Gene,Disease,alpha-1-B glycoprotein,adenocarcinoma,AgeAnno,NCBI_ID,MESH_ID,Homo sapiens
1,A1BG,Gene_Disease,C0002736,Gene,Disease,alpha-1-B glycoprotein,amyotrophic lateral sclerosis,AgeAnno,NCBI_ID,MESH_ID,Homo sapiens
2,A1BG,Gene_Disease,C0003578,Gene,Disease,alpha-1-B glycoprotein,apnea,AgeAnno,NCBI_ID,MESH_ID,Homo sapiens
3,A1BG,Gene_Disease,C0003864,Gene,Disease,alpha-1-B glycoprotein,arthritis,AgeAnno,NCBI_ID,MESH_ID,Homo sapiens
4,A1BG,Gene_Disease,C0008373,Gene,Disease,alpha-1-B glycoprotein,cholesteatoma,AgeAnno,NCBI_ID,MESH_ID,Homo sapiens
...,...,...,...,...,...,...,...,...,...,...,...
590714,CTXND1,Gene_Disease,C0024623,Gene,Disease,cortexin domain containing 1,gastric cancer,AgeAnno,NCBI_ID,MESH_ID,Homo sapiens
590715,CTXND1,Gene_Disease,C0027651,Gene,Disease,cortexin domain containing 1,neoplasm,AgeAnno,NCBI_ID,MESH_ID,Homo sapiens
590716,CTXND1,Gene_Disease,C0206624,Gene,Disease,cortexin domain containing 1,hepatoblastoma,AgeAnno,NCBI_ID,MESH_ID,Homo sapiens
590717,CTXND1,Gene_Disease,C0699791,Gene,Disease,cortexin domain containing 1,gastric carcinoma,AgeAnno,NCBI_ID,MESH_ID,Homo sapiens
590718,CTXND1,Gene_Disease,C1269955,Gene,Disease,cortexin domain containing 1,tumor cell invasion,AgeAnno,NCBI_ID,MESH_ID,Homo sapiens

In [17]:
Dis_Drug.to_csv(f'{OUT_PATH}ageanno_processed/AgeAnno_Gene_Disease.csv', index = None)

## Drug_Gene

In [3]:
Dis_Drug = pd.read_csv(f'{BASE_PATH}ageanno/AgeAnno-main/Disease&Drug/Related_drugs.txt', sep=','
)
Dis_Drug

,ChemicalName,ChemicalID,GeneSymbol,GeneForms,InteractionActions,PubMedIDs
0,10074-G5,C534883,AR,protein,10074-G5 inhibits the reaction [EPHB2 protein ...,32184358
1,10074-G5,C534883,AR,protein,10074-G5 results in decreased expression of AR...,32184358
2,10074-G5,C534883,AR,protein,10074-G5 results in decreased expression of AR...,32184358
3,10074-G5,C534883,EPHB2,protein,10074-G5 inhibits the reaction [EPHB2 protein ...,32184358
4,10074-G5,C534883,EPHB2,protein,10074-G5 inhibits the reaction [EPHB2 protein ...,32184358
...,...,...,...,...,...,...
1162922,Zymosan,D015054,VCAM1,protein,Sirolimus inhibits the reaction [Zymosan analo...,16797888
1162923,Zymosan,D015054,VCAM1,protein,Zymosan analog results in increased expression...,16797888
1162924,Zymosan,D015054,VEGFA,protein,TNFRSF1A gene mutant form inhibits the reactio...,17724436
1162925,Zymosan,D015054,VEGFA,protein,Zymosan results in increased expression of VEG...,17724436
1162926,zymosterol,C015582,MSMO1,protein,MSMO1 protein results in decreased abundance o...,23125191

In [18]:
# ── Load ──────────────────────────────────────────────────────────────────────
Dis_Drug = pd.read_csv(f'{BASE_PATH}ageanno/AgeAnno-main/Disease&Drug/Related_drugs.txt', sep=','
)

# ── Rename columns ────────────────────────────────────────────────────────────
Dis_Drug = Dis_Drug.rename(columns={'geneSymbol': 'Tail', 'ChemicalID': 'Head_MESH'})

print("Unique PubMedIDs:", len(set(Dis_Drug['PubMedIDs'])))

# ── Map MESH → PubChem ID ─────────────────────────────────────────────────────
assert 'ChemicalName' in Dis_Drug.columns, "ChemicalName column missing!"

Dis_Drug['Head'] = (
    Dis_Drug['Head_MESH'].map(Mesh_PUBCHEM_dict)
    .fillna(Dis_Drug['Head_MESH'].map(Mesh_supp_PUBCHEM_dict))
    .fillna(Dis_Drug['ChemicalName'].map(Pubchem_Syn_fil_dict_lower))
)

# Clean float artifacts (e.g. '12345.0' → '12345')
Dis_Drug['Head'] = Dis_Drug['Head'].astype(str).str.replace(r'\.0$', '', regex=True)

# Drop rows where no PubChem ID was found
Dis_Drug = Dis_Drug[Dis_Drug['Head'].notna() & (Dis_Drug['Head'] != 'nan')]

# ── Enrich Head (Chemical) ────────────────────────────────────────────────────
Dis_Drug['Head_detail_name'] = Dis_Drug['Head'].map(Pubchem_IUPAC_CID_Dict)
Dis_Drug['Head_SMILE_name']  = Dis_Drug['Head'].map(Pubchem_CID_Smile_Dict)

Unique PubMedIDs: 83699

In [19]:
Dis_Drug = Dis_Drug.rename(columns={'GeneSymbol':'Tail'})
Dis_Drug

# # ── Enrich Tail (Gene) ────────────────────────────────────────────────────────

Dis_Drug['Tail_detail_name'] = Dis_Drug['Tail'].map(NCBI_ALL_GENEname_dict)
Dis_Drug = Dis_Drug[Dis_Drug['Tail_detail_name'] != 'nan']
Dis_Drug

,ChemicalName,Head_MESH,Tail,GeneForms,InteractionActions,PubMedIDs,Head,Head_detail_name,Head_SMILE_name,Tail_detail_name
0,10074-G5,C534883,AR,protein,10074-G5 inhibits the reaction [EPHB2 protein ...,32184358,2836600,"4-nitro-N-(2-phenylphenyl)-2,1,3-benzoxadiazol...",C1=CC=C(C=C1)C2=CC=CC=C2NC3=CC=C(C4=NON=C34)[N...,androgen receptor
1,10074-G5,C534883,AR,protein,10074-G5 results in decreased expression of AR...,32184358,2836600,"4-nitro-N-(2-phenylphenyl)-2,1,3-benzoxadiazol...",C1=CC=C(C=C1)C2=CC=CC=C2NC3=CC=C(C4=NON=C34)[N...,androgen receptor
2,10074-G5,C534883,AR,protein,10074-G5 results in decreased expression of AR...,32184358,2836600,"4-nitro-N-(2-phenylphenyl)-2,1,3-benzoxadiazol...",C1=CC=C(C=C1)C2=CC=CC=C2NC3=CC=C(C4=NON=C34)[N...,androgen receptor
3,10074-G5,C534883,EPHB2,protein,10074-G5 inhibits the reaction [EPHB2 protein ...,32184358,2836600,"4-nitro-N-(2-phenylphenyl)-2,1,3-benzoxadiazol...",C1=CC=C(C=C1)C2=CC=CC=C2NC3=CC=C(C4=NON=C34)[N...,EPH receptor B2
4,10074-G5,C534883,EPHB2,protein,10074-G5 inhibits the reaction [EPHB2 protein ...,32184358,2836600,"4-nitro-N-(2-phenylphenyl)-2,1,3-benzoxadiazol...",C1=CC=C(C=C1)C2=CC=CC=C2NC3=CC=C(C4=NON=C34)[N...,EPH receptor B2
...,...,...,...,...,...,...,...,...,...,...
1162289,ZSTK474,C510150,PIK3CB,protein,ZSTK474 analog results in decreased activity o...,21882832,11647372,4-[4-[2-(difluoromethyl)benzimidazol-1-yl]-6-m...,C1COCCN1C2=NC(=NC(=N2)N3C4=CC=CC=C4N=C3C(F)F)N...,"phosphatidylinositol-4,5-bisphosphate 3-kinase..."
1162290,ZSTK474,C510150,PIK3CB,protein,ZSTK474 results in decreased activity of PIK3C...,20129775,11647372,4-[4-[2-(difluoromethyl)benzimidazol-1-yl]-6-m...,C1COCCN1C2=NC(=NC(=N2)N3C4=CC=CC=C4N=C3C(F)F)N...,"phosphatidylinositol-4,5-bisphosphate 3-kinase..."
1162291,ZSTK474,C510150,PIK3CG,protein,ZSTK474 results in decreased activity of PIK3C...,20129775,11647372,4-[4-[2-(difluoromethyl)benzimidazol-1-yl]-6-m...,C1COCCN1C2=NC(=NC(=N2)N3C4=CC=CC=C4N=C3C(F)F)N...,"phosphatidylinositol-4,5-bisphosphate 3-kinase..."
1162292,ZSTK474,C510150,PRKDC,protein,ZSTK474 results in decreased activity of PRKDC...,20129775,11647372,4-[4-[2-(difluoromethyl)benzimidazol-1-yl]-6-m...,C1COCCN1C2=NC(=NC(=N2)N3C4=CC=CC=C4N=C3C(F)F)N...,"protein kinase, DNA-activated, catalytic subunit"
1162926,zymosterol,C015582,MSMO1,protein,MSMO1 protein results in decreased abundance o...,23125191,92746,"(3S,5S,10S,13R,14R,17R)-10,13-dimethyl-17-[(2R...",C[C@H](CCC=C(C)C)[C@H]1CC[C@@H]2[C@@]1(CCC3=C2...,methylsterol monooxygenase 1

In [20]:
Dis_Drug

,ChemicalName,Head_MESH,Tail,GeneForms,InteractionActions,PubMedIDs,Head,Head_detail_name,Head_SMILE_name,Tail_detail_name
0,10074-G5,C534883,AR,protein,10074-G5 inhibits the reaction [EPHB2 protein ...,32184358,2836600,"4-nitro-N-(2-phenylphenyl)-2,1,3-benzoxadiazol...",C1=CC=C(C=C1)C2=CC=CC=C2NC3=CC=C(C4=NON=C34)[N...,androgen receptor
1,10074-G5,C534883,AR,protein,10074-G5 results in decreased expression of AR...,32184358,2836600,"4-nitro-N-(2-phenylphenyl)-2,1,3-benzoxadiazol...",C1=CC=C(C=C1)C2=CC=CC=C2NC3=CC=C(C4=NON=C34)[N...,androgen receptor
2,10074-G5,C534883,AR,protein,10074-G5 results in decreased expression of AR...,32184358,2836600,"4-nitro-N-(2-phenylphenyl)-2,1,3-benzoxadiazol...",C1=CC=C(C=C1)C2=CC=CC=C2NC3=CC=C(C4=NON=C34)[N...,androgen receptor
3,10074-G5,C534883,EPHB2,protein,10074-G5 inhibits the reaction [EPHB2 protein ...,32184358,2836600,"4-nitro-N-(2-phenylphenyl)-2,1,3-benzoxadiazol...",C1=CC=C(C=C1)C2=CC=CC=C2NC3=CC=C(C4=NON=C34)[N...,EPH receptor B2
4,10074-G5,C534883,EPHB2,protein,10074-G5 inhibits the reaction [EPHB2 protein ...,32184358,2836600,"4-nitro-N-(2-phenylphenyl)-2,1,3-benzoxadiazol...",C1=CC=C(C=C1)C2=CC=CC=C2NC3=CC=C(C4=NON=C34)[N...,EPH receptor B2
...,...,...,...,...,...,...,...,...,...,...
1162289,ZSTK474,C510150,PIK3CB,protein,ZSTK474 analog results in decreased activity o...,21882832,11647372,4-[4-[2-(difluoromethyl)benzimidazol-1-yl]-6-m...,C1COCCN1C2=NC(=NC(=N2)N3C4=CC=CC=C4N=C3C(F)F)N...,"phosphatidylinositol-4,5-bisphosphate 3-kinase..."
1162290,ZSTK474,C510150,PIK3CB,protein,ZSTK474 results in decreased activity of PIK3C...,20129775,11647372,4-[4-[2-(difluoromethyl)benzimidazol-1-yl]-6-m...,C1COCCN1C2=NC(=NC(=N2)N3C4=CC=CC=C4N=C3C(F)F)N...,"phosphatidylinositol-4,5-bisphosphate 3-kinase..."
1162291,ZSTK474,C510150,PIK3CG,protein,ZSTK474 results in decreased activity of PIK3C...,20129775,11647372,4-[4-[2-(difluoromethyl)benzimidazol-1-yl]-6-m...,C1COCCN1C2=NC(=NC(=N2)N3C4=CC=CC=C4N=C3C(F)F)N...,"phosphatidylinositol-4,5-bisphosphate 3-kinase..."
1162292,ZSTK474,C510150,PRKDC,protein,ZSTK474 results in decreased activity of PRKDC...,20129775,11647372,4-[4-[2-(difluoromethyl)benzimidazol-1-yl]-6-m...,C1COCCN1C2=NC(=NC(=N2)N3C4=CC=CC=C4N=C3C(F)F)N...,"protein kinase, DNA-activated, catalytic subunit"
1162926,zymosterol,C015582,MSMO1,protein,MSMO1 protein results in decreased abundance o...,23125191,92746,"(3S,5S,10S,13R,14R,17R)-10,13-dimethyl-17-[(2R...",C[C@H](CCC=C(C)C)[C@H]1CC[C@@H]2[C@@]1(CCC3=C2...,methylsterol monooxygenase 1

In [21]:

# ── Add metadata columns ──────────────────────────────────────────────────────
Dis_Drug['Head_type']      = 'ChemicalEntity'
Dis_Drug['Tail_type']      = 'Gene'
Dis_Drug['Relation']       = 'ChemicalEntity_Gene'
Dis_Drug['Relation_Source'] = 'AgeAnno'
Dis_Drug['Head_ID_IS']     = 'Pubchem'
Dis_Drug['Tail_ID_IS']     = 'NCBI_ID'
Dis_Drug['Species']        = 'Homo sapiens'

# ── Select & reorder columns ──────────────────────────────────────────────────
desired_cols = [
    "Head", "Relation", "Tail", "Head_type", "Relation_type", "Tail_type",
    "KG_Source", "Head_UBERON_ID", "Head_GO_ID", "Head_HP_ID", "Head_Alias_mapped",
    "Head_detail_name", "Head_ENS", "Head_DO_name", "Head_DO_Alt_ids",
    "Tail_UBERON_ID", "Tail_Alias_mapped", "Tail_detail_name",
    "Head_SMILE_name", "Relation_Source", "Head_ID_IS", "Tail_ID_IS",
    "Tail_GO_ID", "Tail_ENS", "evidence", "InteractionActions", "PubMedIDs", "Species"
]

existing_cols = [col for col in desired_cols if col in Dis_Drug.columns]
Chem_Gene = Dis_Drug[existing_cols]

# ── Save ──────────────────────────────────────────────────────────────────────
Chem_Gene.to_csv(f'{OUT_PATH}ageanno_processed/AgeAnno_Chem_Gene.csv',
    index=False
)
print(f"Saved {len(Chem_Gene)} rows.")

Saved 382465 rows.

---
## Summary

This notebook produced two output files:

| Output File | Relation Type | Description |
|-------------|---------------|-------------|
| AgeAnno_Gene_Disease.csv | Gene_Disease | Gene-to-disease associations from AgeAnno |
| AgeAnno_Chem_Gene.csv | ChemicalEntity_Gene | Chemical-to-gene interactions from AgeAnno |

Both files follow the standardized EvoKG schema with Head/Relation/Tail triples and associated metadata.