# mirTARbase

In [2]:
import pandas as pd

In [3]:
BASE_PATH = "/storage/Arushi/090526_EvoAge/kg_formation/data_collection/"
OUT_PATH  = "/storage/Arushi/090526_EvoAge/kg_formation/processed_data/mirTARbase/"

In [4]:
drerio_ncbi = pd.read_csv(
    f'{BASE_PATH}databases_for_mapping/ncbi/Danio_rerio.gene_info',sep = '\t')
drerio_ncbi_id_name_dict = dict(zip(drerio_ncbi['Symbol'], drerio_ncbi['description']))
drerio_ncbi_id_name_dict

cele_ncbi = pd.read_csv(
    f'{BASE_PATH}databases_for_mapping/ncbi/Caenorhabditis_elegans.gene_info',sep = '\t')
cele_ncbi_id_name_dict = dict(zip(cele_ncbi['Symbol'], cele_ncbi['description']))
cele_ncbi_id_name_dict


drosophila_ncbi = pd.read_csv(
    f'{BASE_PATH}databases_for_mapping/ncbi/Drosophila_melanogaster.gene_info',sep = '\t')
drosophila_ncbi_id_name_dict = dict(zip(drosophila_ncbi['Symbol'], drosophila_ncbi['description']))
drosophila_ncbi_id_name_dict


human_ncbi = pd.read_csv(
    f'{BASE_PATH}databases_for_mapping/ncbi/Homo_sapiens.gene_info',sep = '\t')
human_ncbi_id_name_dict = dict(zip(human_ncbi['Symbol'], human_ncbi['description']))
human_ncbi_id_name_dict

mouse_ncbi = pd.read_csv(
    f'{BASE_PATH}databases_for_mapping/ncbi/Mus_musculus.gene_info',sep = '\t')
mouse_ncbi_id_name_dict = dict(zip(mouse_ncbi['Symbol'], mouse_ncbi['description']))
mouse_ncbi_id_name_dict

{'Pzp': 'PZP, alpha-2-macroglobulin like',
 'Aanat': 'arylalkylamine N-acetyltransferase',
 'Aatk': 'apoptosis-associated tyrosine kinase',
 'Abca1': 'ATP-binding cassette, sub-family A member 1',
 'Abca4': 'ATP-binding cassette, sub-family A member 4',
 'Abca2': 'ATP-binding cassette, sub-family A member 2',
 'Abcb7': 'ATP-binding cassette, sub-family B member 7',
 'Abcg1': 'ATP binding cassette subfamily G member 1',
 'Abi1': 'abl interactor 1',
 'Abl1': 'c-abl oncogene 1, non-receptor tyrosine kinase',
 'Abl2': 'ABL proto-oncogene 2, non-receptor tyrosine kinase',
 'Scgb1b27': 'secretoglobin, family 1B, member 27',
 'ac': 'absent corpus callosum',
 'Acadl': 'acyl-Coenzyme A dehydrogenase, long-chain',
 'Acadm': 'acyl-Coenzyme A dehydrogenase, medium chain',
 'Acadvl': 'acyl-Coenzyme A dehydrogenase, very long chain',
 'Acads': 'acyl-Coenzyme A dehydrogenase, short chain',
 'Slc33a1': 'solute carrier family 33 (acetyl-CoA transporter), member 1',
 'Asic2': 'acid-sensing ion channel 2',
 'Asic1': 'acid-sensing ion channel 1',
 'Ace': 'angiotensin I converting enzyme',
 'Ache': 'acetylcholinesterase',
 'Apoc4': 'apolipoprotein C-IV',
 'Macf1': 'microtubule-actin crosslinking factor 1',
 'Aco1': 'aconitase 1',
 'Aco2': 'aconitase 2, mitochondrial',
 'Acox1': 'acyl-Coenzyme A oxidase 1, palmitoyl',
 'Acp1': 'acid phosphatase 1, soluble',
 'Acp2': 'acid phosphatase 2, lysosomal',
 'Acp5': 'acid phosphatase 5, tartrate resistant',
 'Acr': 'acrosin prepropeptide',
 'Chrna1': 'cholinergic receptor nicotinic alpha 1 subunit',
 'Chrna4': 'cholinergic receptor, nicotinic, alpha polypeptide 4',
 'Chrna6': 'cholinergic receptor, nicotinic, alpha polypeptide 6',
 'Chrna7': 'cholinergic receptor, nicotinic, alpha polypeptide 7',
 'Chrnb1': 'cholinergic receptor nicotinic beta 1 subunit',
 'Chrnb2': 'cholinergic receptor nicotinic beta 2 subunit',
 'Chrnd': 'cholinergic receptor, nicotinic, delta polypeptide',
 'Chrne': 'cholinergic receptor, nicotinic, epsilon polypeptide',
 'Chrng': 'cholinergic receptor, nicotinic, gamma polypeptide',
 'Adipoq': 'adiponectin, C1Q and collagen domain containing',
 'Acrv1': 'acrosomal vesicle protein 1',
 'act': 'adult cataract',
 'Acta1': 'actin alpha 1, skeletal muscle',
 'Actb': 'actin, beta',
 'Actc1': 'actin, alpha, cardiac muscle 1',
 'Actg1': 'actin, gamma, cytoplasmic 1',
 'Actg2': 'actin, gamma 2, smooth muscle, enteric',
 'Actl7a': 'actin-like 7a',
 'Actl7b': 'actin-like 7b',
 'Actn2': 'actinin alpha 2',
 'Actn3': 'actinin alpha 3',
 'Acta2': 'actin alpha 2, smooth muscle, aorta',
 'Acvr1': 'activin A receptor, type 1',
 'Acvr1b': 'activin A receptor, type 1B',
 'Acvr2a': 'activin receptor IIA',
 'Acvr2b': 'activin receptor IIB',
 'Acvrl1': 'activin A receptor, type II-like 1',
 'Aspa': 'aspartoacylase',
 'Ada': 'adenosine deaminase',
 'Adam10': 'a disintegrin and metallopeptidase domain 10',
 'Adam11': 'a disintegrin and metallopeptidase domain 11',
 'Adam12': 'ADAM metallopeptidase domain 12',
 'Adam15': 'ADAM metallopeptidase domain 15',
 'Adam17': 'a disintegrin and metallopeptidase domain 17',
 'Adam19': 'ADAM metallopeptidase domain 19',
 'Adam2': 'a disintegrin and metallopeptidase domain 2',
 'Adam22': 'a disintegrin and metallopeptidase domain 22',
 'Adam3': 'ADAM metallopeptidase domain 3',
 'Adam4': 'a disintegrin and metallopeptidase domain 4',
 'Adam5': 'a disintegrin and metallopeptidase domain 5',
 'Adam7': 'a disintegrin and metallopeptidase domain 7',
 'Adam8': 'a disintegrin and metallopeptidase domain 8',
 'Adam9': 'ADAM metallopeptidase domain 9',
 'Adamts1': 'ADAM metallopeptidase with thrombospondin type 1 motif 1',
 'Adcy6': 'adenylate cyclase 6',
 'Adcy7': 'adenylate cyclase 7',
 'Adcy8': 'adenylate cyclase 8',
 'Adcy9': 'adenylate cyclase 9',
 'Adcyap1': 'adenylate cyclase activating polypeptide 1',
 'Adcyap1r1': 'adenylate cyclase activating polypeptide 1 receptor 1',
 'Add1': 'adducin 1',
 'Add2': 'adducin 2',
 'Plin2': 'perilipin 2',
 'Adh1': 'alcohol dehydrogenase 1 (class I)',
 'Adh7': 'alcohol dehydrogenase 7 (class IV), mu or sigma polypeptide',
 'Adh5': 'alcohol dehydrogenase 5 (class III), chi polypeptide',
 'Adh5-ps1': 'alcohol dehydrogenase 5 (class III), chi polypeptide, pseudogene 1',
 'Adk': 'adenosine kinase',
 'Adm': 'adrenomedullin',
 'Gpr182': 'G protein-coupled receptor 182',
 'Cfd': 'complement factor D',
 'Adnp': 'activity-dependent neuroprotective protein',
 'Adora1': 'adenosine A1 receptor',
 'Adora2a': 'adenosine A2a receptor',
 'Adora2b': 'adenosine A2b receptor',
 'Adora3': 'adenosine A3 receptor',
 'Adprh': 'ADP-ribosylarginine hydrolase',
 'Parp1': 'poly (ADP-ribose) polymerase family, member 1',
 'Parp2': 'poly (ADP-ribose) polymerase family, member 2',
 'Adra1b': 'adrenergic receptor, alpha 1b',
 'Adra1a': 'adrenergic receptor, alpha 1a',
 'Adra1d': 'adrenergic receptor, alpha 1d',
 'Adra2a': 'adrenergic receptor, alpha 2a',
 'Adra2b': 'adrenergic receptor, alpha 2b',
 'Adra2c': 'adrenergic receptor, alpha 2c',
 'Adrb1': 'adrenergic receptor, beta 1',
 'Adrb2': 'adrenergic receptor, beta 2',
 'Adrb3': 'adrenergic receptor, beta 3',
 'Adsl': 'adenylosuccinate lyase',
 'Adss1': 'adenylosuccinate synthase 1',
 'Adss2': 'adenylosuccinate synthase 2',
 'Avil': 'advillin',
 'Aebp1': 'AE binding protein 1',
 'Aebp2': 'AE binding protein 2',
 'Crisp1': 'cysteine-rich secretory protein 1',
 'Crisp3': 'cysteine-rich secretory protein 3',
 'Afp': 'alpha fetoprotein',
 'ag': 'agitans',
 'Aga': 'aspartylglucosaminidase',
 'Acan': 'aggrecan',
 'Ager': 'advanced glycosylation end product-specific receptor',
 'Angpt1': 'angiopoietin 1',
 'Angpt2': 'angiopoietin 2',
 'Angpt4': 'angiopoietin 4',
 'Agrn': 'agrin',
 'Agrp': 'agouti related neuropeptide',
 'Gla': 'galactosidase, alpha',
 'Agt': 'angiotensinogen',
 'Agtr1a': 'angiotensin II receptor, type 1a',
 'Agtr1b': 'angiotensin II receptor, type 1b',
 'Agtr2': 'angiotensin II receptor, type 2',
 'Agtrap': 'angiotensin II, type I receptor-associated protein',
 'Agxt': 'alanine-glyoxylate aminotransferase',
 'Nr0b1': 'nuclear receptor subfamily 0, group B, member 1',
 'Ahcyl': 'adenosylhomocysteinase like',
 'Ahr': 'aryl-hydrocarbon receptor',
 'Ahrr': 'aryl-hydrocarbon receptor repressor',
 'Ahsg': 'alpha-2-HS-glycoprotein',
 'Aicda': 'activation-induced cytidine deaminase',
 'Aif1': 'allograft inflammatory factor 1',
 'Crybg1': 'crystallin beta-gamma domain containing 1',
 'Aip': 'aryl-hydrocarbon receptor-interacting protein',
 'Aire': 'autoimmune regulator',
 'Ak1': 'adenylate kinase 1',
 'Ak2': 'adenylate kinase 2',
 'Ak4': 'adenylate kinase 4',
 'Akap1': 'A kinase anchor protein 1',
 'Akap3': 'A kinase anchor protein 3',
 'Akap4': 'A kinase anchor protein 4',
 'Alpl': 'alkaline phosphatase, liver/bone/kidney',
 'Akp3': 'alkaline phosphatase 3, intestine, not Mn requiring',
 'Alppl2': 'alkaline phosphatase, placental-like 2',
 'Akt1': 'thymoma viral proto-oncogene 1',
 'Akt2': 'thymoma viral proto-oncogene 2',
 'Alas1': 'aminolevulinic acid synthase 1',
 'Alas2': 'aminolevulinic acid synthase 2, erythroid',
 'Alb': 'albumin',
 'Alcam': 'activated leukocyte cell adhesion molecule',
 'Abcd1': 'ATP-binding cassette, sub-family D member 1',
 'Aldh1a1': 'aldehyde dehydrogenase family 1, subfamily A1',
 'Aldh2': 'aldehyde dehydrogenase 2, mitochondrial',
 'Aldh3a1': 'aldehyde dehydrogenase family 3, subfamily A1',
 'Aldh3a2': 'aldehyde dehydrogenase family 3, subfamily A2',
 'Aldoa': 'aldolase A, fructose-bisphosphate',
 'Aldoc': 'aldolase C, fructose-bisphosphate',
 'Akr1b1': 'aldo-keto reductase family 1 member B',
 'Alk': 'anaplastic lymphoma kinase',
 'Alox12': 'arachidonate 12-lipoxygenase',
 'Alox12e': 'arachidonate lipoxygenase, epidermal',
 'Alox12b': 'arachidonate 12-lipoxygenase, 12R type',
 'Alox15': 'arachidonate 15-lipoxygenase',
 'Alox8': 'arachidonate 8-lipoxygenase',
 'Alox5': 'arachidonate 5-lipoxygenase',
 'Alox5ap': 'arachidonate 5-lipoxygenase activating protein',
 'alp': 'alopecia, recessive',
 'Gfer': 'growth factor, augmenter of liver regeneration',
 'Alx3': 'aristaless-like homeobox 3',
 'Alx4': 'aristaless-like homeobox 4',
 'am': 'amputated',
 'Ambn': 'ameloblastin',
 'Ambp': 'alpha 1 microglobulin/bikunin precursor',
 'amd': 'autoimmune myocardial disease',
 'Amd-ps1': 'S-adenosylmethionine decarboxylase, pseudogene 1',
 'Amd1': 'S-adenosylmethionine decarboxylase 1',
 'Amelx': 'amelogenin, X-linked',
 'Amh': 'anti-Mullerian hormone',
 'Ampd3': 'adenosine monophosphate deaminase 3',
 'Mat1a': 'methionine adenosyltransferase 1A',
 'Amy1': 'amylase 1, salivary',
 'Ang': 'angiogenin, ribonuclease, RNase A family, 5',
 'Ang-ps1': 'angiogenin, ribonuclease A family, pseudogene 1',
 'Ang3': 'angiogenin, ribonuclease A family, member 3',
 'Ang2': 'angiogenin, ribonuclease A family, member 2',
 'Ank': 'progressive ankylosis',
 'Ank1': 'ankyrin 1, erythroid',
 'Ank3': 'ankyrin 3, epithelial',
 'Ankfy1': 'ankyrin repeat and FYVE domain containing 1',
 'Anp32a': 'acidic nuclear phosphoprotein 32 family member A',
 'Slc25a4': 'solute carrier family 25 (mitochondrial carrier, adenine nucleotide translocator), member 4',
 'Slc25a5': 'solute carrier family 25 (mitochondrial carrier, adenine nucleotide translocator), member 5',
 'anx': 'anorexia',
 'Anxa11': 'annexin A11',
 'Anxa3': 'annexin A3',
 'Anxa4': 'annexin A4',
 'Anxa5': 'annexin A5',
 'Anxa6': 'annexin A6',
 'Anxa7': 'annexin A7',
 'Anxa8': 'annexin A8',
 'ao': 'apampischo',
 'Aoc3': 'amine oxidase, copper containing 3',
 'Prdx3': 'peroxiredoxin 3',
 'Prdx6': 'peroxiredoxin 6',
 'Aox1': 'aldehyde oxidase 1',
 'ap': 'alopecia periodica',
 'Ap1b1': 'adaptor protein complex AP-1, beta 1 subunit',
 'Ap1g1': 'adaptor protein complex AP-1, gamma 1 subunit',
 'Ap1g2': 'adaptor protein complex AP-1, gamma 2 subunit',
 'Ap1m1': 'adaptor-related protein complex AP-1, mu subunit 1',
 'Ap1m2': 'adaptor protein complex AP-1, mu 2 subunit',
 'Ap1s1': 'adaptor protein complex AP-1, sigma 1',
 'Fabp4': 'fatty acid binding protein 4, adipocyte',
 'Ap2a1': 'adaptor-related protein complex 2, alpha 1 subunit',
 'Ap2a2': 'adaptor-related protein complex 2, alpha 2 subunit',
 'Ap2m1': 'adaptor-related protein complex 2, mu 1 subunit',
 'Ap3b1': 'adaptor-related protein complex 3, beta 1 subunit',
 'Ap3b2': 'adaptor-related protein complex 3, beta 2 subunit',
 'Ap3d1': 'adaptor-related protein complex 3, delta 1 subunit',
 'Ap3s1': 'adaptor-related protein complex 3, sigma 1 subunit',
 'Ap3s2': 'adaptor-related protein complex 3, sigma 2 subunit',
 'Ap4m1': 'adaptor-related protein complex AP-4, mu 1',
 'Ap4s1': 'adaptor-related protein complex AP-4, sigma 1',
 'Apaf1': 'apoptotic peptidase activating factor 1',
 'Apba2': 'amyloid beta precursor protein binding family A member 2',
 'Apbb1': 'amyloid beta precursor protein binding family B member 1',
 'Apbb2': 'amyloid beta precursor protein binding family B member 2',
 'Apc': 'APC, WNT signaling pathway regulator',
 'Speg': 'SPEG complex locus',
 'Apex1': 'apurinic/apyrimidinic endonuclease 1',
 'Atg5': 'autophagy related 5',
 'Birc3': 'baculoviral IAP repeat-containing 3',
 'Birc2': 'baculoviral IAP repeat-containing 2',
 'Xiap': 'X-linked inhibitor of apoptosis',
 'Birc5': 'baculoviral IAP repeat-containing 5',
 'Api5': 'apoptosis inhibitor 5',
 'Cd5l': 'CD5 antigen-like',
 'Aplp1': 'amyloid beta precursor like protein 1',
 'Aplp2': 'amyloid beta precursor-like protein 2',
 'Apoa1': 'apolipoprotein A-I',
 'Apoa2': 'apolipoprotein A-II',
 'Apoa4': 'apolipoprotein A-IV',
 'Apobec1': 'apolipoprotein B mRNA editing enzyme, catalytic polypeptide 1',
 'Apobec2': 'apolipoprotein B mRNA editing enzyme, catalytic polypeptide 2',
 'Apoc1': 'apolipoprotein C-I',
 'Apoc2': 'apolipoprotein C2',
 'Apoc3': 'apolipoprotein C-III',
 'Apod': 'apolipoprotein D',
 'Apoe': 'apolipoprotein E',
 'Apoh': 'apolipoprotein H',
 'Nr2f2': 'nuclear receptor subfamily 2, group F, member 2',
 'App': 'amyloid beta precursor protein',
 'Aprt': 'adenine phosphoribosyl transferase',
 'Aqp1': 'aquaporin 1',
 'Aqp2': 'aquaporin 2',
 'Aqp3': 'aquaporin 3',
 'Aqp4': 'aquaporin 4',
 'Aqp5': 'aquaporin 5',
 'Aqp6': 'aquaporin 6',
 'Aqp7': 'aquaporin 7',
 'Aqp8': 'aquaporin 8',
 'Aqr': 'aquarius',
 'Ar': 'androgen receptor',
 'Araf': 'Araf proto-oncogene, serine/threonine kinase',
 'Rplp0': 'ribosomal protein lateral stalk subunit P0',
 'Arc': 'activity regulated cytoskeletal-associated protein',
 'Areg': 'amphiregulin',
 'Arf1': 'ARF GTPase 1',
 'Arf2': 'ARF GTPase 2',
 'Arf3': 'ARF GTPase 3',
 'Arf4': 'ARF GTPase 4',
 'Arf5': 'ARF GTPase 5',
 'Arf6': 'ARF GTPase 6',
 'Arg1': 'arginase, liver',
 'Arg2': 'arginase type II',
 'Rhoa': 'ras homolog family member A',
 'Rhoay-ps1': 'ras homolog A translocated to the Y, pseudogene 1',
 'Rhoay-ps2': 'ras homolog A translocated to the Y, pseudogene 2',
 'Rhoay-ps3': 'ras homolog A translocated to the Y, pseudogene 3',
 'Rhob': 'ras homolog family member B',
 'Rhoc': 'ras homolog family member C',
 'Rhod': 'ras homolog family member D',
 'Arhgap5': 'Rho GTPase activating protein 5',
 'Arhgap6': 'Rho GTPase activating protein 6',
 'Arhgdib': 'Rho, GDP dissociation inhibitor beta',
 'Rnd2': 'Rho family GTPase 2',
 'Phox2a': 'paired-like homeobox 2a',
 'Arl4a': 'ADP-ribosylation factor-like 4A',
 'Arnt': 'aryl hydrocarbon receptor nuclear translocator',
 'Arnt2': 'aryl hydrocarbon receptor nuclear translocator 2',
 'Bmal1': 'basic helix-loop-helix ARNT like 1',
 'Arpc1b': 'actin related protein 2/3 complex, subunit 1B',
 'Art1': 'ADP-ribosyltransferase 1',
 'Art2a': 'ADP-ribosyltransferase 2a',
 'Art2b': 'ADP-ribosyltransferase 2b',
 'Art5': 'ADP-ribosyltransferase 5',
 'Artn': 'artemin',
 'Arvcf': 'armadillo repeat gene deleted in velocardiofacial syndrome',
 'Arx': 'aristaless related homeobox',
 'Arsb': 'arylsulfatase B',
 'Arsa': 'arylsulfatase A',
 'asa': 'anti-sarcolemmal autoantibodies',
 'Asah1': 'N-acylsphingosine amidohydrolase 1',
 'Asgr1': 'asialoglycoprotein receptor 1',
 'Asgr2': 'asialoglycoprotein receptor 2',
 'Rab27a': 'RAB27A, member RAS oncogene family',
 'Asp1': 'audiogenic seizure prone 1',
 'Asp2': 'audiogenic seizure prone 2',
 'Asp3': 'audiogenic seizure prone 3',
 'Ass1': 'argininosuccinate synthetase 1',
 'Astn1': 'astrotactin 1',
 'at': 'atrichosis',
 'Serpinc1': 'serine (or cysteine) peptidase inhibitor, clade C (antithrombin), member 1',
 'Zfhx3': 'zinc finger homeobox 3',
 'Ate1': 'arginyltransferase 1',
 'Atf1': 'activating transcription factor 1',
 'Atf2': 'activating transcription factor 2',
 'Atf3': 'activating transcription factor 3',
 'Atf4': 'activating transcription factor 4',
 'Atm': 'ataxia telangiectasia mutated',
 'Atoh1': 'atonal bHLH transcription factor 1',
 'Neurod6': 'neurogenic differentiation 6',
 'Neurod4': 'neurogenic differentiation 4',
 'Neurog2': 'neurogenin 2',
 'Neurog3': 'neurogenin 3',
 'Atox1': 'antioxidant 1 copper chaperone',
 'Atp1a1': 'ATPase, Na+/K+ transporting, alpha 1 polypeptide',
 'Atp1b1': 'ATPase, Na+/K+ transporting, beta 1 polypeptide',
 'Atp1b2': 'ATPase, Na+/K+ transporting, beta 2 polypeptide',
 'Atp1b3': 'ATPase, Na+/K+ transporting, beta 3 polypeptide',
 'Fxyd2': 'FXYD domain-containing ion transport regulator 2',
 'Atp2a1': 'ATPase, Ca++ transporting, cardiac muscle, fast twitch 1',
 'Atp2a2': 'ATPase, Ca++ transporting, cardiac muscle, slow twitch 2',
 'Atp2b2': 'ATPase, Ca++ transporting, plasma membrane 2',
 'Atp4a': 'ATPase, H+/K+ exchanging, gastric, alpha polypeptide',
 'Atp4b': 'ATPase, H+/K+ exchanging, beta polypeptide',
 'Atp5f1a': 'ATP synthase F1 subunit alpha',
 'Atp5f1b': 'ATP synthase F1 subunit beta',
 'Atp5f1c': 'ATP synthase F1 subunit gamma',
 'Atp5pb': 'ATP synthase peripheral stalk-membrane subunit b',
 'Atp5mc1': 'ATP synthase membrane subunit c locus 1',
 'Atp5pf': 'ATP synthase peripheral stalk subunit F6',
 'Atp5me': 'ATP synthase membrane subunit e',
 'Atp6v1a': 'ATPase, H+ transporting, lysosomal V1 subunit A',
 'Atp6v1b2': 'ATPase, H+ transporting, lysosomal V1 subunit B2',
 'Atp6v0d1': 'ATPase, H+ transporting, lysosomal V0 subunit D1',
 'Atp6v1e1': 'ATPase, H+ transporting, lysosomal V1 subunit E1',
 'Atp6v0e': 'ATPase, H+ transporting, lysosomal V0 subunit E',
 'Atp6v0a1': 'ATPase, H+ transporting, lysosomal V0 subunit A1',
 'Atp7a': 'ATPase, copper transporting, alpha polypeptide',
 'Atp7b': 'ATPase, copper transporting, beta polypeptide',
 'Atp8a1': 'ATPase phospholipid transporting 8A1',
 'Atp9a': 'ATPase, class II, type 9A',
 'Atp10a': 'ATPase, class V, type 10A',
 'Atp5if1': 'ATP synthase inhibitory factor subunit 1',
 'Atp6v0c': 'ATPase, H+ transporting, lysosomal V0 subunit C',
 'Slc7a1': 'solute carrier family 7 (cationic amino acid transporter, y+ system), member 1',
 'Slc7a2': 'solute carrier family 7 (cationic amino acid transporter, y+ system), member 2',
 'Slc7a3': 'solute carrier family 7 (cationic amino acid transporter, y+ system), member 3',
 'Atrn': 'attractin',
 'Hnrnpd': 'heterogeneous nuclear ribonucleoprotein D',
 'Auh': 'AU RNA binding protein/enoyl-coenzyme A hydratase',
 'Aup1': 'ancient ubiquitous protein 1',
 'Pcdh15': 'protocadherin 15',
 'Akr1b7': 'aldo-keto reductase family 1, member B7',
 'Avp': 'arginine vasopressin',
 'Avpr2': 'arginine vasopressin receptor 2',
 'awg': 'abnormal wobbly gait',
 'Axin1': 'axin 1',
 'Axin2': 'axin 2',
 'Azgp1': 'alpha-2-glycoprotein 1, zinc',
 'Cep131': 'centrosomal protein 131',
 'B2m': 'beta-2 microglobulin',
 'ba': 'bare',
 'Baat': 'bile acid-Coenzyme A: amino acid N-acyltransferase',
 'Bach1': 'BTB and CNC homology 1, basic leucine zipper transcription factor 1',
 'Bach2': 'BTB and CNC homology, basic leucine zipper transcription factor 2',
 'Bad': 'BCL2-associated agonist of cell death',
 'baf': 'b-associated fitness',
 'Bag1': 'BCL2-associated athanogene 1',
 'Bak1': 'BCL2-antagonist/killer 1',
 'Nkx3-2': 'NK3 homeobox 2',
 'Bard1': 'BRCA1 associated RING domain 1',
 'Barx1': 'BarH-like homeobox 1',
 'Barx2': 'BarH-like homeobox 2',
 'Bax': 'BCL2-associated X protein',
 'Bcl6b': 'B cell CLL/lymphoma 6, member B',
 'Bc1-ps1': 'brain cytoplasmic RNA 1, pseudogene 1',
 'Bcan': 'brevican',
 'Bcap29': 'B cell receptor associated protein 29',
 'Phb2': 'prohibitin 2',
 'Bcat1': 'branched chain aminotransferase 1, cytosolic',
 'Bcat2': 'branched chain aminotransferase 2, mitochondrial',
 'Bche': 'butyrylcholinesterase',
 'Bckdha': 'branched chain ketoacid dehydrogenase E1, alpha polypeptide',
 'Bckdhb': 'branched chain ketoacid dehydrogenase E1, beta polypeptide',
 'Bckdk': 'branched chain ketoacid dehydrogenase kinase',
 'Bcl10': 'B cell leukemia/lymphoma 10',
 'Bcl2': 'B cell leukemia/lymphoma 2',
 'Bcl2a1a': 'B cell leukemia/lymphoma 2 related protein A1a',
 'Bcl2a1b': 'B cell leukemia/lymphoma 2 related protein A1b',
 'Bcl2a1c': 'B cell leukemia/lymphoma 2 related protein A1c',
 'Bcl2a1d': 'B cell leukemia/lymphoma 2 related protein A1d',
 'Bcl2l1': 'BCL2-like 1',
 'Bcl2l10': 'Bcl2-like 10',
 'Bcl2l2': 'BCL2-like 2',
 'Bcl3': 'B cell leukemia/lymphoma 3',
 'Bcl6': 'B cell leukemia/lymphoma 6',
 'Bcl7b': 'B cell CLL/lymphoma 7B',
 'Bcl7c': 'B cell CLL/lymphoma 7C',
 'Opn1sw': 'opsin 1 (cone pigments), short-wave-sensitive (color blindness, tritan)',
 'bd': 'bradypneic',
 'Bdkrb1': 'bradykinin receptor, beta 1',
 'Bdkrb2': 'bradykinin receptor, beta 2',
 'Bdnf': 'brain derived neurotrophic factor',
 'Bemv1': 'B-26 envelope mouse retrovirus',
 'Ube2n-ps1': 'ubiquitin-conjugating enzyme E2N, pseudogene 1',
 'Bet1': 'Bet1 golgi vesicular membrane trafficking protein',
 'Bex2': 'brain expressed X-linked 2',
 'Bex3': 'brain expressed X-linked 3',
 'Bfsp1': 'beaded filament structural protein 1, in lens-CP94',
 'Glb1': 'galactosidase, beta 1',
 'Bglap3': 'bone gamma-carboxyglutamate protein 3',
 'Bglap': 'bone gamma carboxyglutamate protein',
 'Bglap2': 'bone gamma-carboxyglutamate protein 2',
 'Bgn': 'biglycan',
 'bh': 'brain hernia',
 'Bhmt': 'betaine-homocysteine methyltransferase',
 'Bicd1': 'BICD cargo adaptor 1',

In [5]:
drosophila = pd.read_csv(f'{BASE_PATH}mirTARbase/dme_MTI.csv')
drosophila

,miRTarBase ID,miRNA,Species (miRNA),Target Gene,Target Gene (Entrez ID),Species (Target Gene),Experiments,Support Type,References (PMID)
0,MIRT003740,dme-miR-9a-5p,dme,Bx,32846.0,dme,Luciferase reporter assay,Functional MTI,19162004.0
1,MIRT003740,dme-miR-9a-5p,dme,Bx,32846.0,dme,Luciferase reporter assay,Non-Functional MTI,19162004.0
2,MIRT002992,dme-miR-8-3p,dme,CG13060,39802.0,dme,Luciferase reporter assay,Functional MTI,17923093.0
3,MIRT002991,dme-miR-8-3p,dme,CG8420,41097.0,dme,Luciferase reporter assay,Functional MTI,17923093.0
4,MIRT003745,dme-miR-8-3p,dme,Cpr56F,37299.0,dme,Luciferase reporter assay,Functional MTI,17923093.0
...,...,...,...,...,...,...,...,...,...
282,MIRT736675,dme-miR-92a-3p,dme,Khc-73,36718.0,dme,Luciferase reporter assay//Immunohistochemistr...,Functional MTI,32737186.0
283,MIRT756367,dme-miR-310-3p,dme,imd,44339.0,dme,Luciferase reporter assay//qRT-PCR,Functional MTI,38790230.0
284,MIRT756368,dme-miR-311-3p,dme,imd,44339.0,dme,Luciferase reporter assay//qRT-PCR,Functional MTI,38790230.0
285,MIRT756369,dme-miR-312-3p,dme,imd,44339.0,dme,Luciferase reporter assay//qRT-PCR,Functional MTI,38790230.0
286,MIRT756370,dme-miR-313-3p,dme,imd,44339.0,dme,Luciferase reporter assay//qRT-PCR,Functional MTI,38790230.0

##  Drosophila file

In [7]:
drosophila = pd.read_csv(f'{BASE_PATH}mirTARbase/dme_MTI.csv')
drosophila
drosophilaKG = pd.DataFrame({
    'Head': drosophila['miRNA'],
    'Relation': 'Mirna_Gene',
    'Tail': drosophila['Target Gene'],
    'Head_Type': 'miRTarBase_ID',
    'Tail_Type': 'Gene',
    'KG_Source': 'miRTarBase',
    'Head_detail_name': drosophila['miRNA'],
    'Tail_detail_name': '',
    'Species': 'Drosophila melanogaster'
})
drosophilaKG = drosophilaKG[drosophilaKG['Head'] != '0']

drosophilaKG
drosophilaKG['Tail_detail_name'] = drosophilaKG['Tail'].map(drosophila_ncbi_id_name_dict)
drosophilaKG = drosophilaKG[~drosophilaKG['Tail_detail_name'].isna()]
drosophilaKG

,Head,Relation,Tail,Head_Type,Tail_Type,KG_Source,Head_detail_name,Tail_detail_name,Species
0,dme-miR-9a-5p,Mirna_Gene,Bx,miRTarBase_ID,Gene,miRTarBase,dme-miR-9a-5p,Beadex,Drosophila melanogaster
1,dme-miR-9a-5p,Mirna_Gene,Bx,miRTarBase_ID,Gene,miRTarBase,dme-miR-9a-5p,Beadex,Drosophila melanogaster
2,dme-miR-8-3p,Mirna_Gene,CG13060,miRTarBase_ID,Gene,miRTarBase,dme-miR-8-3p,uncharacterized protein,Drosophila melanogaster
3,dme-miR-8-3p,Mirna_Gene,CG8420,miRTarBase_ID,Gene,miRTarBase,dme-miR-8-3p,uncharacterized protein,Drosophila melanogaster
4,dme-miR-8-3p,Mirna_Gene,Cpr56F,miRTarBase_ID,Gene,miRTarBase,dme-miR-8-3p,Cuticular protein 56F,Drosophila melanogaster
...,...,...,...,...,...,...,...,...,...
282,dme-miR-92a-3p,Mirna_Gene,Khc-73,miRTarBase_ID,Gene,miRTarBase,dme-miR-92a-3p,Kinesin heavy chain 73,Drosophila melanogaster
283,dme-miR-310-3p,Mirna_Gene,imd,miRTarBase_ID,Gene,miRTarBase,dme-miR-310-3p,immune deficiency,Drosophila melanogaster
284,dme-miR-311-3p,Mirna_Gene,imd,miRTarBase_ID,Gene,miRTarBase,dme-miR-311-3p,immune deficiency,Drosophila melanogaster
285,dme-miR-312-3p,Mirna_Gene,imd,miRTarBase_ID,Gene,miRTarBase,dme-miR-312-3p,immune deficiency,Drosophila melanogaster
286,dme-miR-313-3p,Mirna_Gene,imd,miRTarBase_ID,Gene,miRTarBase,dme-miR-313-3p,immune deficiency,Drosophila melanogaster

In [8]:
drosophilaKG.to_csv(f'{OUT_PATH}dmel/miRTarBase_Mirna_Gene.csv',index = None)
del drosophilaKG

## Human file

In [9]:
human = pd.read_csv(f'{BASE_PATH}mirTARbase/hsa_MTI.csv')
human

humanKG = pd.DataFrame({
    'Head': human['miRNA'],
    'Relation': 'Mirna_Gene',
    'Tail': human['Target Gene'],
    'HeadType': 'miRTarBase_ID',
    'TailType': 'Gene',
    'KG_Source': 'miRTarBase',
    'Head_detail_name': human['miRNA'],
    'Tail_detail_name': '',
    'Species': 'Homo sapiens'
})
humanKG = humanKG[humanKG['Head'] != '0']
humanKG
humanKG['Tail_detail_name'] = humanKG['Tail'].map(human_ncbi_id_name_dict)
humanKG = humanKG[~humanKG['Head_detail_name'].isna()]
humanKG = humanKG[~humanKG['Tail_detail_name'].isna()]
humanKG = humanKG[humanKG['Head'].str.startswith('hsa', na=False)]
humanKG

,Head,Relation,Tail,HeadType,TailType,KG_Source,Head_detail_name,Tail_detail_name,Species
0,hsa-miR-122-5p,Mirna_Gene,SLC7A1,miRTarBase_ID,Gene,miRTarBase,hsa-miR-122-5p,solute carrier family 7 member 1,Homo sapiens
1,hsa-miR-122-5p,Mirna_Gene,SLC7A1,miRTarBase_ID,Gene,miRTarBase,hsa-miR-122-5p,solute carrier family 7 member 1,Homo sapiens
2,hsa-miR-122-5p,Mirna_Gene,SLC7A1,miRTarBase_ID,Gene,miRTarBase,hsa-miR-122-5p,solute carrier family 7 member 1,Homo sapiens
3,hsa-miR-122-5p,Mirna_Gene,SLC7A1,miRTarBase_ID,Gene,miRTarBase,hsa-miR-122-5p,solute carrier family 7 member 1,Homo sapiens
4,hsa-miR-122-5p,Mirna_Gene,SLC7A1,miRTarBase_ID,Gene,miRTarBase,hsa-miR-122-5p,solute carrier family 7 member 1,Homo sapiens
...,...,...,...,...,...,...,...,...,...
4004962,hsa-miR-549,Mirna_Gene,ZZZ3,miRTarBase_ID,Gene,miRTarBase,hsa-miR-549,zinc finger ZZ-type containing 3,Homo sapiens
4004963,hsa-miR-556-5p,Mirna_Gene,ZZZ3,miRTarBase_ID,Gene,miRTarBase,hsa-miR-556-5p,zinc finger ZZ-type containing 3,Homo sapiens
4004964,hsa-miR-558,Mirna_Gene,ZZZ3,miRTarBase_ID,Gene,miRTarBase,hsa-miR-558,zinc finger ZZ-type containing 3,Homo sapiens
4004965,hsa-miR-590-3p,Mirna_Gene,ZZZ3,miRTarBase_ID,Gene,miRTarBase,hsa-miR-590-3p,zinc finger ZZ-type containing 3,Homo sapiens
4004966,hsa-miR-664,Mirna_Gene,ZZZ3,miRTarBase_ID,Gene,miRTarBase,hsa-miR-664,zinc finger ZZ-type containing 3,Homo sapiens

In [10]:
humanKG.to_csv(f'{OUT_PATH}hsap/miRTarBase_Mirna_Gene.csv',index = None)

In [11]:
del humanKG

# Mouse file

In [12]:
mouse = pd.read_csv(f'{BASE_PATH}mirTARbase/mmu_MTI.csv')
mouse

mouseKG = pd.DataFrame({
    'Head': mouse['miRNA'],
    'Relation': 'Mirna_Gene',
    'Tail': mouse['Target Gene'],
    'HeadType': 'Mirna',
    'TailType': 'Gene',
    'KG_Source': 'miRTarBase',
    'Head_detail_name': mouse['miRNA'],
    'Tail_detail_name': '',
    'Species': 'Mus musculus'
})
mouseKG = mouseKG[mouseKG['Head'] != '0']
mouseKG
mouseKG['Tail_detail_name'] = mouseKG['Tail'].map(mouse_ncbi_id_name_dict)
mouseKG = mouseKG[~mouseKG['Head_detail_name'].isna()]
mouseKG = mouseKG[mouseKG['Head'].str.startswith('mmu', na=False)]
mouseKG = mouseKG[~mouseKG['Tail_detail_name'].isna()]
mouseKG

,Head,Relation,Tail,HeadType,TailType,KG_Source,Head_detail_name,Tail_detail_name,Species
0,mmu-miR-122-5p,Mirna_Gene,Cd320,Mirna,Gene,miRTarBase,mmu-miR-122-5p,CD320 antigen,Mus musculus
1,mmu-miR-122-5p,Mirna_Gene,Cd320,Mirna,Gene,miRTarBase,mmu-miR-122-5p,CD320 antigen,Mus musculus
2,mmu-miR-122-5p,Mirna_Gene,Ndrg3,Mirna,Gene,miRTarBase,mmu-miR-122-5p,N-myc downstream regulated gene 3,Mus musculus
3,mmu-miR-122-5p,Mirna_Gene,Ndrg3,Mirna,Gene,miRTarBase,mmu-miR-122-5p,N-myc downstream regulated gene 3,Mus musculus
4,mmu-miR-122-5p,Mirna_Gene,Ndrg3,Mirna,Gene,miRTarBase,mmu-miR-122-5p,N-myc downstream regulated gene 3,Mus musculus
...,...,...,...,...,...,...,...,...,...
664501,mmu-miR-125b-5p,Mirna_Gene,Tnfrsf1b,Mirna,Gene,miRTarBase,mmu-miR-125b-5p,"tumor necrosis factor receptor superfamily, me...",Mus musculus
664502,mmu-miR-351,Mirna_Gene,Tnfrsf1b,Mirna,Gene,miRTarBase,mmu-miR-351,"tumor necrosis factor receptor superfamily, me...",Mus musculus
664503,mmu-miR-670,Mirna_Gene,Tnfrsf1b,Mirna,Gene,miRTarBase,mmu-miR-670,"tumor necrosis factor receptor superfamily, me...",Mus musculus
664504,mmu-miR-3473c,Mirna_Gene,Tnrc6b,Mirna,Gene,miRTarBase,mmu-miR-3473c,trinucleotide repeat containing 6b,Mus musculus
664505,mmu-miR-3473c,Mirna_Gene,Zfp738,Mirna,Gene,miRTarBase,mmu-miR-3473c,zinc finger protein 738,Mus musculus

In [13]:
mouseKG.to_csv(f'{OUT_PATH}mmus/miRTarBase_Mirna_Gene.csv',index = None)

# Cele file

In [14]:
cele = pd.read_csv(f'{BASE_PATH}mirTARbase/cel_MTI.csv')
cele

celeKG = pd.DataFrame({
    'Head': cele['miRNA'],
    'Relation': 'Mirna_Gene',
    'Tail':cele['Target Gene'],
    'HeadType': 'Mirna',
    'TailType': 'Gene',
    'KG_Source': 'miRTarBase',
    'Head_detail_name': cele['miRNA'],
    'Tail_detail_name': '',
    'Species': 'Caenorhabditis elegans'
})

celeKG
celeKG = celeKG[celeKG['Head'] != '0']

celeKG['Tail_detail_name'] = celeKG['Tail'].map(cele_ncbi_id_name_dict)
celeKG = celeKG[~celeKG['Head_detail_name'].isna()]
celeKG = celeKG[~celeKG['Tail_detail_name'].isna()]
celeKG = celeKG[celeKG['Head'].str.startswith('cel', na=False)]
celeKG.to_csv(f'{OUT_PATH}cele/miRTarBase_Mirna_Gene.csv',index = None)
celeKG

,Head,Relation,Tail,HeadType,TailType,KG_Source,Head_detail_name,Tail_detail_name,Species
0,cel-lsy-6-3p,Mirna_Gene,cog-1,Mirna,Gene,miRTarBase,cel-lsy-6-3p,Homeobox domain-containing protein,Caenorhabditis elegans
1,cel-let-7-5p,Mirna_Gene,lin-41,Mirna,Gene,miRTarBase,cel-let-7-5p,Protein lin-41,Caenorhabditis elegans
4,cel-let-7-5p,Mirna_Gene,lin-14,Mirna,Gene,miRTarBase,cel-let-7-5p,Protein lin-14,Caenorhabditis elegans
5,cel-lin-4-5p,Mirna_Gene,lin-28,Mirna,Gene,miRTarBase,cel-lin-4-5p,Protein lin-28,Caenorhabditis elegans
6,cel-lsy-6-3p,Mirna_Gene,cog-1,Mirna,Gene,miRTarBase,cel-lsy-6-3p,Homeobox domain-containing protein,Caenorhabditis elegans
...,...,...,...,...,...,...,...,...,...
249,cel-miR-35-3p,Mirna_Gene,gld-1,Mirna,Gene,miRTarBase,cel-miR-35-3p,Female germline-specific tumor suppressor gld-1,Caenorhabditis elegans
250,cel-let-7-5p,Mirna_Gene,ncl-1,Mirna,Gene,miRTarBase,cel-let-7-5p,B box-type domain-containing protein;B-box typ...,Caenorhabditis elegans
251,cel-let-7-5p,Mirna_Gene,ncl-1,Mirna,Gene,miRTarBase,cel-let-7-5p,B box-type domain-containing protein;B-box typ...,Caenorhabditis elegans
252,cel-miR-1-3p,Mirna_Gene,mef-2,Mirna,Gene,miRTarBase,cel-miR-1-3p,MEF2 transcription factor homolog,Caenorhabditis elegans
253,cel-miR-243-3p,Mirna_Gene,daf-16,Mirna,Gene,miRTarBase,cel-miR-243-3p,Forkhead box protein O,Caenorhabditis elegans

In [15]:
celeKG.to_csv(f'{OUT_PATH}cele/miRTarBase_Mirna_Gene.csv',index = None)

## D rereio file

In [16]:
drer = pd.read_csv(f'{BASE_PATH}mirTARbase/dre_MTI.csv')
drer

drerKG = pd.DataFrame({
    'Head': drer['miRNA'],
    'Relation': 'Mirna_Gene',
    'Tail':drer['Target Gene'],
    'HeadType': 'Mirna',
    'TailType': 'Gene',
    'KG_Source': 'miRTarBase',
    'Head_detail_name': drer['miRNA'],
    'Tail_detail_name': '',
    'Species': 'Denio rerio'
})

drerKG = drerKG[drerKG['Head'] != '0']
drerKG['Tail_detail_name'] = drerKG['Tail'].map(drerio_ncbi_id_name_dict)
drerKG = drerKG[~drerKG['Head_detail_name'].isna()]
drerKG = drerKG[~drerKG['Tail_detail_name'].isna()]
drerKG = drerKG[drerKG['Head'].str.startswith('dre', na=False)]
drerKG.to_csv(f'{OUT_PATH}drer/miRTarBase_Mirna_Gene.csv',index = None)
drerKG

,Head,Relation,Tail,HeadType,TailType,KG_Source,Head_detail_name,Tail_detail_name,Species
0,dre-miR-196b,Mirna_Gene,hoxb8a,Mirna,Gene,miRTarBase,dre-miR-196b,homeobox B8a,Denio rerio
1,dre-miR-126a-3p,Mirna_Gene,spred1,Mirna,Gene,miRTarBase,dre-miR-126a-3p,sprouty related EVH1 domain containing 1,Denio rerio
2,dre-miR-126a-3p,Mirna_Gene,pik3r2,Mirna,Gene,miRTarBase,dre-miR-126a-3p,"phosphoinositide-3-kinase, regulatory subunit ...",Denio rerio
4,dre-miR-214,Mirna_Gene,disp2,Mirna,Gene,miRTarBase,dre-miR-214,dispatched RND transporter family member 2,Denio rerio
5,dre-miR-214,Mirna_Gene,disp2,Mirna,Gene,miRTarBase,dre-miR-214,dispatched RND transporter family member 2,Denio rerio
...,...,...,...,...,...,...,...,...,...
204,dre-miR-140-5p,Mirna_Gene,prkaa2,Mirna,Gene,miRTarBase,dre-miR-140-5p,"protein kinase, AMP-activated, alpha 2 catalyt...",Denio rerio
207,dre-miR-126a-3p,Mirna_Gene,cxcl12a,Mirna,Gene,miRTarBase,dre-miR-126a-3p,chemokine (C-X-C motif) ligand 12a (stromal ce...,Denio rerio
208,dre-miR-126a-3p,Mirna_Gene,cxcl12a,Mirna,Gene,miRTarBase,dre-miR-126a-3p,chemokine (C-X-C motif) ligand 12a (stromal ce...,Denio rerio
209,dre-miR-202-5p,Mirna_Gene,cdc42se1,Mirna,Gene,miRTarBase,dre-miR-202-5p,CDC42 small effector 1,Denio rerio
210,dre-miR-146a,Mirna_Gene,traf6,Mirna,Gene,miRTarBase,dre-miR-146a,TNF receptor-associated factor 6,Denio rerio

In [17]:
drerKG.to_csv(f'{OUT_PATH}drer/miRTarBase_Mirna_Gene.csv',index = None)