In [25]:
import pandas as pd
import numpy as np

In [ ]:
BASE_PATH = "/storage/Arushi/090526_EvoAge/kg_formation/data_collection/"
OUT_PATH = "/storage/Arushi/090526_EvoAge/kg_formation/processed_data/stitch"

In [27]:
## Pubchem_2_name 

Pubchem = pd.read_pickle(f'{BASE_PATH}databases_for_mapping/pubchem/combined_df.pkl')
Pubchem.head()

# Pubchem


# Pubchem[Pubchem['PUBCHEM_IUPAC_NAME']== '(4S)-1-methyl-4-prop-1-en-2-ylcyclohexene']

Pubchem_CID_Smile_Dict  = dict(zip(Pubchem['PUBCHEM_COMPOUND_CID'], Pubchem['PUBCHEM_SMILES']))
Pubchem_CID_Smile_Dict

Pubchem_IUPAC_CID_Dict  = dict(zip(Pubchem['PUBCHEM_COMPOUND_CID'], Pubchem['PUBCHEM_IUPAC_NAME']))
# Pubchem_IUPAC_CID_Dict  Pubchem_CID_Smile_Dict

# del Pubchem

In [39]:
#

# CHEMICAL_Chemical

In [40]:
yeast_Chemical_Chemical_path = f'{BASE_PATH}stitch/scer/chemical_chemical.links.v5.0.tsv'

Y_C_C = pd.read_csv(yeast_Chemical_Chemical_path, sep = '\t')

Y_C_C = Y_C_C.rename(columns={
    'chemical1': 'head',
    'chemical2': 'tail'
})

def clean_chemical_id(chem_id):
    return chem_id.lstrip('CIDs').lstrip('CIDm').lstrip('0')

# Apply the function to chemical1 and chemical2 columns only
Y_C_C[['head']] = Y_C_C[['head']].applymap(clean_chemical_id)
Y_C_C[['tail']] = Y_C_C[['tail']].applymap(clean_chemical_id)


Y_C_C['relation'] = 'ChemicalEntity_ChemicalEntity'
Y_C_C['head_type'] = 'ChemicalEntity'
Y_C_C['tail_type'] = 'ChemicalEntity'
Y_C_C['relation_type'] = np.nan

Y_C_C['head_detail_name'] = Y_C_C['head'].map(Pubchem_IUPAC_CID_Dict)
Y_C_C['tail_detail_name'] = Y_C_C['tail'].map(Pubchem_IUPAC_CID_Dict)
Y_C_C['head_smile_name'] = Y_C_C['head'].map(Pubchem_CID_Smile_Dict)
Y_C_C['tail_smile_name'] = Y_C_C['tail'].map(Pubchem_CID_Smile_Dict)
Y_C_C['head_id_is'] = 'Pubchem'
Y_C_C['tail_id_is'] = 'Pubchem'
Y_C_C['species'] = 'S.cerevisae'

Y_C_C

/tmp/ipykernel_1667789/1171471698.py:14: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  Y_C_C[['head']] = Y_C_C[['head']].applymap(clean_chemical_id)
/tmp/ipykernel_1667789/1171471698.py:15: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  Y_C_C[['tail']] = Y_C_C[['tail']].applymap(clean_chemical_id)

,head,tail,textmining,relation,head_type,tail_type,relation_type,head_detail_name,tail_detail_name,head_smile_name,tail_smile_name,head_id_is,tail_id_is,species
0,24759,24759,0,ChemicalEntity_ChemicalEntity,ChemicalEntity,ChemicalEntity,NaN,"(2S,3S,4S,5R,6R)-6-[(2S,3R,5S,6R)-3-acetamido-...","(2S,3S,4S,5R,6R)-6-[(2S,3R,5S,6R)-3-acetamido-...",CC(=O)N[C@H]1[C@@H](O[C@@H]([C@H](C1O[C@H]2[C@...,CC(=O)N[C@H]1[C@@H](O[C@@H]([C@H](C1O[C@H]2[C@...,Pubchem,Pubchem,S.cerevisae
1,91758695,107694,230,ChemicalEntity_ChemicalEntity,ChemicalEntity,ChemicalEntity,NaN,"(3Z,8R,9S,10R,13S,14S,17R)-13-ethyl-17-ethynyl...","[(1S,2S,5R,11R,12S,15R,16S)-15-acetyl-9-chloro...",CC[C@]12CC[C@H]3[C@H]([C@@H]1CC[C@]2(C#C)O)CCC...,CC(=O)[C@]1(CC[C@@H]2[C@@]1(CC[C@H]3[C@H]2C=C(...,Pubchem,Pubchem,S.cerevisae
2,91758695,11013287,230,ChemicalEntity_ChemicalEntity,ChemicalEntity,ChemicalEntity,NaN,"(3Z,8R,9S,10R,13S,14S,17R)-13-ethyl-17-ethynyl...","(3S,4S,5R,6R)-6-(hydroxymethyl)-4-[(2R,3S,4S,5...",CC[C@]12CC[C@H]3[C@H]([C@@H]1CC[C@]2(C#C)O)CCC...,C([C@@H]1[C@H]([C@@H]([C@@H]([C@H](O1)O[C@H]2[...,Pubchem,Pubchem,S.cerevisae
3,91758695,11980957,328,ChemicalEntity_ChemicalEntity,ChemicalEntity,ChemicalEntity,NaN,"(3Z,8R,9S,10R,13S,14S,17R)-13-ethyl-17-ethynyl...","N-[5-[[2-(2,6-dimethylphenoxy)acetyl]amino]-4-...",CC[C@]12CC[C@H]3[C@H]([C@@H]1CC[C@]2(C#C)O)CCC...,CC1=C(C(=CC=C1)C)OCC(=O)NC(CC2=CC=CC=C2)C(CC(C...,Pubchem,Pubchem,S.cerevisae
4,91758695,13078,162,ChemicalEntity_ChemicalEntity,ChemicalEntity,ChemicalEntity,NaN,"(3Z,8R,9S,10R,13S,14S,17R)-13-ethyl-17-ethynyl...",1-chloro-4-[chloro-(4-chlorophenyl)methyl]benzene,CC[C@]12CC[C@H]3[C@H]([C@@H]1CC[C@]2(C#C)O)CCC...,C1=CC(=CC=C1C(C2=CC=C(C=C2)Cl)Cl)Cl,Pubchem,Pubchem,S.cerevisae
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17705813,1,87081431,173,ChemicalEntity_ChemicalEntity,ChemicalEntity,ChemicalEntity,NaN,3-acetyloxy-4-(trimethylazaniumyl)butanoate,3-(4-hydroxy-3-methylbutanoyl)oxy-4-(trimethyl...,CC(=O)OC(CC(=O)[O-])C[N+](C)(C)C,CC(CC(=O)OC(CC(=O)[O-])C[N+](C)(C)C)CO,Pubchem,Pubchem,S.cerevisae
17705814,1,90857042,218,ChemicalEntity_ChemicalEntity,ChemicalEntity,ChemicalEntity,NaN,3-acetyloxy-4-(trimethylazaniumyl)butanoate,2-hydroxy-2-(3-methyl-2-piperidin-1-ylphenyl)-...,CC(=O)OC(CC(=O)[O-])C[N+](C)(C)C,CC1=C(C(=CC=C1)C(C2=CC=CC=C2)(C(=O)O)O)N3CCCCC3,Pubchem,Pubchem,S.cerevisae
17705815,1,91056687,294,ChemicalEntity_ChemicalEntity,ChemicalEntity,ChemicalEntity,NaN,3-acetyloxy-4-(trimethylazaniumyl)butanoate,"[3-carboxy-2-[1,1-difluoro-2-oxo-2-(2,3,4-trif...",CC(=O)OC(CC(=O)[O-])C[N+](C)(C)C,C[N+](C)(C)CC(CC(=O)O)OC(C(=O)C1=C(C(=C(C=C1)F...,Pubchem,Pubchem,S.cerevisae
17705816,1,91213096,357,ChemicalEntity_ChemicalEntity,ChemicalEntity,ChemicalEntity,NaN,3-acetyloxy-4-(trimethylazaniumyl)butanoate,"[1,1-difluoro-2-oxo-2-(2,3,4-trifluorophenyl)e...",CC(=O)OC(CC(=O)[O-])C[N+](C)(C)C,C1=CC(=C(C(=C1C(=O)C(OS(=O)(=O)C(F)(F)F)(F)F)F...,Pubchem,Pubchem,S.cerevisae
17705817,24759,24759,0,ChemicalEntity_ChemicalEntity,ChemicalEntity,ChemicalEntity,NaN,"(2S,3S,4S,5R,6R)-6-[(2S,3R,5S,6R)-3-acetamido-...","(2S,3S,4S,5R,6R)-6-[(2S,3R,5S,6R)-3-acetamido-...",CC(=O)N[C@H]1[C@@H](O[C@@H]([C@H](C1O[C@H]2[C@...,CC(=O)N[C@H]1[C@@H](O[C@@H]([C@H](C1O[C@H]2[C@...,Pubchem,Pubchem,S.cerevisae

In [41]:
Y_C_C['kg_source'] = 'STITCH'

In [42]:
final_df = Y_C_C

In [43]:
set(final_df['species']), set(final_df['relation']),set(final_df['head_type']),set(final_df['tail_type']),set(final_df['kg_source']),set(final_df['head_id_is']),set(final_df['tail_id_is'])

({'S.cerevisae'},
 {'ChemicalEntity_ChemicalEntity'},
 {'ChemicalEntity'},
 {'ChemicalEntity'},
 {'STITCH'},
 {'Pubchem'},
 {'Pubchem'})

In [44]:
# set(final_df['relation_type'])

In [45]:
# Count true NaN values
true_nan_count = final_df.isna().sum()

# Count string 'NAN' values (case-insensitive)
string_nan_count = final_df.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

# Combine both counts
nan_summary = pd.DataFrame({
    'NaN_count': true_nan_count,
    "'NAN'_string_count": string_nan_count,
    'Total_NaN_like': true_nan_count + string_nan_count
})
nan_summary

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
tail                      0                   0               0
textmining                0                   0               0
relation                  0                   0               0
head_type                 0                   0               0
tail_type                 0                   0               0
relation_type      17705818            17705818        35411636
head_detail_name     548083              548083         1096166
tail_detail_name     548083              548083         1096166
head_smile_name      548083              548083         1096166
tail_smile_name      548083              548083         1096166
head_id_is                0                   0               0
tail_id_is                0                   0               0
species                   0                   0               0
kg_source                 0                   0               0

In [46]:
# First, concatenate all dataframes as before (assuming `final_df` already exists from earlier step)

# Group by the 3 key columns
group_cols = ['head', 'relation', 'tail']

# For kg_source, combine with '::'
def merge_sources(x):
    return '::'.join(sorted(set(x.dropna())))

# Merge duplicates
final_df_dedup = final_df.groupby(group_cols, as_index=False).agg({
    'head_type': 'first',
    'relation_type': 'first',
    'tail_type': 'first',
    'kg_source': merge_sources,
    'head_id_is': 'first',
    'tail_id_is': 'first',
    'head_detail_name': 'first',
    'tail_detail_name': 'first',
    'head_smile_name': 'first',
    'tail_smile_name': 'first',
    'species': 'first'
})
final_df_dedup

,head,relation,tail,head_type,relation_type,tail_type,kg_source,head_id_is,tail_id_is,head_detail_name,tail_detail_name,head_smile_name,tail_smile_name,species
0,1,ChemicalEntity_ChemicalEntity,1003,ChemicalEntity,NaN,ChemicalEntity,STITCH,Pubchem,Pubchem,3-acetyloxy-4-(trimethylazaniumyl)butanoate,dihydrogen phosphate,CC(=O)OC(CC(=O)[O-])C[N+](C)(C)C,OP(=O)(O)[O-],S.cerevisae
1,1,ChemicalEntity_ChemicalEntity,1005,ChemicalEntity,NaN,ChemicalEntity,STITCH,Pubchem,Pubchem,3-acetyloxy-4-(trimethylazaniumyl)butanoate,2-phosphonooxyprop-2-enoic acid,CC(=O)OC(CC(=O)[O-])C[N+](C)(C)C,C=C(C(=O)O)OP(=O)(O)O,S.cerevisae
2,1,ChemicalEntity_ChemicalEntity,10177002,ChemicalEntity,NaN,ChemicalEntity,STITCH,Pubchem,Pubchem,3-acetyloxy-4-(trimethylazaniumyl)butanoate,3-(2-methylpropanoyloxy)-4-(trimethylazaniumyl...,CC(=O)OC(CC(=O)[O-])C[N+](C)(C)C,CC(C)C(=O)OC(CC(=O)[O-])C[N+](C)(C)C,S.cerevisae
3,1,ChemicalEntity_ChemicalEntity,101775,ChemicalEntity,NaN,ChemicalEntity,STITCH,Pubchem,Pubchem,3-acetyloxy-4-(trimethylazaniumyl)butanoate,"(6R,8S,9S,10R,13R,14S,17R)-6-hydroxy-10,13-dim...",CC(=O)OC(CC(=O)[O-])C[N+](C)(C)C,C[C@H](CCCC(C)C)[C@H]1CC[C@@H]2[C@@]1(CC[C@H]3...,S.cerevisae
4,1,ChemicalEntity_ChemicalEntity,101934,ChemicalEntity,NaN,ChemicalEntity,STITCH,Pubchem,Pubchem,3-acetyloxy-4-(trimethylazaniumyl)butanoate,"(8S,9S,10R,13R,14S,17R)-10,13-dimethyl-17-[(2R...",CC(=O)OC(CC(=O)[O-])C[N+](C)(C)C,C[C@H](CCCC(C)C)[C@H]1CC[C@@H]2[C@@]1(CC[C@H]3...,S.cerevisae
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12501701,9999862,ChemicalEntity_ChemicalEntity,10457858,ChemicalEntity,NaN,ChemicalEntity,STITCH,Pubchem,Pubchem,"(4S,4bS,8S,10aR)-8a-(bromomethyl)-4-hydroxy-4,...","(1S,3S,4aS,4bS,5S,8R,8aS,10aS)-1-bromo-8a-(bro...",CC(C)[C@@H]1CC=C[C@@H]2C1(CC[C@]3(C2[C@](C(=O)...,CC(C)[C@@H]1C=C[C@@H]([C@@H]2[C@@]1(CC[C@]3([C...,S.cerevisae
12501702,9999862,ChemicalEntity_ChemicalEntity,11123637,ChemicalEntity,NaN,ChemicalEntity,STITCH,Pubchem,Pubchem,"(4S,4bS,8S,10aR)-8a-(bromomethyl)-4-hydroxy-4,...","(1R,4aS,4bS,5S,6S,8S,8aS,10aS)-8-bromo-10a-(br...",CC(C)[C@@H]1CC=C[C@@H]2C1(CC[C@]3(C2[C@](C(=O)...,CC(C)[C@@H]1C=CC(=O)[C@@H]2[C@@]1(CC[C@]3([C@H...,S.cerevisae
12501703,9999862,ChemicalEntity_ChemicalEntity,2719,ChemicalEntity,NaN,ChemicalEntity,STITCH,Pubchem,Pubchem,"(4S,4bS,8S,10aR)-8a-(bromomethyl)-4-hydroxy-4,...","4-N-(7-chloroquinolin-4-yl)-1-N,1-N-diethylpen...",CC(C)[C@@H]1CC=C[C@@H]2C1(CC[C@]3(C2[C@](C(=O)...,CCN(CC)CCCC(C)NC1=C2C=CC(=CC2=NC=C1)Cl,S.cerevisae
12501704,9999951,ChemicalEntity_ChemicalEntity,10453329,ChemicalEntity,NaN,ChemicalEntity,STITCH,Pubchem,Pubchem,"3,5,7-trihydroxy-2-(4-octylphenyl)chromen-4-one","3,5,7-trihydroxy-2-(4-iodophenyl)chromen-4-one",CCCCCCCCC1=CC=C(C=C1)C2=C(C(=O)C3=C(C=C(C=C3O2...,C1=CC(=CC=C1C2=C(C(=O)C3=C(C=C(C=C3O2)O)O)O)I,S.cerevisae
12501705,9999951,ChemicalEntity_ChemicalEntity,5281616,ChemicalEntity,NaN,ChemicalEntity,STITCH,Pubchem,Pubchem,"3,5,7-trihydroxy-2-(4-octylphenyl)chromen-4-one","3,5,7-trihydroxy-2-phenylchromen-4-one",CCCCCCCCC1=CC=C(C=C1)C2=C(C(=O)C3=C(C=C(C=C3O2...,C1=CC=C(C=C1)C2=C(C(=O)C3=C(C=C(C=C3O2)O)O)O,S.cerevisae

In [47]:
final_df_dedup.to_csv(f'{OUT_PATH}stitch_YEAST_CHEMICALENTITY_CHEMICALENTITY.csv',index = None)

NameError: name 'OUT_PATH' is not defined