In [1]:
import pandas as pd
import numpy as np

In [3]:
BASE_PATH = "/storage/Arushi/090526_EvoAge/kg_formation/data_collection/"
OUT_PATH = "/storage/Arushi/090526_EvoAge/kg_formation/processed_data/string"

# NCBI GENE

In [3]:
NCBI_Yeast_gene = pd.read_csv(f'{BASE_PATH}databases_for_mapping/ncbi/Saccharomyces_cerevisiae.gene_info',sep = '\t')
NCBI_Yeast_gene

NCBI_Yeast_gene_Locus_2_GeneSymd_ict = dict(zip(NCBI_Yeast_gene['LocusTag'], NCBI_Yeast_gene['Symbol']))
NCBI_Yeast_gene_Locus_2_GeneSymd_ict
NCBI_Yeast_Locustag_Descrip_dict = dict(zip(NCBI_Yeast_gene['LocusTag'], NCBI_Yeast_gene['description']))
NCBI_Yeast_Locustag_Descrip_dict

{'-': 'Record to support submission of GeneRIFs for a gene not in Gene.',
 'ACI60_gp06': 'Atp6',
 'ACI60_gt03': 'tRNA-Glu',
 'ACI60_gt04': 'tRNA-Ser',
 'ACI60_gr01': 'large subunit ribosomal RNA',
 'ACI60_gt21': 'tRNA-Phe',
 'ACI60_gt24': 'tRNA-Met',
 'ACI60_gp04': 'Atp9',
 'ACI60_gp07': 'Atp8',
 'ACI60_gr02': 'small subunit ribosomal RNA',
 'ACI60_gt02': 'tRNA-Trp',
 'ACI60_gp08': 'cytochrome c oxidase subunit 1',
 'ACI60_gp05': 'cytochrome b',
 'ACI60_gp03': 'ribosomal protein S3',
 'ACI60_gt05': 'tRNA-Thr',
 'ACI60_gt06': 'tRNA-Cys',
 'ACI60_gt07': 'tRNA-His',
 'ACI60_gt08': 'tRNA-Leu',
 'ACI60_gt09': 'tRNA-Gln',
 'ACI60_gt10': 'tRNA-Lys',
 'ACI60_gt11': 'tRNA-Arg',
 'ACI60_gt12': 'tRNA-Gly',
 'ACI60_gt13': 'tRNA-Asp',
 'ACI60_gt14': 'tRNA-Ser',
 'ACI60_gt15': 'tRNA-Arg',
 'ACI60_gt16': 'tRNA-Ala',
 'ACI60_gt17': 'tRNA-Ile',
 'ACI60_gt18': 'tRNA-Tyr',
 'ACI60_gt19': 'tRNA-Asn',
 'ACI60_gt20': 'tRNA-Met',
 'ACI60_gp02': 'cytchrome c oxidase sububnit 2',
 'ACI60_gt22': 'tRNA-Thr',
 'ACI60_gt23': 'tRNA-Val',
 'ACI60_gp01': 'cytchrome c oxidase sububnit 3',
 'ACI60_gs01': 'ncRNA',
 'ACI60_gt01': 'tRNA-Pro',
 'YCL075W': 'pseudo',
 'YCL074W': 'pseudo',
 'YCL073C': 'glutathione exchanger',
 'YCL069W': 'basic amino acid transporter',
 'YCL068C': 'uncharacterized protein',
 'YCL067C': 'homeodomain mating type protein alpha2',
 'YCL066W': 'transcriptional co-activator mating type protein alpha',
 'YCL064C': 'L-serine/L-threonine ammonia-lyase CHA1',
 'YCL063W': 'Vac17p',
 'YCL061C': 'chromatin-modulating protein MRC1',
 'YCL059C': 'ribosome biosynthesis protein KRR1',
 'YCL058C': 'Fyv5p',
 'YCL057C-A': 'Mic10p',
 'YCL057W': 'metalloendopeptidase',
 'YCL056C': 'Pex34p',
 'YCL055W': 'Kar4p',
 'YCL054W': "27S pre-rRNA (guanosine2922-2'-O)-methyltransferase",
 'YCL052C': 'Pbn1p',
 'YCL051W': 'Lre1p',
 'YCL050C': 'bifunctional AP-4-A phosphorylase/ADP sulfurylase',
 'YCL049C': 'uncharacterized protein',
 'YCL048W': 'Sps22p',
 'YCL047C': 'nicotinamide-nucleotide adenylyltransferase',
 'YCL045C': 'Emc1p',
 'YCL044C': 'Mgr1p',
 'YCL043C': 'protein disulfide isomerase PDI1',
 'YCL042W': 'uncharacterized protein',
 'YCL040W': 'glucokinase',
 'YCL039W': 'glucose-induced degradation complex subunit GID7',
 'YCL038C': 'Atg22p',
 'YCL037C': 'Sro9p',
 'YCL036W': 'Gfd2p',
 'YCL035C': 'dithiol glutaredoxin GRX1',
 'YCL034W': 'Lsb5p',
 'YCL033C': 'peptide-methionine (R)-S-oxide reductase',
 'YCL032W': 'Ste50p',
 'YCL031C': 'Rrp7p',
 'YCL030C': 'trifunctional histidinol dehydrogenase/phosphoribosyl-AMP cyclohydrolase/phosphoribosyl-ATP diphosphatase',
 'YCL029C': 'Bik1p',
 'YCL028W': 'prion domain-containing protein RNQ1',
 'YCL027W': 'Fus1p',
 'YCL026C-B': 'putative nitroreductase',
 'YCL026C-A': 'type II nitroreductase',
 'YCL025C': 'amino acid transporter AGP1',
 'YCL024W': 'serine/threonine protein kinase',
 'YNCC0001C': 'tRNA-Glu',
 'YCL021W-A': 'uncharacterized protein',
 'YCL020W': 'gag protein',
 'YCL019W': 'gag-pol fusion protein',
 'YNCC0002W': 'tRNA-Leu',
 'YCL018W': '3-isopropylmalate dehydrogenase',
 'YCL017C': 'cysteine desulfurase',
 'YCL016C': 'Dcc1p',
 'YCL014W': 'Bud3p',
 'YCL011C': 'single-stranded telomeric DNA-binding/mRNA-binding protein',
 'YCL010C': 'Sgf29p',
 'YCL009C': 'acetolactate synthase regulatory subunit',
 'YCL008C': 'ubiquitin-binding ESCRT-I subunit protein STP22',
 'YCL005W': 'Ldb16p',
 'YCL004W': 'CDP-diacylglycerol--glycerol-3-phosphate 3-phosphatidyltransferase',
 'YCL002C': 'uncharacterized protein',
 'YCL001W': 'protein retrieval receptor',
 'YCL001W-A': 'uncharacterized protein',
 'YCL001W-B': 'uncharacterized protein',
 'YCR001W': 'uncharacterized protein',
 'YCR002C': 'septin CDC10',
 'YCR003W': 'mitochondrial 54S ribosomal protein YmL32',
 'YCR004C': 'flavodoxin-like fold family protein',
 'YCR005C': 'citrate (Si)-synthase CIT2',
 'YCR006C': 'uncharacterized protein',
 'YNCC0004C': 'tRNA-Pro',
 'YCR007C': 'DUP240 family protein',
 'YNCC0005W': 'tRNA-Asn',
 'YCR008W': 'serine/threonine protein kinase SAT4',
 'YCR009C': 'amphiphysin-like protein RVS161',
 'YCR010C': 'Ady2p',
 'YCR011C': 'putative ATP-dependent permease ADP1',
 'YCR012W': 'phosphoglycerate kinase',
 'YCR014C': 'DNA-directed DNA polymerase IV',
 'YCR015C': 'Cto1p',
 'YNCC0007C': 'tRNA-Gly',
 'YCR016W': 'RNA-binding ribosome assembly factor RBP95',
 'YCR017C': 'Cwh43p',
 'YCR018C': 'Srd1p',
 'YNCC0008W': 'tRNA-Met',
 'YNCC0009C': 'tRNA-Lys',
 'YCR019W': 'Mak32p',
 'YCR020C': 'Pet18p',
 'YCR020C-A': 'Mak31p',
 'YCR020W-B': 'Htl1p',
 'YCR021C': 'Hsp30p',
 'YCR022C': 'uncharacterized protein',
 'YCR023C': 'uncharacterized protein',
 'YCR024C': 'asparagine--tRNA ligase SLM5',
 'YCR024C-A': 'proteolipid ATPase',
 'YCR025C': 'uncharacterized protein',
 'YCR026C': 'nucleotide diphosphatase/phosphodiesterase NPP1',
 'YCR027C': 'putative GTPase RHB1',
 'YNCC0010C': 'tRNA-Gln',
 'YCR028C': 'Fen2p',
 'YCR028C-A': 'Rim1p',
 'YCR030C': 'Syp1p',
 'YCR031C': 'ribosomal 40S subunit protein S14A',
 'YCR032W': 'Bph1p',
 'YCR033W': 'Snt1p',
 'YCR034W': 'fatty acid elongase ELO2',
 'YCR035C': 'exosome non-catalytic core subunit RRP43',
 'YCR036W': 'putative ribokinase',
 'YCR037C': 'SPX domain-containing inorganic phosphate transporter',
 'YCR038C': 'Ras family guanine nucleotide exchange factor BUD5',
 'YCR039C': 'homeodomain mating type protein alpha2',
 'YCR040W': 'transcriptional co-activator mating type protein alpha',
 'YCR041W': 'uncharacterized protein',
 'YCR042C': 'transcription initiation factor TFIID subunit TAF2',
 'YCR043C': 'uncharacterized protein',
 'YCR044C': 'Per1p',
 'YCR045C': 'Rrt12p',
 'YCR046C': 'mitochondrial 54S ribosomal protein IMG1',
 'YCR047C': '18S rRNA (guanine1575-N7)-methyltransferase',
 'YCR048W': 'sterol acyltransferase',
 'YCR050C': 'uncharacterized protein',
 'YCR051W': 'uncharacterized protein',
 'YCR052W': 'Rsc6p',
 'YCR053W': 'threonine synthase THR4',
 'YCR054C': 'Ctr86p',
 'YCR057C': 'snoRNA-binding rRNA-processing protein PWP2',
 'YCR059C': 'Yih1p',
 'YCR060W': 'Tah1p',
 'YCR061W': 'Tvs1p',
 'YNCC0013W': 'tRNA-Ser',
 'YCR063W': 'U2 snRNP complex subunit BUD31',
 'YCR065W': 'Hcm1p',
 'YCR066W': 'E3 ubiquitin-protein ligase RAD18',
 'YCR067C': 'GTPase-activating protein SED4',
 'YCR068W': 'triglyceride lipase ATG15',
 'YCR069W': 'peptidylprolyl isomerase family protein CPR4',
 'YCR071C': 'mitochondrial 54S ribosomal protein IMG2',
 'YCR072C': 'Rsa4p',
 'YCR073C': 'mitogen-activated protein kinase kinase kinase SSK22',
 'YCR073W-A': 'Sol2p',
 'YCR075C': 'cystinosin-like protein ERS1',
 'YCR076C': 'Fub1p',
 'YCR077C': 'deadenylation-dependent mRNA-decapping factor PAT1',
 'YCR079W': 'type 2C protein phosphatase PTC6',
 'YCR081W': 'Srb8p',
 'YCR082W': 'Ahc2p',
 'YCR083W': 'Trx3p',
 'YCR084C': 'chromatin-silencing transcriptional regulator TUP1',
 'YCR085W': 'uncharacterized protein',
 'YCR086W': 'Csm1p',
 'YCR087C-A': 'uncharacterized protein',
 'YCR088W': 'Abp1p',
 'YCR089W': 'Fig2p',
 'YCR090C': 'uncharacterized protein',
 'YCR091W': 'putative serine/threonine protein kinase KIN82',
 'YCR092C': 'mismatch repair protein MSH3',
 'YCR093W': 'CCR4-NOT core subunit CDC39',
 'YCR094W': 'aminophospholipid translocase regulatory protein CDC50',
 'YCR095C': 'Oca4p',
 'YCR096C': 'homeodomain mating type protein a2',
 'YCR097W': 'Hmra1p',
 'YNCC0014W': 'tRNA-Thr',
 'YCR098C': 'Git1p',
 'YCR099C': 'uncharacterized protein',
 'YCR100C': 'Ema35p',
 'YCR101C': 'uncharacterized protein',
 'YCR102C': 'uncharacterized protein',
 'YCR104W': 'seripauperin PAU3',
 'YCR105W': 'NADP-dependent alcohol dehydrogenase',
 'YCR106W': 'Rds1p',
 'YCR107W': 'putative aryl-alcohol dehydrogenase',
 'YFL068W': 'uncharacterized protein',
 'YFL067W': 'uncharacterized protein',
 'YFL066C': "Y' element ATP-dependent helicase",
 'YFL065C': 'uncharacterized protein',
 'YFL064C': 'uncharacterized protein',
 'YFL062W': 'Cos4p',
 'YFL061W': 'cyanamide hydratase',
 'YFL060C': "putative pyridoxal 5'-phosphate synthase",
 'YFL059W': 'pyridoxine biosynthesis protein SNZ3',
 'YFL058W': '4-amino-5-hydroxymethyl-2-methylpyrimidine phosphate synthase',
 'YFL056C': 'pseudo',
 'YFL055W': 'Agp3p',
 'YFL054C': 'Aqy3p',
 'YFL053W': 'dihydroxyacetone kinase',
 'YFL052W': 'DNA-binding domain containing protein',
 'YFL051C': 'uncharacterized protein',
 'YFL050C': 'putative Mg(2+) transporter ALR2',
 'YFL049W': 'Swp82p',
 'YFL048C': 'Emp47p',
 'YFL047W': 'GTPase-activating protein RGD2',
 'YFL046W': 'Fmp32p',
 'YFL045C': 'phosphomannomutase SEC53',
 'YFL044C': 'ubiquitin-specific protease OTU1',
 'YFL042C': 'Lam5p',
 'YFL041W': 'ferroxidase FET5',
 'YFL040W': 'uncharacterized protein',
 'YFL039C': 'actin',
 'YFL038C': 'Rab family GTPase YPT1',
 'YFL037W': 'beta-tubulin',
 'YFL036W': 'DNA-directed RNA polymerase',
 'YFL034C-B': 'Mob2p',
 'YFL034C-A': 'ribosomal 60S subunit protein L22B',
 'YFL034W': 'Mil1p',
 'YFL033C': 'protein kinase RIM15',
 'YFL031W': 'transcription factor HAC1',
 'YFL030W': 'alanine--glyoxylate transaminase',
 'YFL029C': 'cyclin-dependent protein kinase-activating kinase CAK1',
 'YFL028C': 'putative ATP-binding cassette family ATPase CAF16',
 'YFL027C': 'GTPase-activating protein GYP8',
 'YFL026W': 'alpha-factor pheromone receptor STE2',
 'YFL025C': 'Bst1p',
 'YFL024C': 'Epl1p',
 'YFL023W': 'prefoldin-like protein',
 'YFL022C': 'phenylalanine--tRNA ligase subunit alpha',
 'YFL021W': 'Gat1p',
 'YFL020C': 'seripauperin PAU5',
 'YFL019C': 'uncharacterized protein',
 'YNCF0002W': 'tRNA-Pro',
 'YFL018C': 'dihydrolipoyl dehydrogenase',
 'YFL017W-A': 'mRNA splicing protein SMX2',
 'YFL017C': 'glucosamine 6-phosphate N-acetyltransferase',
 'YFL016C': 'Mdj1p',
 'YFL015C': 'uncharacterized protein',
 'YFL014W': 'lipid-binding protein HSP12',
 'YFL013C': 'Ies1p',
 'YFL012W': 'uncharacterized protein',
 'YFL011W': 'hexose transporter HXT10',
 'YFL010W-A': 'Aua1p',
 'YFL010C': 'Wwm1p',
 'YFL009W': 'SCF ubiquitin ligase complex subunit CDC4',
 'YFL008W': 'cohesin subunit SMC1',
 'YFL007W': 'proteasome activator BLM10',
 'YFL005W': 'Rab family GTPase SEC4',
 'YFL004W': 'vacuolar transporter chaperone',
 'YFL003C': 'MutS family protein MSH4',
 'YNCF0004C': 'tRNA-Asn',
 'YFL002W-B': 'gag protein',
 'YFL002W-A': 'gag-pol fusion protein',
 'YFL002C': 'ATP-dependent RNA helicase SPB4',
 'YFL001W': 'pseudouridine synthase DEG1',
 'YFR001W': 'Loc1p',
 'YFR002W': 'linker nucleoporin NIC96',
 'YFR003C': 'type 1 protein phosphatase-activating protein YPI1',
 'YFR004W': 'proteasome regulatory particle lid subunit RPN11',
 'YFR005C': 'mRNA splicing protein SAD1',
 'YFR006W': 'putative Xaa-Pro dipeptidase',
 'YNCF0005C': 'tRNA-Phe',
 'YFR007W': 'Yfh7p',
 'YFR008W': 'Far7p',
 'YNCF0006W': 'tRNA-Gly',
 'YFR009W': 'putative AAA family ATPase GCN20',
 'YFR010W': 'ubiquitin-specific protease UBP6',
 'YFR011C': 'Mic19p',
 'YNCF0007W': 'tRNA-Tyr',
 'YFR012W': 'Dcv1p',
 'YFR012W-A': 'uncharacterized protein',
 'YFR013W': 'Ioc3p',
 'YFR014C': 'calmodulin-dependent protein kinase CMK1',
 'YFR015C': 'glycogen (starch) synthase GSY1',
 'YFR016C': 'Aip5p',
 'YNCF0008C': 'tRNA-Gly',
 'YFR017C': 'Igd1p',
 'YFR018C': 'uncharacterized protein',
 'YFR019W': '1-phosphatidylinositol-3-phosphate 5-kinase',
 'YNCF0009C': 'tRNA-Ser',
 'YFR020W': 'Css2p',
 'YFR021W': 'phosphoinositide binding protein ATG18',
 'YFR022W': 'Rog3p',
 'YFR023W': 'Pes4p',
 'YFR024C-A': 'Lsb3p',
 'YFR025C': 'histidinol-phosphatase',
 'YNCF0011C': 'tRNA-Ala',
 'YFR026C': 'Uli1p',
 'YFR027W': 'Eco1p',
 'YFR028C': 'phosphoprotein phosphatase CDC14',
 'YNCF0012C': 'tRNA-Tyr',
 'YFR029W': 'Ptr3p',
 'YFR030W': 'sulfite reductase subunit alpha',
 'YFR031C': 'condensin subunit SMC2',
 'YFR031C-A': 'ribosomal 60S subunit protein L2A',
 'YFR032C': 'Rrt5p',
 'YFR032C-A': 'ribosomal 60S subunit protein L29',
 'YFR033C': 'ubiquinol--cytochrome-c reductase subunit 6',
 'YFR034C': 'phosphate-sensing transcription factor PHO4',
 'YFR035C': 'uncharacterized protein',
 'YNCF0014C': 'tRNA-Lys',
 'YFR036W': 'anaphase promoting complex subunit CDC26',
 'YFR037C': 'Rsc8p',
 'YFR038W': 'putative ATPase',
 'YFR039C': 'Osw7p',
 'YFR040W': 'Sap155p',
 'YFR041C': 'Erj5p',
 'YFR042W': 'Keg1p',
 'YFR043C': 'Irc6p',
 'YFR044C': 'metallodipeptidase',
 'YFR045W': 'Mrx20p',
 'YFR046C': 'centromere-binding protein CNN1',
 'YFR047C': 'nicotinate-nucleotide diphosphorylase (carboxylating)',
 'YFR048W': 'Rmd8p',
 'YFR049W': 'alpha-ketoglutarate dehydrogenase subunit KGD4',
 'YFR050C': 'proteasome core particle subunit beta 7',
 'YFR051C': 'coatomer subunit delta',
 'YFR052W': 'proteasome regulatory particle lid subunit RPN12',
 'YFR053C': 'hexokinase 1',
 'YFR054C': 'uncharacterized protein',
 'YFR055W': 'cysteine-S-conjugate beta-lyase IRC7',
 'YFR057W': 'uncharacterized protein',
 'YLL040C': 'membrane morphogenesis protein VPS13',
 'YLL039C': 'ubiquitin',
 'YLL038C': 'Ent4p',
 'YLL036C': 'E3 ubiquitin-protein ligase PRP19',
 'YLL035W': "polynucleotide 5'-hydroxyl-kinase",
 'YLL034C': 'putative AAA family ATPase RIX7',
 'YLL033W': 'Irc19p',
 'YLL032C': 'uncharacterized protein',
 'YLL031C': 'mannose-ethanolamine phosphotransferase GPI13',
 'YLL030C': 'Rrt7p',
 'YLL029W': 'aminopeptidase P',
 'YLL028W': 'polyamine transporter TPO1',
 'YLL027W': 'Fe-binding Fe/S cluster assembly protein ISA1',
 'YLL026W': 'chaperone ATPase HSP104',
 'YNCL0001W': 'tRNA-Pro',
 'YLL025W': 'seripauperin PAU17',
 'YLL024C': 'Hsp70 family chaperone SSA2',
 'YLL023C': 'nucleoporin POM33',
 'YLL022C': 'Hif1p',
 'YLL021W': 'Spa2p',
 'YLL019C': 'serine/threonine protein kinase KNS1',
 'YLL018C-A': 'Cox19p',
 'YLL018C': 'aspartate--tRNA ligase DPS1',
 'YLL016W': 'pseudo',
 'YLL015W': 'ATP-binding cassette bilirubin transporter BPT1',
 'YLL014W': 'Emc6p',
 'YLL013C': 'mRNA-binding protein PUF3',
 'YLL012W': 'sterol esterase',
 'YLL011W': 'rRNA-processing protein SOF1',
 'YLL010C': 'phosphatase',
 'YLL009C': 'copper metallochaperone COX17',
 'YLL008W': 'putative ATP-dependent RNA helicase',
 'YLL007C': 'Lmo1p',
 'YLL006W': 'ERMES complex subunit MMM1',
 'YLL005C': 'Spo75p',
 'YLL004W': 'origin recognition complex subunit 3',
 'YLL003W': 'Sfi1p',
 'YLL002W': 'H3 histone acetyltransferase RTT109',
 'YLL067C': "Y' element ATP-dependent helicase",
 'YLL066C': "Y' element ATP-dependent helicase",
 'YLL064C': 'seripauperin PAU18',
 'YLL063C': 'acetyltransferase',
 'YLL062C': 'S-adenosylmethionine-homocysteine S-methyltransferase MHT1',
 'YLL061W': 'S-methylmethionine permease MMP1',
 'YLL060C': 'glutathione transferase GTT2',
 'YLL058W': 'cystathionine gamma-synthase',
 'YLL057C': 'sulfonate dioxygenase',
 'YLL056C': 'uncharacterized protein',
 'YLL055W': 'Yct1p',
 'YLL054C': 'uncharacterized protein',
 'YLL053C': 'uncharacterized protein',
 'YLL052C': 'Aqy2p',
 'YLL051C': 'putative ferric-chelate reductase',
 'YLL050C': 'cofilin',
 'YLL049W': 'Ldb18p',
 'YLL048C': 'bile acid-transporting ATPase YBT1',
 'YLL046C': 'Rnp1p',
 'YLL045C': 'ribosomal 60S subunit protein L8B',
 'YLL043W': 'Fps1p',
 'YLL042C': 'E2-like conjugating enzyme',
 'YLL041C': 'succinate dehydrogenase iron-sulfur protein subunit SDH2',
 'YLL001W': 'dynamin-related GTPase DNM1',
 'YLR001C': 'uncharacterized protein',
 'YLR002C': 'Noc3p',
 'YLR003C': 'Cms1p',
 'YLR004C': 'Thi73p',
 'YLR005W': 'TFIIH/NER complex subunit SSL1',
 'YLR006C': 'mitogen-activated protein kinase kinase kinase SSK1',
 'YLR007W': 'Smc5-Smc6 complex subunit NSE1',
 'YLR008C': 'Pam18p',
 'YLR009W': 'ATPase-activating ribosome biosynthesis protein',
 'YLR010C': 'Ten1p',
 'YNCL0002C': 'tRNA-Ser',
 'YLR011W': 'flavin-dependent quinone reductase',
 'YLR012C': 'uncharacterized protein',
 'YLR013W': 'Gat3p',
 'YLR014C': 'Ppr1p',
 'YLR015W': 'Bre2p',
 'YLR016C': 'Pml1p',
 'YLR017W': 'S-methyl-5-thioadenosine phosphorylase',
 'YLR018C': 'Pom34p',
 'YLR019W': 'putative phosphatase',
 'YLR020C': 'sterol esterase',
 'YLR021W': 'Irc25p',
 'YLR022C': 'guanine nucleotide exchange factor SDO1',
 'YLR023C': 'Izh3p',
 'YLR024C': 'putative ubiquitin-protein ligase UBR2',
 'YLR025W': 'ESCRT-III subunit protein SNF7',
 'YLR026C': 't-SNARE syntaxin',
 'YLR027C': 'aspartate transaminase AAT2',
 'YLR028C': 'bifunctional phosphoribosylaminoimidazolecarboxamide formyltransferase/IMP cyclohydrolase ADE16',
 'YLR029C': 'ribosomal 60S subunit protein L15A',
 'YLR030W': 'uncharacterized protein',
 'YLR031W': 'uncharacterized protein',
 'YLR032W': 'DNA helicase RAD5',
 'YLR033W': 'Rsc58p',
 'YLR034C': 'putative divalent metal ion transporter SMF3',
 'YLR035C': 'mismatch repair protein MLH2',
 'YNCL0004C': 'tRNA-Ala',
 'YLR035C-A': 'gag-pol fusion protein',
 'YLR036C': 'uncharacterized protein',
 'YLR037C': 'seripauperin PAU23',
 'YLR038C': 'cytochrome c oxidase subunit VIb',
 'YLR039C': 'Ric1p',
 'YLR040C': 'Afb1p',
 'YLR042C': 'Nfg1p',
 'YLR043C': 'thioredoxin TRX1',
 'YLR044C': 'indolepyruvate decarboxylase 1',
 'YLR045C': 'Stu2p',
 'YLR046C': 'uncharacterized protein',
 'YLR047C': 'putative ferric-chelate reductase',
 'YLR048W': 'ribosomal 40S subunit protein S0B',
 'YLR049C': 'Mlo50p',
 'YLR050C': 'Ema19p',
 'YLR051C': 'Fcf2p',
 'YLR052W': 'Ies3p',
 'YLR053C': 'Nrs1p',
 'YLR054C': 'Osw2p',
 'YLR055C': 'SAGA complex subunit SPT8',
 'YLR056W': 'C-5 sterol desaturase',
 'YLR057W': 'putative mannosidase MNL2',
 'YLR058C': 'glycine hydroxymethyltransferase SHM2',
 'YLR059C': 'Rex2p',
 'YLR060W': 'phenylalanine--tRNA ligase subunit beta',
 'YLR061W': 'ribosomal 60S subunit protein L22A',
 'YLR063W': '25S rRNA (uracil2843-N3)-methyltransferase',
 'YLR064W': 'Per33p',
 'YLR065C': 'Snd2p',
 'YLR066W': 'signal peptidase complex subunit SPC3',
 'YLR067C': 'Pet309p',
 'YLR068W': 'Fyv7p',
 'YLR069C': 'Mef1p',
 'YLR070C': 'D-xylulose reductase XYL2',
 'YLR071C': 'Rgr1p',
 'YLR072W': 'Lam6p',
 'YLR073C': 'Rfu1p',
 'YLR074C': 'Bud20p',
 'YLR075W': 'ribosomal 60S subunit protein L10',
 'YLR077W': 'Fmp25p',
 'YLR078C': 'Bos1p',
 'YLR079W': 'cyclin-dependent protein serine/threonine kinase inhibiting protein SIC1',
 'YLR080W': 'Emp46p',
 'YLR081W': 'galactose permease GAL2',
 'YLR082C': 'Srl2p',
 'YLR083C': 'Emp70p',
 'YLR084C': 'Rax2p',
 'YLR085C': 'Arp6p',
 'YLR086W': 'condensin subunit SMC4',
 'YLR087C': 'Csf1p',
 'YLR088W': 'GPI-anchor transamidase subunit GAA1',
 'YLR089C': 'alanine transaminase ALT1',
 'YLR090W': 'Xdj1p',
 'YLR091W': 'Gep5p',
 'YLR092W': 'sulfate permease',
 'YLR093C': 'Nyv1p',
 'YLR094C': 'Gis3p',
 'YLR095C': 'Ioc2p',
 'YLR096W': 'serine/threonine protein kinase KIN2',
 'YLR097C': 'SCF ubiquitin ligase complex subunit HRT3',
 'YLR098C': 'Cha4p',
 'YLR099C': 'lysophosphatidic acid acyltransferase ICT1',
 'YLR099W-A': 'Mim2p',
 'YLR100W': '3-keto-steroid reductase',
 'YLR102C': 'anaphase promoting complex subunit 9',
 'YLR103C': 'DNA replication initiation factor CDC45',
 'YLR104W': 'Lcl2p',
 'YLR105C': 'tRNA splicing endonuclease subunit SEN2',
 'YLR106C': 'AAA family ATPase midasin',
 'YLR107W': 'RNA exonuclease',
 'YLR108C': 'uncharacterized protein',
 'YLR109W': 'thioredoxin peroxidase AHP1',
 'YLR110C': 'Ccw12p',
 'YLR111W': 'uncharacterized protein',
 'YLR112W': 'uncharacterized protein',
 'YLR113W': 'mitogen-activated protein kinase HOG1',
 'YNCL0007W': 'tRNA-Arg',
 'YLR114C': 'Avl9p',
 'YLR115W': 'cleavage polyadenylation factor subunit CFT2',
 'YLR116W': 'mRNA splicing protein MSL5',
 'YLR117C': 'Clf1p',
 'YLR118C': 'palmitoyl-(protein) hydrolase',
 'YLR119W': 'ESCRT-I subunit protein SRN2',
 'YLR120C': 'aspartyl protease',
 'YLR121C': 'aspartyl protease',
 'YLR122C': 'uncharacterized protein',
 'YLR125W': 'uncharacterized protein',
 'YLR126C': 'putative amidotransferase',
 'YLR127C': 'anaphase promoting complex subunit 2',
 'YLR128W': 'NEDD8 ligase DCN1',
 'YLR129W': 'snoRNA-binding rRNA-processing protein DIP2',
 'YLR130C': 'low-affinity Zn(2+) transporter ZRT2',
 'YLR131C': 'DNA-binding transcription factor ACE2',
 'YLR132C': 'phosphoric diester hydrolase',
 'YLR133W': 'bifunctional choline kinase/ethanolamine kinase CKI1',
 'YLR134W': 'indolepyruvate decarboxylase 5',
 'YLR135W': 'Slx4p',
 'YLR136C': 'Tis11p',

# Protein_Protein

In [4]:
'''
Data is collected from STRING
'''

'\nData is collected from STRING\n'

In [5]:
yeast_Protein_Protein_path = f'{BASE_PATH}string/scer/4932.protein.links.v12.0.txt'

Y_P_P = pd.read_csv(yeast_Protein_Protein_path, sep = '\s')

Y_P_P = Y_P_P.rename(columns={
    'protein1': 'head',
    'protein2': 'tail'
})

Y_P_P['head'] = Y_P_P['head'].str.replace('4932.', '')
Y_P_P['tail'] = Y_P_P['tail'].str.replace('4932.', '')
Y_P_P

Y_P_P['relation'] = 'Gene_Gene'
Y_P_P['head_type'] = 'Gene'
Y_P_P['tail_type'] = 'Gene'
Y_P_P['relation_type'] = np.nan
Y_P_P['kg_source'] = 'STRING'
Y_P_P['head_detail_name'] = Y_P_P['head'].map(NCBI_Yeast_Locustag_Descrip_dict)
Y_P_P['tail_detail_name'] = Y_P_P['tail'].map(NCBI_Yeast_Locustag_Descrip_dict)
Y_P_P['head_id_is'] = 'SGD_SysematicName'
Y_P_P['tail_id_is'] = 'SGD_SysematicName'
Y_P_P['species'] = 'S.cerevisae'
Y_P_P
Y_P_P = Y_P_P[~Y_P_P['head_detail_name'].isna()]
Y_P_P = Y_P_P[~Y_P_P['tail_detail_name'].isna()]
Y_P_P

<>:3: SyntaxWarning: invalid escape sequence '\s'
<>:3: SyntaxWarning: invalid escape sequence '\s'
/tmp/ipykernel_2139107/72427256.py:3: SyntaxWarning: invalid escape sequence '\s'
  Y_P_P = pd.read_csv(yeast_Protein_Protein_path, sep = '\s')
/tmp/ipykernel_2139107/72427256.py:3: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  Y_P_P = pd.read_csv(yeast_Protein_Protein_path, sep = '\s')

,head,tail,combined_score,relation,head_type,tail_type,relation_type,kg_source,head_detail_name,tail_detail_name,head_id_is,tail_id_is,species
1106,Q0045,YBR146W,174,Gene_Gene,Gene,Gene,NaN,STRING,cytochrome c oxidase subunit 1,mitochondrial 37S ribosomal protein MRPS9,SGD_SysematicName,SGD_SysematicName,S.cerevisae
1107,Q0045,YOR176W,168,Gene_Gene,Gene,Gene,NaN,STRING,cytochrome c oxidase subunit 1,ferrochelatase HEM15,SGD_SysematicName,SGD_SysematicName,S.cerevisae
1108,Q0045,YNL121C,197,Gene_Gene,Gene,Gene,NaN,STRING,cytochrome c oxidase subunit 1,protein channel TOM70,SGD_SysematicName,SGD_SysematicName,S.cerevisae
1109,Q0045,YFR039C,186,Gene_Gene,Gene,Gene,NaN,STRING,cytochrome c oxidase subunit 1,Osw7p,SGD_SysematicName,SGD_SysematicName,S.cerevisae
1110,Q0045,YLR259C,465,Gene_Gene,Gene,Gene,NaN,STRING,cytochrome c oxidase subunit 1,chaperone ATPase HSP60,SGD_SysematicName,SGD_SysematicName,S.cerevisae
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2824837,YPR204W,YGL150C,181,Gene_Gene,Gene,Gene,NaN,STRING,Y' element ATP-dependent helicase,chromatin-remodeling ATPase INO80,SGD_SysematicName,SGD_SysematicName,S.cerevisae
2824838,YPR204W,YOR326W,204,Gene_Gene,Gene,Gene,NaN,STRING,Y' element ATP-dependent helicase,myosin 2,SGD_SysematicName,SGD_SysematicName,S.cerevisae
2824839,YPR204W,YPR007C,194,Gene_Gene,Gene,Gene,NaN,STRING,Y' element ATP-dependent helicase,Rec8p,SGD_SysematicName,SGD_SysematicName,S.cerevisae
2824840,YPR204W,YDR051C,180,Gene_Gene,Gene,Gene,NaN,STRING,Y' element ATP-dependent helicase,acid phosphatase DET1,SGD_SysematicName,SGD_SysematicName,S.cerevisae
2824841,YPR204W,YLR247C,233,Gene_Gene,Gene,Gene,NaN,STRING,Y' element ATP-dependent helicase,E3 ubiquitin-protein ligase IRC20,SGD_SysematicName,SGD_SysematicName,S.cerevisae

In [6]:
Y_P_P.columns

Index(['head', 'tail', 'combined_score', 'relation', 'head_type', 'tail_type',
       'relation_type', 'kg_source', 'head_detail_name', 'tail_detail_name',
       'head_id_is', 'tail_id_is', 'species'],
      dtype='object')

In [7]:
final_df = Y_P_P
set(final_df['species']), set(final_df['relation']),set(final_df['head_type']),set(final_df['tail_type']),set(final_df['kg_source']),set(final_df['head_id_is']),set(final_df['tail_id_is'])

({'S.cerevisae'},
 {'Gene_Gene'},
 {'Gene'},
 {'Gene'},
 {'STRING'},
 {'SGD_SysematicName'},
 {'SGD_SysematicName'})

In [8]:
# Count true NaN values
true_nan_count = final_df.isna().sum()

# Count string 'NAN' values (case-insensitive)
string_nan_count = final_df.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

# Combine both counts
nan_summary = pd.DataFrame({
    'NaN_count': true_nan_count,
    "'NAN'_string_count": string_nan_count,
    'Total_NaN_like': true_nan_count + string_nan_count
})
nan_summary

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
tail                      0                   0               0
combined_score            0                   0               0
relation                  0                   0               0
head_type                 0                   0               0
tail_type                 0                   0               0
relation_type       2743780             2743780         5487560
kg_source                 0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
species                   0                   0               0

In [9]:
# First, concatenate all dataframes as before (assuming `final_df` already exists from earlier step)

# Group by the 3 key columns
group_cols = ['head', 'relation', 'tail']

# For kg_source, combine with '::'
def merge_sources(x):
    return '::'.join(sorted(set(x.dropna())))

# Merge duplicates
final_df_dedup = final_df.groupby(group_cols, as_index=False).agg({
    'head_type': 'first',
    'relation_type': 'first',
    'tail_type': 'first',
    'kg_source': merge_sources,
    'head_id_is': 'first',
    'tail_id_is': 'first',
    'head_detail_name': 'first',
    'tail_detail_name': 'first',
    'species': 'first'
})
final_df_dedup

,head,relation,tail,head_type,relation_type,tail_type,kg_source,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,Q0045,Gene_Gene,Q0050,Gene,NaN,Gene,STRING,SGD_SysematicName,SGD_SysematicName,cytochrome c oxidase subunit 1,intron-encoded reverse transcriptase aI1,S.cerevisae
1,Q0045,Gene_Gene,Q0055,Gene,NaN,Gene,STRING,SGD_SysematicName,SGD_SysematicName,cytochrome c oxidase subunit 1,intron-encoded reverse transcriptase aI2,S.cerevisae
2,Q0045,Gene_Gene,Q0060,Gene,NaN,Gene,STRING,SGD_SysematicName,SGD_SysematicName,cytochrome c oxidase subunit 1,intron-encoded DNA endonuclease aI3,S.cerevisae
3,Q0045,Gene_Gene,Q0065,Gene,NaN,Gene,STRING,SGD_SysematicName,SGD_SysematicName,cytochrome c oxidase subunit 1,intron-encoded DNA endonuclease aI4,S.cerevisae
4,Q0045,Gene_Gene,Q0070,Gene,NaN,Gene,STRING,SGD_SysematicName,SGD_SysematicName,cytochrome c oxidase subunit 1,intron-encoded DNA endonuclease aI5 alpha,S.cerevisae
...,...,...,...,...,...,...,...,...,...,...,...,...
2743775,YPR204W,Gene_Gene,YPR190C,Gene,NaN,Gene,STRING,SGD_SysematicName,SGD_SysematicName,Y' element ATP-dependent helicase,DNA-directed RNA polymerase III subunit C82,S.cerevisae
2743776,YPR204W,Gene_Gene,YPR192W,Gene,NaN,Gene,STRING,SGD_SysematicName,SGD_SysematicName,Y' element ATP-dependent helicase,Aqy1p,S.cerevisae
2743777,YPR204W,Gene_Gene,YPR201W,Gene,NaN,Gene,STRING,SGD_SysematicName,SGD_SysematicName,Y' element ATP-dependent helicase,Arr3p,S.cerevisae
2743778,YPR204W,Gene_Gene,YPR202W,Gene,NaN,Gene,STRING,SGD_SysematicName,SGD_SysematicName,Y' element ATP-dependent helicase,uncharacterized protein,S.cerevisae
2743779,YPR204W,Gene_Gene,YPR203W,Gene,NaN,Gene,STRING,SGD_SysematicName,SGD_SysematicName,Y' element ATP-dependent helicase,uncharacterized protein,S.cerevisae

In [10]:
#

In [11]:
OUT_PATH

'/storage/Arushi/090526_EvoAge/kg_formation/processed_data/string'

In [12]:
final_df_dedup.to_csv(f'{OUT_PATH}/scer/string_YEAST_GENE_GENE.csv',index = None)

In [13]:
final_df_dedup

,head,relation,tail,head_type,relation_type,tail_type,kg_source,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,Q0045,Gene_Gene,Q0050,Gene,NaN,Gene,STRING,SGD_SysematicName,SGD_SysematicName,cytochrome c oxidase subunit 1,intron-encoded reverse transcriptase aI1,S.cerevisae
1,Q0045,Gene_Gene,Q0055,Gene,NaN,Gene,STRING,SGD_SysematicName,SGD_SysematicName,cytochrome c oxidase subunit 1,intron-encoded reverse transcriptase aI2,S.cerevisae
2,Q0045,Gene_Gene,Q0060,Gene,NaN,Gene,STRING,SGD_SysematicName,SGD_SysematicName,cytochrome c oxidase subunit 1,intron-encoded DNA endonuclease aI3,S.cerevisae
3,Q0045,Gene_Gene,Q0065,Gene,NaN,Gene,STRING,SGD_SysematicName,SGD_SysematicName,cytochrome c oxidase subunit 1,intron-encoded DNA endonuclease aI4,S.cerevisae
4,Q0045,Gene_Gene,Q0070,Gene,NaN,Gene,STRING,SGD_SysematicName,SGD_SysematicName,cytochrome c oxidase subunit 1,intron-encoded DNA endonuclease aI5 alpha,S.cerevisae
...,...,...,...,...,...,...,...,...,...,...,...,...
2743775,YPR204W,Gene_Gene,YPR190C,Gene,NaN,Gene,STRING,SGD_SysematicName,SGD_SysematicName,Y' element ATP-dependent helicase,DNA-directed RNA polymerase III subunit C82,S.cerevisae
2743776,YPR204W,Gene_Gene,YPR192W,Gene,NaN,Gene,STRING,SGD_SysematicName,SGD_SysematicName,Y' element ATP-dependent helicase,Aqy1p,S.cerevisae
2743777,YPR204W,Gene_Gene,YPR201W,Gene,NaN,Gene,STRING,SGD_SysematicName,SGD_SysematicName,Y' element ATP-dependent helicase,Arr3p,S.cerevisae
2743778,YPR204W,Gene_Gene,YPR202W,Gene,NaN,Gene,STRING,SGD_SysematicName,SGD_SysematicName,Y' element ATP-dependent helicase,uncharacterized protein,S.cerevisae
2743779,YPR204W,Gene_Gene,YPR203W,Gene,NaN,Gene,STRING,SGD_SysematicName,SGD_SysematicName,Y' element ATP-dependent helicase,uncharacterized protein,S.cerevisae

# GENE_GENE  YeastNet

In [14]:
yeast_gene_gene_path = f'{BASE_PATH}yeastnet/YEAST_GENE_GENE_withSEQ.pkl'
Y_G_G = pd.read_pickle(yeast_gene_gene_path)
Y_G_G['relation_type'] = 'Gene_Gene'
Y_G_G[['relation', 'relation_type']] = Y_G_G[['relation_type', 'relation']]
Y_G_G = Y_G_G.drop(columns={'Head_SEQ', 'Tail_SEQ'})
Y_G_G['kg_source'] = 'YeastNet'
Y_G_G['head_detail_name'] = Y_G_G['head'].map(NCBI_Yeast_Locustag_Descrip_dict)
Y_G_G['tail_detail_name'] = Y_G_G['tail'].map(NCBI_Yeast_Locustag_Descrip_dict)
Y_G_G
Y_G_G = Y_G_G[~Y_G_G['head_detail_name'].isna()]
Y_G_G = Y_G_G[~Y_G_G['tail_detail_name'].isna()]
Y_G_G['head_id_is'] = 'SGD_SysematicName'
Y_G_G['tail_id_is'] = 'SGD_SysematicName'
Y_G_G['species'] = 'S.cerevisae'

Y_G_G

,head,relation,tail,weight,head_type,tail_type,normalized_weight,relation_type,kg_source,head_detail_name,tail_detail_name,head_id_is,tail_id_is,species
15293136,YBL075C,Gene_Gene,YBR169C,4.097100,Gene,Gene,1.599374,co-citation,YeastNet,Hsp70 family ATPase SSA3,adenyl-nucleotide exchange factor SSE2,SGD_SysematicName,SGD_SysematicName,S.cerevisae
15293137,YBR019C,Gene_Gene,YBR020W,4.097100,Gene,Gene,1.599374,co-citation,YeastNet,bifunctional UDP-glucose 4-epimerase/aldose 1-...,galactokinase,SGD_SysematicName,SGD_SysematicName,S.cerevisae
15293138,YBR160W,Gene_Gene,YDL102W,4.097100,Gene,Gene,1.599374,co-citation,YeastNet,cyclin-dependent serine/threonine-protein kina...,DNA-directed DNA polymerase delta POL3,SGD_SysematicName,SGD_SysematicName,S.cerevisae
15293139,YBR169C,Gene_Gene,YPL240C,4.097100,Gene,Gene,1.599374,co-citation,YeastNet,adenyl-nucleotide exchange factor SSE2,Hsp90 family chaperone HSP82,SGD_SysematicName,SGD_SysematicName,S.cerevisae
15293140,YCR096C,Gene_Gene,YCR097W,4.097100,Gene,Gene,1.599374,co-citation,YeastNet,homeodomain mating type protein a2,Hmra1p,SGD_SysematicName,SGD_SysematicName,S.cerevisae
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16080581,YBL009W,Gene_Gene,YMR139W,2.338488,Gene,Gene,1.584525,3-D protein structure of interacting orthologo...,YeastNet,protein kinase ALK2,serine/threonine protein kinase RIM11,SGD_SysematicName,SGD_SysematicName,S.cerevisae
16080582,YBL009W,Gene_Gene,YJL106W,2.338488,Gene,Gene,1.584525,3-D protein structure of interacting orthologo...,YeastNet,protein kinase ALK2,protein kinase IME2,SGD_SysematicName,SGD_SysematicName,S.cerevisae
16080583,YAR019C,Gene_Gene,YNR031C,2.338488,Gene,Gene,1.584525,3-D protein structure of interacting orthologo...,YeastNet,serine/threonine protein kinase CDC15,mitogen-activated protein kinase kinase kinase...,SGD_SysematicName,SGD_SysematicName,S.cerevisae
16080584,YAR019C,Gene_Gene,YLR362W,2.338488,Gene,Gene,1.584525,3-D protein structure of interacting orthologo...,YeastNet,serine/threonine protein kinase CDC15,mitogen-activated protein kinase kinase kinase...,SGD_SysematicName,SGD_SysematicName,S.cerevisae
16080585,YAL040C,Gene_Gene,YBL105C,2.338488,Gene,Gene,1.584525,3-D protein structure of interacting orthologo...,YeastNet,cyclin CLN3,protein kinase C,SGD_SysematicName,SGD_SysematicName,S.cerevisae

In [15]:
# First, concatenate all dataframes as before (assuming `final_df` already exists from earlier step)

# Group by the 3 key columns
group_cols = ['head', 'relation', 'tail']

# For kg_source, combine with '::'
def merge_sources(x):
    return '::'.join(sorted(set(x.dropna())))

# Merge duplicates
final_df_dedup = Y_G_G.groupby(group_cols, as_index=False).agg({
    'head_type': 'first',
    'relation_type': 'first',
    'tail_type': 'first',
    'kg_source': merge_sources,
    'head_id_is': 'first',
    'tail_id_is': 'first',
    'head_detail_name': 'first',
    'tail_detail_name': 'first',
    'species': 'first'
})
final_df_dedup

,head,relation,tail,head_type,relation_type,tail_type,kg_source,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,Q0045,Gene_Gene,Q0050,Gene,co-citation,Gene,YeastNet,SGD_SysematicName,SGD_SysematicName,cytochrome c oxidase subunit 1,intron-encoded reverse transcriptase aI1,S.cerevisae
1,Q0045,Gene_Gene,Q0055,Gene,co-citation,Gene,YeastNet,SGD_SysematicName,SGD_SysematicName,cytochrome c oxidase subunit 1,intron-encoded reverse transcriptase aI2,S.cerevisae
2,Q0045,Gene_Gene,Q0060,Gene,co-citation,Gene,YeastNet,SGD_SysematicName,SGD_SysematicName,cytochrome c oxidase subunit 1,intron-encoded DNA endonuclease aI3,S.cerevisae
3,Q0045,Gene_Gene,Q0065,Gene,co-citation,Gene,YeastNet,SGD_SysematicName,SGD_SysematicName,cytochrome c oxidase subunit 1,intron-encoded DNA endonuclease aI4,S.cerevisae
4,Q0045,Gene_Gene,Q0070,Gene,co-occurrence of protein domains between two c...,Gene,YeastNet,SGD_SysematicName,SGD_SysematicName,cytochrome c oxidase subunit 1,intron-encoded DNA endonuclease aI5 alpha,S.cerevisae
...,...,...,...,...,...,...,...,...,...,...,...,...
694186,YPR189W,Gene_Gene,YPR191W,Gene,co-citation,Gene,YeastNet,SGD_SysematicName,SGD_SysematicName,SKI complex subunit tetratricopeptide repeat p...,ubiquinol--cytochrome-c reductase subunit 2,S.cerevisae
694187,YPR190C,Gene_Gene,YPR191W,Gene,co-citation,Gene,YeastNet,SGD_SysematicName,SGD_SysematicName,DNA-directed RNA polymerase III subunit C82,ubiquinol--cytochrome-c reductase subunit 2,S.cerevisae
694188,YPR199C,Gene_Gene,YPR200C,Gene,co-citation,Gene,YeastNet,SGD_SysematicName,SGD_SysematicName,Arr1p,Arr2p,S.cerevisae
694189,YPR199C,Gene_Gene,YPR201W,Gene,co-citation,Gene,YeastNet,SGD_SysematicName,SGD_SysematicName,Arr1p,Arr3p,S.cerevisae
694190,YPR200C,Gene_Gene,YPR201W,Gene,co-citation,Gene,YeastNet,SGD_SysematicName,SGD_SysematicName,Arr2p,Arr3p,S.cerevisae

In [16]:
OUT_PATH = "/storage/Arushi/090526_EvoAge/kg_formation/processed_data/yeastnet/"

final_df_dedup.to_csv(f'{OUT_PATH}yeastnet_YEAST_GENE_GENE.csv',index = None)

# GENE_GENE TF (BioGRID)

In [17]:
yeast_gene_gene_tf_path = f'{BASE_PATH}biogrid/YEAST_GENE_TF_withSEQ.pkl'

Y_G_G_TF = pd.read_pickle(yeast_gene_gene_tf_path)
Y_G_G_TF
Y_G_G_TF = Y_G_G_TF.drop(columns={'Head_SEQ', 'Tail_SEQ'})
Y_G_G_TF['head_detail_name'] = Y_G_G_TF['head'].map(NCBI_Yeast_Locustag_Descrip_dict)
Y_G_G_TF['tail_detail_name'] = Y_G_G_TF['tail'].map(NCBI_Yeast_Locustag_Descrip_dict)
Y_G_G_TF
Y_G_G_TF = Y_G_G_TF[~Y_G_G_TF['head_detail_name'].isna()]
Y_G_G_TF = Y_G_G_TF[~Y_G_G_TF['tail_detail_name'].isna()]
Y_G_G_TF['head_id_is'] = 'SGD_SysematicName'
Y_G_G_TF['tail_id_is'] = 'SGD_SysematicName'
Y_G_G_TF['relation_type'] = 'Gene_Gene'
Y_G_G_TF['kg_source'] = 'Biogrid'
Y_G_G_TF['species'] = 'S.cerevisae'
Y_G_G_TF['head_type'] = 'Gene'
Y_G_G_TF['tail_type'] = 'Gene'
Y_G_G_TF['relation'] = 'Gene_Gene'
Y_G_G_TF

,head,relation,tail,weight,head_type,tail_type,normalized_weight,head_detail_name,tail_detail_name,head_id_is,tail_id_is,relation_type,kg_source,species
57940498,YBR092C,Gene_Gene,YGL209W,10.0,Gene,Gene,1.649216,acid phosphatase PHO3,Mig2p,SGD_SysematicName,SGD_SysematicName,Gene_Gene,Biogrid,S.cerevisae
57940499,YBR114W,Gene_Gene,YGL209W,10.0,Gene,Gene,1.649216,DNA repair protein RAD16,Mig2p,SGD_SysematicName,SGD_SysematicName,Gene_Gene,Biogrid,S.cerevisae
57940500,YBR244W,Gene_Gene,YGL209W,10.0,Gene,Gene,1.649216,glutathione peroxidase GPX2,Mig2p,SGD_SysematicName,SGD_SysematicName,Gene_Gene,Biogrid,S.cerevisae
57940501,YBR299W,Gene_Gene,YGL209W,10.0,Gene,Gene,1.649216,alpha-glucosidase MAL32,Mig2p,SGD_SysematicName,SGD_SysematicName,Gene_Gene,Biogrid,S.cerevisae
57940502,YDR040C,Gene_Gene,YGL209W,10.0,Gene,Gene,1.649216,Na(+)/Li(+)-exporting P-type ATPase ENA1,Mig2p,SGD_SysematicName,SGD_SysematicName,Gene_Gene,Biogrid,S.cerevisae
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58068782,YJR069C,Gene_Gene,YGL237C,10.0,Gene,Gene,1.649216,nucleoside triphosphate pyrophosphohydrolase HAM1,transcription activator HAP2,SGD_SysematicName,SGD_SysematicName,Gene_Gene,Biogrid,S.cerevisae
58068783,YNL021W,Gene_Gene,YGL237C,10.0,Gene,Gene,1.649216,histone deacetylase HDA1,transcription activator HAP2,SGD_SysematicName,SGD_SysematicName,Gene_Gene,Biogrid,S.cerevisae
58068784,YNL119W,Gene_Gene,YGL237C,10.0,Gene,Gene,1.649216,Ncs2p,transcription activator HAP2,SGD_SysematicName,SGD_SysematicName,Gene_Gene,Biogrid,S.cerevisae
58068786,YJR058C,Gene_Gene,YGL237C,10.0,Gene,Gene,1.649216,Aps2p,transcription activator HAP2,SGD_SysematicName,SGD_SysematicName,Gene_Gene,Biogrid,S.cerevisae
58068787,YNL023C,Gene_Gene,YGL237C,10.0,Gene,Gene,1.649216,Fap1p,transcription activator HAP2,SGD_SysematicName,SGD_SysematicName,Gene_Gene,Biogrid,S.cerevisae

In [18]:
# Y_G_G_TF['kg_source'] = 'Biogrid'

In [19]:
# First, concatenate all dataframes as before (assuming `final_df` already exists from earlier step)

# Group by the 3 key columns
group_cols = ['head', 'relation', 'tail']

# For kg_source, combine with '::'
def merge_sources(x):
    return '::'.join(sorted(set(x.dropna())))

# Merge duplicates
final_df_dedup = Y_G_G_TF.groupby(group_cols, as_index=False).agg({
    'head_type': 'first',
    'relation_type': 'first',
    'tail_type': 'first',
    'kg_source': merge_sources,
    'head_id_is': 'first',
    'tail_id_is': 'first',
    'head_detail_name': 'first',
    'tail_detail_name': 'first',
    'species': 'first'
})
final_df_dedup

,head,relation,tail,head_type,relation_type,tail_type,kg_source,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,Q0045,Gene_Gene,YBL005W,Gene,Gene_Gene,Gene,Biogrid,SGD_SysematicName,SGD_SysematicName,cytochrome c oxidase subunit 1,drug-responsive transcription factor PDR3,S.cerevisae
1,Q0045,Gene_Gene,YDL020C,Gene,Gene_Gene,Gene,Biogrid,SGD_SysematicName,SGD_SysematicName,cytochrome c oxidase subunit 1,stress-regulated transcription factor RPN4,S.cerevisae
2,Q0045,Gene_Gene,YFL031W,Gene,Gene_Gene,Gene,Biogrid,SGD_SysematicName,SGD_SysematicName,cytochrome c oxidase subunit 1,transcription factor HAC1,S.cerevisae
3,Q0045,Gene_Gene,YGL013C,Gene,Gene_Gene,Gene,Biogrid,SGD_SysematicName,SGD_SysematicName,cytochrome c oxidase subunit 1,drug-responsive transcription factor PDR1,S.cerevisae
4,Q0045,Gene_Gene,YIL101C,Gene,Gene_Gene,Gene,Biogrid,SGD_SysematicName,SGD_SysematicName,cytochrome c oxidase subunit 1,Xbp1p,S.cerevisae
...,...,...,...,...,...,...,...,...,...,...,...,...
121612,YPR204W,Gene_Gene,YJR060W,Gene,Gene_Gene,Gene,Biogrid,SGD_SysematicName,SGD_SysematicName,Y' element ATP-dependent helicase,Cbf1p,S.cerevisae
121613,YPR204W,Gene_Gene,YKL032C,Gene,Gene_Gene,Gene,Biogrid,SGD_SysematicName,SGD_SysematicName,Y' element ATP-dependent helicase,DNA-binding transcription repressor IXR1,S.cerevisae
121614,YPR204W,Gene_Gene,YKL109W,Gene,Gene_Gene,Gene,Biogrid,SGD_SysematicName,SGD_SysematicName,Y' element ATP-dependent helicase,transcription factor HAP4,S.cerevisae
121615,YPR204W,Gene_Gene,YML007W,Gene,Gene_Gene,Gene,Biogrid,SGD_SysematicName,SGD_SysematicName,Y' element ATP-dependent helicase,DNA-binding transcription factor YAP1,S.cerevisae
121616,YPR204W,Gene_Gene,YPL038W,Gene,Gene_Gene,Gene,Biogrid,SGD_SysematicName,SGD_SysematicName,Y' element ATP-dependent helicase,Met31p,S.cerevisae

In [20]:
OUT_PATH = "/storage/Arushi/090526_EvoAge/kg_formation/processed_data/biogrid/"

final_df_dedup.to_csv(f'{OUT_PATH}biogrid_YEAST_GENE_GENE.csv',index = None)
final_df_dedup

,head,relation,tail,head_type,relation_type,tail_type,kg_source,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,Q0045,Gene_Gene,YBL005W,Gene,Gene_Gene,Gene,Biogrid,SGD_SysematicName,SGD_SysematicName,cytochrome c oxidase subunit 1,drug-responsive transcription factor PDR3,S.cerevisae
1,Q0045,Gene_Gene,YDL020C,Gene,Gene_Gene,Gene,Biogrid,SGD_SysematicName,SGD_SysematicName,cytochrome c oxidase subunit 1,stress-regulated transcription factor RPN4,S.cerevisae
2,Q0045,Gene_Gene,YFL031W,Gene,Gene_Gene,Gene,Biogrid,SGD_SysematicName,SGD_SysematicName,cytochrome c oxidase subunit 1,transcription factor HAC1,S.cerevisae
3,Q0045,Gene_Gene,YGL013C,Gene,Gene_Gene,Gene,Biogrid,SGD_SysematicName,SGD_SysematicName,cytochrome c oxidase subunit 1,drug-responsive transcription factor PDR1,S.cerevisae
4,Q0045,Gene_Gene,YIL101C,Gene,Gene_Gene,Gene,Biogrid,SGD_SysematicName,SGD_SysematicName,cytochrome c oxidase subunit 1,Xbp1p,S.cerevisae
...,...,...,...,...,...,...,...,...,...,...,...,...
121612,YPR204W,Gene_Gene,YJR060W,Gene,Gene_Gene,Gene,Biogrid,SGD_SysematicName,SGD_SysematicName,Y' element ATP-dependent helicase,Cbf1p,S.cerevisae
121613,YPR204W,Gene_Gene,YKL032C,Gene,Gene_Gene,Gene,Biogrid,SGD_SysematicName,SGD_SysematicName,Y' element ATP-dependent helicase,DNA-binding transcription repressor IXR1,S.cerevisae
121614,YPR204W,Gene_Gene,YKL109W,Gene,Gene_Gene,Gene,Biogrid,SGD_SysematicName,SGD_SysematicName,Y' element ATP-dependent helicase,transcription factor HAP4,S.cerevisae
121615,YPR204W,Gene_Gene,YML007W,Gene,Gene_Gene,Gene,Biogrid,SGD_SysematicName,SGD_SysematicName,Y' element ATP-dependent helicase,DNA-binding transcription factor YAP1,S.cerevisae
121616,YPR204W,Gene_Gene,YPL038W,Gene,Gene_Gene,Gene,Biogrid,SGD_SysematicName,SGD_SysematicName,Y' element ATP-dependent helicase,Met31p,S.cerevisae

# GENE_RBP (BioGRID)

In [21]:

yeast_gene_gene_rbp = f'{BASE_PATH}biogrid/YEAST_GENE_RBP_withSEQ.pkl'

Y_G_G_RBP = pd.read_pickle(yeast_gene_gene_rbp)
Y_G_G_RBP
Y_G_G_RBP = Y_G_G_RBP.drop(columns={'Head_SEQ', 'Tail_SEQ'})
Y_G_G_RBP['head_detail_name'] = Y_G_G_RBP['head'].map(NCBI_Yeast_Locustag_Descrip_dict)
Y_G_G_RBP['tail_detail_name'] = Y_G_G_RBP['tail'].map(NCBI_Yeast_Locustag_Descrip_dict)
Y_G_G_RBP
Y_G_G_RBP = Y_G_G_RBP[~Y_G_G_RBP['head_detail_name'].isna()]
Y_G_G_RBP = Y_G_G_RBP[~Y_G_G_RBP['tail_detail_name'].isna()]
Y_G_G_RBP['head_id_is'] = 'SGD_SysematicName'
Y_G_G_RBP['tail_id_is'] = 'SGD_SysematicName'
Y_G_G_RBP['relation_type'] = 'Gene_Gene'
Y_G_G_RBP['kg_source'] = 'BioGrid'
Y_G_G_RBP['species'] = 'S.cerevisae'
Y_G_G_RBP['head_type'] = 'Gene'
Y_G_G_RBP['tail_type'] = 'Gene'
Y_G_G_RBP['relation'] = 'Gene_Gene'
Y_G_G_RBP
Y_G_G_RBP

,head,relation,tail,weight,head_type,tail_type,normalized_weight,head_detail_name,tail_detail_name,head_id_is,tail_id_is,relation_type,kg_source,species
15210847,YNL016W,Gene_Gene,YGL049C,934.0,Gene,Gene,9.451162,Pub1p,translation initiation factor eIF4G,SGD_SysematicName,SGD_SysematicName,Gene_Gene,BioGrid,S.cerevisae
15210848,YHL034C,Gene_Gene,YGL049C,815.0,Gene,Gene,8.446366,Sbp1p,translation initiation factor eIF4G,SGD_SysematicName,SGD_SysematicName,Gene_Gene,BioGrid,S.cerevisae
15210849,YPR163C,Gene_Gene,YGL049C,976.0,Gene,Gene,9.805796,Tif3p,translation initiation factor eIF4G,SGD_SysematicName,SGD_SysematicName,Gene_Gene,BioGrid,S.cerevisae
15210850,YER165W,Gene_Gene,YGL049C,999.0,Gene,Gene,10.000000,polyadenylate-binding protein,translation initiation factor eIF4G,SGD_SysematicName,SGD_SysematicName,Gene_Gene,BioGrid,S.cerevisae
15210851,YNL255C,Gene_Gene,YGL049C,710.0,Gene,Gene,7.559781,mRNA-binding translational activator GIS2,translation initiation factor eIF4G,SGD_SysematicName,SGD_SysematicName,Gene_Gene,BioGrid,S.cerevisae
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15293129,YHR143W,Gene_Gene,YNL046W,571.0,Gene,Gene,6.386112,Dse2p,uncharacterized protein,SGD_SysematicName,SGD_SysematicName,Gene_Gene,BioGrid,S.cerevisae
15293130,YGL061C,Gene_Gene,YBR233W-A,987.0,Gene,Gene,9.898676,Duo1p,Dad3p,SGD_SysematicName,SGD_SysematicName,Gene_Gene,BioGrid,S.cerevisae
15293131,YGL151W,Gene_Gene,YBL093C,951.0,Gene,Gene,9.594704,Nut1p,Rox3p,SGD_SysematicName,SGD_SysematicName,Gene_Gene,BioGrid,S.cerevisae
15293132,YGL151W,Gene_Gene,YMR112C,888.0,Gene,Gene,9.062753,Nut1p,Med11p,SGD_SysematicName,SGD_SysematicName,Gene_Gene,BioGrid,S.cerevisae
15293133,YGR143W,Gene_Gene,YNR063W,446.0,Gene,Gene,5.330654,beta-glucan synthesis-associated protein SKN1,Pul4p,SGD_SysematicName,SGD_SysematicName,Gene_Gene,BioGrid,S.cerevisae

In [22]:
# First, concatenate all dataframes as before (assuming `final_df` already exists from earlier step)

# Group by the 3 key columns
group_cols = ['head', 'relation', 'tail']

# For kg_source, combine with '::'
def merge_sources(x):
    return '::'.join(sorted(set(x.dropna())))

# Merge duplicates
final_df_dedup = Y_G_G_RBP.groupby(group_cols, as_index=False).agg({
    'head_type': 'first',
    'relation_type': 'first',
    'tail_type': 'first',
    'kg_source': merge_sources,
    'head_id_is': 'first',
    'tail_id_is': 'first',
    'head_detail_name': 'first',
    'tail_detail_name': 'first',
    'species': 'first'
})
final_df_dedup

,head,relation,tail,head_type,relation_type,tail_type,kg_source,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,Q0115,Gene_Gene,Q0045,Gene,Gene_Gene,Gene,BioGrid,SGD_SysematicName,SGD_SysematicName,cytochrome b mRNA maturase bI3,cytochrome c oxidase subunit 1,S.cerevisae
1,Q0115,Gene_Gene,Q0050,Gene,Gene_Gene,Gene,BioGrid,SGD_SysematicName,SGD_SysematicName,cytochrome b mRNA maturase bI3,intron-encoded reverse transcriptase aI1,S.cerevisae
2,Q0115,Gene_Gene,Q0055,Gene,Gene_Gene,Gene,BioGrid,SGD_SysematicName,SGD_SysematicName,cytochrome b mRNA maturase bI3,intron-encoded reverse transcriptase aI2,S.cerevisae
3,Q0115,Gene_Gene,Q0060,Gene,Gene_Gene,Gene,BioGrid,SGD_SysematicName,SGD_SysematicName,cytochrome b mRNA maturase bI3,intron-encoded DNA endonuclease aI3,S.cerevisae
4,Q0115,Gene_Gene,Q0065,Gene,Gene_Gene,Gene,BioGrid,SGD_SysematicName,SGD_SysematicName,cytochrome b mRNA maturase bI3,intron-encoded DNA endonuclease aI4,S.cerevisae
...,...,...,...,...,...,...,...,...,...,...,...,...
81865,YPR189W,Gene_Gene,YOR001W,Gene,Gene_Gene,Gene,BioGrid,SGD_SysematicName,SGD_SysematicName,SKI complex subunit tetratricopeptide repeat p...,exosome nuclease subunit RRP6,S.cerevisae
81866,YPR189W,Gene_Gene,YOR063W,Gene,Gene_Gene,Gene,BioGrid,SGD_SysematicName,SGD_SysematicName,SKI complex subunit tetratricopeptide repeat p...,ribosomal 60S subunit protein L3,S.cerevisae
81867,YPR189W,Gene_Gene,YOR076C,Gene,Gene_Gene,Gene,BioGrid,SGD_SysematicName,SGD_SysematicName,SKI complex subunit tetratricopeptide repeat p...,Ski7p,S.cerevisae
81868,YPR189W,Gene_Gene,YOR096W,Gene,Gene_Gene,Gene,BioGrid,SGD_SysematicName,SGD_SysematicName,SKI complex subunit tetratricopeptide repeat p...,ribosomal 40S subunit protein S7A,S.cerevisae
81869,YPR189W,Gene_Gene,YPL081W,Gene,Gene_Gene,Gene,BioGrid,SGD_SysematicName,SGD_SysematicName,SKI complex subunit tetratricopeptide repeat p...,ribosomal 40S subunit protein S9A,S.cerevisae

In [23]:
OUT_PATH = "/storage/Arushi/090526_EvoAge/kg_formation/processed_data/biogrid/"

final_df_dedup.to_csv(f'{OUT_PATH}biogrid_YEAST_GENE_GENE_2.csv',index = None)
final_df_dedup

,head,relation,tail,head_type,relation_type,tail_type,kg_source,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,Q0115,Gene_Gene,Q0045,Gene,Gene_Gene,Gene,BioGrid,SGD_SysematicName,SGD_SysematicName,cytochrome b mRNA maturase bI3,cytochrome c oxidase subunit 1,S.cerevisae
1,Q0115,Gene_Gene,Q0050,Gene,Gene_Gene,Gene,BioGrid,SGD_SysematicName,SGD_SysematicName,cytochrome b mRNA maturase bI3,intron-encoded reverse transcriptase aI1,S.cerevisae
2,Q0115,Gene_Gene,Q0055,Gene,Gene_Gene,Gene,BioGrid,SGD_SysematicName,SGD_SysematicName,cytochrome b mRNA maturase bI3,intron-encoded reverse transcriptase aI2,S.cerevisae
3,Q0115,Gene_Gene,Q0060,Gene,Gene_Gene,Gene,BioGrid,SGD_SysematicName,SGD_SysematicName,cytochrome b mRNA maturase bI3,intron-encoded DNA endonuclease aI3,S.cerevisae
4,Q0115,Gene_Gene,Q0065,Gene,Gene_Gene,Gene,BioGrid,SGD_SysematicName,SGD_SysematicName,cytochrome b mRNA maturase bI3,intron-encoded DNA endonuclease aI4,S.cerevisae
...,...,...,...,...,...,...,...,...,...,...,...,...
81865,YPR189W,Gene_Gene,YOR001W,Gene,Gene_Gene,Gene,BioGrid,SGD_SysematicName,SGD_SysematicName,SKI complex subunit tetratricopeptide repeat p...,exosome nuclease subunit RRP6,S.cerevisae
81866,YPR189W,Gene_Gene,YOR063W,Gene,Gene_Gene,Gene,BioGrid,SGD_SysematicName,SGD_SysematicName,SKI complex subunit tetratricopeptide repeat p...,ribosomal 60S subunit protein L3,S.cerevisae
81867,YPR189W,Gene_Gene,YOR076C,Gene,Gene_Gene,Gene,BioGrid,SGD_SysematicName,SGD_SysematicName,SKI complex subunit tetratricopeptide repeat p...,Ski7p,S.cerevisae
81868,YPR189W,Gene_Gene,YOR096W,Gene,Gene_Gene,Gene,BioGrid,SGD_SysematicName,SGD_SysematicName,SKI complex subunit tetratricopeptide repeat p...,ribosomal 40S subunit protein S7A,S.cerevisae
81869,YPR189W,Gene_Gene,YPL081W,Gene,Gene_Gene,Gene,BioGrid,SGD_SysematicName,SGD_SysematicName,SKI complex subunit tetratricopeptide repeat p...,ribosomal 40S subunit protein S9A,S.cerevisae

# Rough work

In [42]:
# import pandas as pd

# # List of your DataFrame variable names
# df_names = [
#     'Y_P_P', 'Y_G_G', 'Y_G_G_TF', 'Y_G_G_RBP'
# ]

# # The required columns
# required_columns = [
#     'head', 'relation', 'tail', 'head_type', 'relation_type', 'tail_type',
#     'kg_source', 'head_id_is', 'tail_id_is', 'head_detail_name', 'tail_detail_name'
# ]

# # List to hold cleaned dataframes
# df_list = []

# # Loop through each DataFrame name, get it from globals(), align columns
# for name in df_names:
#     df = globals()[name].copy()  # Get the DataFrame object from its name
#     for col in required_columns:
#         if col not in df.columns:
#             df[col] = pd.NA  # Add missing columns with NaN
#     df = df[required_columns]  # Reorder/select only required columns
#     df_list.append(df)

# # Concatenate all into one
# final_df = pd.concat(df_list, ignore_index=True)
# final_df

,head,relation,tail,head_type,relation_type,tail_type,kg_source,head_id_is,tail_id_is,head_detail_name,tail_detail_name
0,Q0045,Protein_Protein,YBR146W,Protein,NaN,Protein,NaN,SGD_SysematicName,SGD_SysematicName,cytochrome c oxidase subunit 1,mitochondrial 37S ribosomal protein MRPS9
1,Q0045,Protein_Protein,YOR176W,Protein,NaN,Protein,NaN,SGD_SysematicName,SGD_SysematicName,cytochrome c oxidase subunit 1,ferrochelatase HEM15
2,Q0045,Protein_Protein,YNL121C,Protein,NaN,Protein,NaN,SGD_SysematicName,SGD_SysematicName,cytochrome c oxidase subunit 1,protein channel TOM70
3,Q0045,Protein_Protein,YFR039C,Protein,NaN,Protein,NaN,SGD_SysematicName,SGD_SysematicName,cytochrome c oxidase subunit 1,Osw7p
4,Q0045,Protein_Protein,YLR259C,Protein,NaN,Protein,NaN,SGD_SysematicName,SGD_SysematicName,cytochrome c oxidase subunit 1,chaperone ATPase HSP60
...,...,...,...,...,...,...,...,...,...,...,...
3733867,YHR143W,Gene-RBProtein,YNL046W,Gene,Gene_Gene,RBProtein,GenePatri,SGD_SysematicName,SGD_SysematicName,Dse2p,uncharacterized protein
3733868,YGL061C,Gene-RBProtein,YBR233W-A,Gene,Gene_Gene,RBProtein,GenePatri,SGD_SysematicName,SGD_SysematicName,Duo1p,Dad3p
3733869,YGL151W,Gene-RBProtein,YBL093C,Gene,Gene_Gene,RBProtein,GenePatri,SGD_SysematicName,SGD_SysematicName,Nut1p,Rox3p
3733870,YGL151W,Gene-RBProtein,YMR112C,Gene,Gene_Gene,RBProtein,GenePatri,SGD_SysematicName,SGD_SysematicName,Nut1p,Med11p
3733871,YGR143W,Gene-RBProtein,YNR063W,Gene,Gene_Gene,RBProtein,GenePatri,SGD_SysematicName,SGD_SysematicName,beta-glucan synthesis-associated protein SKN1,Pul4p

In [56]:
# set(final_df['relation']),set(final_df['head_type']),set(final_df['tail_type']),set(final_df['kg_source']),set(final_df['head_id_is']),set(final_df['tail_id_is'])

In [57]:
# final_df['relation'] = 'Gene_Gene'

# final_df['head_type'] = 'Gene'
# final_df['tail_type'] = 'Gene'

In [58]:
# set(final_df['relation']),set(final_df['head_type']),set(final_df['tail_type']),set(final_df['kg_source']),set(final_df['head_id_is']),set(final_df['tail_id_is'])

In [46]:
set(final_df['relation_type'])

{'3-D protein structure of interacting orthologous proteins between two yeast proteins',
 'Gene_Gene',
 'Inferred links by similar profiles of genetic interaction partners',
 'co-citation',
 'co-expression',
 'co-occurrence of protein domains between two coding genes',
 'high-throughput protein-protein interactions',
 nan,
 'similar genomic context of bacterial orthologs of two yeast genes',
 'similar phylogenetic profiles between two yeast genes',
 'small/medium-scale protein-protein interactions'}

In [47]:
# Count true NaN values
true_nan_count = final_df.isna().sum()

# Count string 'NAN' values (case-insensitive)
string_nan_count = final_df.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

# Combine both counts
nan_summary = pd.DataFrame({
    'NaN_count': true_nan_count,
    "'NAN'_string_count": string_nan_count,
    'Total_NaN_like': true_nan_count + string_nan_count
})
nan_summary

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type       2743780             2743780         5487560
tail_type                 0                   0               0
kg_source           2743780             2743780         5487560
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0

In [48]:
# First, concatenate all dataframes as before (assuming `final_df` already exists from earlier step)

# Group by the 3 key columns
group_cols = ['head', 'relation', 'tail']

# For kg_source, combine with '::'
def merge_sources(x):
    return '::'.join(sorted(set(x.dropna())))

# Merge duplicates
final_df_dedup = final_df.groupby(group_cols, as_index=False).agg({
    'head_type': 'first',
    'relation_type': 'first',
    'tail_type': 'first',
    'kg_source': merge_sources,
    'head_id_is': 'first',
    'tail_id_is': 'first',
    'head_detail_name': 'first',
    'tail_detail_name': 'first'
})
final_df_dedup

,head,relation,tail,head_type,relation_type,tail_type,kg_source,head_id_is,tail_id_is,head_detail_name,tail_detail_name
0,Q0045,Gene_Gene,Q0050,Gene,co-citation,Gene,YeastNet,SGD_SysematicName,SGD_SysematicName,cytochrome c oxidase subunit 1,intron-encoded reverse transcriptase aI1
1,Q0045,Gene_Gene,Q0055,Gene,co-citation,Gene,YeastNet,SGD_SysematicName,SGD_SysematicName,cytochrome c oxidase subunit 1,intron-encoded reverse transcriptase aI2
2,Q0045,Gene_Gene,Q0060,Gene,co-citation,Gene,YeastNet,SGD_SysematicName,SGD_SysematicName,cytochrome c oxidase subunit 1,intron-encoded DNA endonuclease aI3
3,Q0045,Gene_Gene,Q0065,Gene,co-citation,Gene,YeastNet,SGD_SysematicName,SGD_SysematicName,cytochrome c oxidase subunit 1,intron-encoded DNA endonuclease aI4
4,Q0045,Gene_Gene,Q0070,Gene,co-occurrence of protein domains between two c...,Gene,YeastNet,SGD_SysematicName,SGD_SysematicName,cytochrome c oxidase subunit 1,intron-encoded DNA endonuclease aI5 alpha
...,...,...,...,...,...,...,...,...,...,...,...
3278568,YPR204W,Gene_Gene,YPR190C,Gene,None,Gene,,SGD_SysematicName,SGD_SysematicName,Y' element ATP-dependent helicase,DNA-directed RNA polymerase III subunit C82
3278569,YPR204W,Gene_Gene,YPR192W,Gene,None,Gene,,SGD_SysematicName,SGD_SysematicName,Y' element ATP-dependent helicase,Aqy1p
3278570,YPR204W,Gene_Gene,YPR201W,Gene,None,Gene,,SGD_SysematicName,SGD_SysematicName,Y' element ATP-dependent helicase,Arr3p
3278571,YPR204W,Gene_Gene,YPR202W,Gene,None,Gene,,SGD_SysematicName,SGD_SysematicName,Y' element ATP-dependent helicase,uncharacterized protein
3278572,YPR204W,Gene_Gene,YPR203W,Gene,None,Gene,,SGD_SysematicName,SGD_SysematicName,Y' element ATP-dependent helicase,uncharacterized protein

In [22]:
# final_df_dedup.to_csv('GENE_GENE/ALL_YEAST_GENE_GENE.csv',index = None)